import{test,expect}from'@playwright/test';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,version='a'.repeat(64);
const report={state:'needs_review',updatedAt:'2026-10-03T00:00:00Z',checkedAt:'2026-10-03T00:01:00Z',errorCode:'JOB_DEADLINE_REACHED',canRetry:true,version,details:[{at:'2026-10-03T00:00:00Z',code:'JOB_DEADLINE_REACHED'}]};
const data={enabled:true,allPublished:false,revision:0,eligibleCount:103,startedCount:2,nextCursor:id(90),remoteAvailable:true,rows:[{id:id(1),name:'학생 A',published:false,attemptId:id(10),state:'submitted',startedAt:'2026-10-03T00:00:00Z',updatedAt:'2026-10-03T00:00:00Z',report,statusAvailable:true},{id:id(2),name:'학생 B',published:false,attemptId:null,state:'not_started',startedAt:null,updatedAt:null,report:null,statusAvailable:true},{id:id(3),name:'학생 C',published:true,attemptId:id(11),state:'submitted',report:{...report,state:'ready',errorCode:null,canRetry:false,details:[]},statusAvailable:true}]};
test('admin can find direct diagnosis, confirm whole or individual publication and see progress without document overflow',async({page},info)=>{
 const writes:unknown[]=[];let latest=data;
 await page.route('**/api/admin/diagnosis**',async route=>{if(route.request().method()==='POST'){const b=route.request().postDataJSON();writes.push(b);latest={...latest,revision:latest.revision+1,allPublished:b.action==='publish_all'?b.enabled:latest.allPublished,rows:latest.rows.map(r=>b.action==='publish_all'||b.userId===r.id?{...r,published:b.enabled}:r)};await route.fulfill({json:{revision:latest.revision}});return;}await route.fulfill({json:latest});});
 await page.goto('/diagnosis-test?manage');await expect(page.getByRole('heading',{name:'N6 진단 관리',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'N6 진단 받기'})).toHaveAttribute('href','/admin/diagnosis');
 await page.getByRole('button',{name:'한 번에 모두 공개'}).click();await expect(page.getByRole('dialog')).toContainText('103명');await page.getByRole('button',{name:'취소',exact:true}).click();expect(writes).toHaveLength(0);
 await page.getByRole('button',{name:'학생 B 진단 공개'}).click();await expect(page.getByRole('dialog')).toContainText('학생 B');await page.getByRole('button',{name:'공개하기',exact:true}).click();await expect(page.getByRole('button',{name:'학생 B 진단 닫기'})).toBeVisible();expect(writes[0]).toMatchObject({action:'publish_member',userId:id(2),revision:0,enabled:true});
 await page.getByRole('button',{name:'한 번에 모두 공개'}).click();await page.getByRole('button',{name:'공개하기',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'진단 공개 설정을 저장했습니다.'})).toBeVisible();expect(writes[1]).toMatchObject({action:'publish_all',revision:1});
 await page.screenshot({path:info.outputPath('diagnosis-management.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('retry confirms frozen answers and uses same request after lost acknowledgment; ready reports never offer regeneration',async({page})=>{
 const writes:Record<string,unknown>[]=[];let lost=true;
 await page.route('**/api/admin/diagnosis**',async route=>{if(route.request().method()==='POST'){writes.push(route.request().postDataJSON());if(lost){lost=false;await route.abort();return;}await route.fulfill({json:{state:'queued'}});return;}await route.fulfill({json:data});});
 await page.goto('/diagnosis-test?manage');const row=page.getByRole('row',{name:/학생 A/}),ready=page.getByRole('row',{name:/학생 C/});await expect(ready.getByRole('button',{name:'보고서 재발급'})).toBeDisabled();await row.getByText('진행·오류 기록 보기').click();await expect(row).toContainText('JOB_DEADLINE_REACHED');
 await row.getByRole('button',{name:'보고서 재발급'}).click();await expect(page.getByRole('dialog')).toContainText('검사를 다시 할 필요는 없습니다');await page.getByRole('button',{name:'저장된 답변으로 재발급'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible();await page.getByRole('button',{name:'저장된 답변으로 재발급'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(writes).toHaveLength(2);expect(writes[1]).toEqual(writes[0]);expect(writes[0]).toMatchObject({action:'retry',attemptId:id(10),expectedVersion:version});
});
test('temporary remote outage shows last check and disables retry; failed reads disable all changes',async({page})=>{
 let failed=false;await page.route('**/api/admin/diagnosis**',route=>route.fulfill(failed?{status:503,json:{error:'조회할 수 없습니다.'}}:{json:{...data,remoteAvailable:false,rows:data.rows.map(r=>({...r,statusAvailable:false,report:r.report?{...r.report,canRetry:false}:null}))}}));
 await page.goto('/diagnosis-test?manage');await expect(page.getByText(/마지막 확인 기록/)).toBeVisible();for(const b of await page.getByRole('button',{name:'보고서 재발급'}).all())await expect(b).toBeDisabled();failed=true;await page.getByRole('button',{name:'새로고침'}).click();await expect(page.getByRole('alert')).toContainText('조회할 수 없습니다');await expect(page.getByRole('button',{name:'한 번에 모두 공개'})).toBeDisabled();
});
test('pagination and search use bounded server pages; 320px layout keeps controls readable',async({page},info)=>{
 const queries:string[]=[];await page.route('**/api/admin/diagnosis**',async route=>{queries.push(route.request().url());await route.fulfill({json:data});});await page.setViewportSize({width:320,height:844});await page.goto('/diagnosis-test?manage');await page.getByRole('button',{name:'다음',exact:true}).click();await expect.poll(()=>queries.at(-1)).toContain('before=');await page.getByRole('textbox',{name:'수강생 이름'}).fill('학생 A');await page.getByRole('button',{name:'검색',exact:true}).click();await expect.poll(()=>queries.at(-1)).toContain('query=');expect(new URL(queries.at(-1)!).searchParams.has('before')).toBe(false);await page.screenshot({path:info.outputPath('diagnosis-management-320.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
