import {test,expect} from '@playwright/test';
const code='33333333-3333-4333-8333-333333333333';
const url='/templates-admin-test?followup='+code+'&revision=2';
test('saved followup requires explicit import and saves only an inactive marketing template',async({page})=>{
 let reads=0;const writes:Record<string,unknown>[]=[];
 await page.route('**/api/conversion/followup**',r=>{reads++;return r.fulfill({json:{drafts:[{channel:'direct',purpose:'encore',body:'합성 안내 문구',revision:2}]}});});
 await page.route('**/api/platform/workflows',r=>{writes.push(r.request().postDataJSON());return r.fulfill({json:{ok:true}});});
 await page.goto(url);
 await expect(page.getByRole('button',{name:'저장된 개별 초안 불러오기',exact:true})).toBeVisible();
 expect(reads).toBe(0);expect(writes).toHaveLength(0);
 await page.getByRole('button',{name:'저장된 개별 초안 불러오기',exact:true}).click();
 await expect(page.getByLabel('메시지 내용')).toHaveValue('합성 안내 문구');
 await expect(page.getByLabel('메시지 목적')).toHaveValue('marketing');
 await expect(page.getByLabel('메시지 목적')).toBeDisabled();
 await expect(page.getByRole('checkbox')).not.toBeChecked();
 await expect(page.getByRole('checkbox')).toBeDisabled();
 await page.getByRole('button',{name:'저장하기',exact:true}).click();
 await expect.poll(()=>writes.length).toBe(1);
 expect(writes[0]).toMatchObject({action:'crm-save',kind:'template',purpose:'marketing',channel:'lms',isActive:false,content:'합성 안내 문구'});
 expect(writes[0].id).toBeUndefined();expect(writes[0].tagId).toBeUndefined();expect(writes[0].scheduledAt).toBeUndefined();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('stale or inaccessible source never populates the form; edits block importing',async({page})=>{
 await page.route('**/api/conversion/followup**',r=>r.fulfill({json:{drafts:[{channel:'direct',body:'새 버전',revision:3}]}}));
 await page.goto(url);
 await page.getByRole('button',{name:'저장된 개별 초안 불러오기',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('원본 초안이 변경');
 await expect(page.getByLabel('메시지 내용')).toHaveValue('');
 await page.getByLabel('메시지 내용').fill('작성 중인 내용');
 await expect(page.getByRole('button',{name:'저장된 개별 초안 불러오기',exact:true})).toBeDisabled();
 await expect(page.getByLabel('메시지 내용')).toHaveValue('작성 중인 내용');
 await page.getByRole('button',{name:'새로 등록',exact:true}).click();
 await expect(page.getByLabel('메시지 내용')).toHaveValue('');
 await expect(page.getByRole('button',{name:'저장된 개별 초안 불러오기',exact:true})).toBeEnabled();
});
test('denied source and room-only response cannot import a direct message',async({page})=>{
 let denied=true;
 await page.route('**/api/conversion/followup**',r=>denied?r.fulfill({status:403,json:{error:'개별 안내 권한이 없습니다.'}}):r.fulfill({json:{drafts:[{channel:'room',body:'방 공지',revision:2}]}}));
 await page.goto(url);
 await page.getByRole('button',{name:'저장된 개별 초안 불러오기',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('개별 안내 권한이 없습니다.');
 denied=false;
 await page.getByRole('button',{name:'저장된 개별 초안 불러오기',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('접근할 수 없습니다');
 await expect(page.getByLabel('메시지 내용')).toHaveValue('');
});

test('Alimtalk draft stays editable and off until an approved Kakao template number is entered',async({page})=>{
 const writes:Record<string,unknown>[]=[];
 await page.route('**/api/platform/workflows',r=>{writes.push(r.request().postDataJSON());return r.fulfill({json:{ok:true}});});
 await page.goto('/templates-admin-test');
 await page.getByLabel('발송 채널').selectOption('alimtalk');
 await expect(page.getByLabel('메시지 목적')).toHaveValue('transactional');
 await expect(page.getByLabel('메시지 목적')).toBeDisabled();
 await expect(page.getByLabel('카카오 승인 템플릿 번호')).toHaveValue('');
 await expect(page.getByRole('checkbox')).not.toBeChecked();
 await expect(page.getByRole('checkbox')).toBeDisabled();
 await page.getByLabel('템플릿 이름').fill('결제 완료 안내 초안');
 await page.getByLabel('메시지 내용').fill('결제가 확인되었습니다. 안내 문구는 여기서 수정할 수 있습니다.');
 await page.getByRole('button',{name:'저장하기',exact:true}).click();
 await expect.poll(()=>writes.length).toBe(1);
 expect(writes[0]).toMatchObject({action:'crm-save',kind:'template',channel:'alimtalk',purpose:'transactional',name:'결제 완료 안내 초안',content:'결제가 확인되었습니다. 안내 문구는 여기서 수정할 수 있습니다.',alimtalkTemplateId:'',isActive:false});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
