import {expect,test,type Page} from '@playwright/test';
const id=(n:number)=>`11111111-1111-4111-8111-${String(n).padStart(12,'0')}`;
const candidates=[1,2,3].map(n=>({id:id(n),title:'질문 '+n,content:'참고할 질문 내용 '+n,learning_context:'시험 수업'}));
const reference={lessonTitle:'시험 수업',revision:id(8),truncated:true,imageIncluded:true,imageFirstFrame:true,contextMissing:false};
async function open(page:Page){await page.goto('/question-ai-batch-test');await page.getByRole('button',{name:'미답변 AI 초안',exact:true}).click();}
async function thread(page:Page,{lost=false,existing=false}={}){
 const writes:Record<string,unknown>[]=[];let answered=false;
 await page.route('**/api/platform/question-thread?**',r=>{
  if(r.request().method()==='POST'){const body=r.request().postDataJSON();writes.push(body);if(lost&&writes.length===1)return r.fulfill({status:503,json:{error:'응답 확인 실패'}});answered=true;return r.fulfill({json:{id:body.requestId,questionId:body.questionId}});}
  const q=new URL(r.request().url()).searchParams.get('question');return r.fulfill({json:{question:{id:q,title:'검토할 질문',content:'실제 질문 원문',headId:existing?id(99):null,status:'open',resolved:false,archived:false},answers:existing?[{id:id(99),authorName:'다른 운영자',content:'먼저 등록한 답변',createdAt:'2026-09-01'}]:answered?[{id:id(90),authorName:'운영자',content:'방금 등록한 답변',createdAt:'2026-09-01'}]:[],nextCursor:null,canAnswer:true}});
 });return writes;
}
test('batch crosses all cursor pages, keeps editable drafts, isolates failures and only publishes after individual review',async({page},info)=>{
 let rounds=0,thirdFailed=true,inFlight=0,maxInFlight=0;const posts:Record<string,unknown>[]=[],listQueries:string[]=[];
 await page.route('**/api/admin/questions/answer-drafts?**',r=>{const u=new URL(r.request().url());listQueries.push(u.search);if(!u.searchParams.has('cursor'))rounds++;return r.fulfill({json:{rows:u.searchParams.has('cursor')?[candidates[2]]:candidates.slice(0,2),snapshot:'2026-09-01T00:00:00.000Z',nextCursor:u.searchParams.has('cursor')?null:id(2)}});});
 await page.route('**/api/admin/questions/answer-draft',async r=>{const b=r.request().postDataJSON();posts.push(b);inFlight++;maxInFlight=Math.max(maxInFlight,inFlight);await new Promise(resolve=>setTimeout(resolve,60));inFlight--;if(b.questionId===id(2))return r.fulfill({status:409,json:{error:'다른 운영자가 답변했습니다.'}});if(b.questionId===id(3)&&thirdFailed)return r.fulfill({status:502,json:{error:'초안 생성 실패'}});return r.fulfill({json:{draft:'AI 초안 '+b.questionId,reference}});});
 const writes=await thread(page);await open(page);await page.getByRole('button',{name:'미답변 전체 초안 만들기'}).click();await expect(page.getByRole('status')).toContainText('목록 확인을 마쳤습니다');expect(posts).toHaveLength(3);expect(maxInFlight).toBeLessThanOrEqual(2);expect(maxInFlight).toBe(2);expect(writes).toHaveLength(0);expect(listQueries[1]).toContain('cursor=');expect(listQueries[1]).toContain('snapshot=');
 const first=page.getByRole('article').filter({has:page.getByRole('heading',{name:'질문 1',exact:true})});await first.getByRole('textbox',{name:'답변 초안'}).fill('운영자가 수정한 내용');thirdFailed=false;await page.getByRole('button',{name:'미답변 전체 초안 만들기'}).click();await expect(page.getByRole('status')).toContainText('실패 0개');expect(rounds).toBe(2);expect(posts.filter(p=>p.questionId===id(1))).toHaveLength(1);await expect(first.getByRole('textbox',{name:'답변 초안'})).toHaveValue('운영자가 수정한 내용');
 await first.getByRole('button',{name:'초안 검토하고 등록'}).click();await expect(page.getByRole('textbox',{name:'새 답변',exact:true})).toHaveValue('운영자가 수정한 내용');await expect(page.getByText('실제 질문 원문')).toBeVisible();expect(writes).toHaveLength(0);
 await page.getByRole('button',{name:'답변 추가하기'}).click();await expect(page.getByRole('status').filter({hasText:'답변을 추가했습니다'})).toBeVisible();expect(writes).toHaveLength(1);await expect(page.locator('html')).toHaveAttribute('data-question-refreshes','1');expect(writes[0]).toMatchObject({questionId:id(1),content:'운영자가 수정한 내용',expectedHeadId:null});await page.locator('.admin-dialog-footer').getByRole('button',{name:'닫기',exact:true}).click();await expect(first.getByText('답변을 등록했습니다.')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:info.outputPath('question-ai-batch.png'),fullPage:true});
});
test('stop finishes only the in-flight pair and restart generates the remaining unanswered question',async({page})=>{
 let release!:()=>void;const waiting=new Promise<void>(resolve=>{release=resolve;});const requested:string[]=[];
 await page.route('**/api/admin/questions/answer-drafts?**',r=>r.fulfill({json:{rows:candidates,snapshot:'2026-09-01T00:00:00.000Z',nextCursor:null}}));
 await page.route('**/api/admin/questions/answer-draft',async r=>{const q=r.request().postDataJSON().questionId;requested.push(q);await waiting;return r.fulfill({json:{draft:'완료된 초안 '+q}});});
 await open(page);await page.getByRole('button',{name:'미답변 전체 초안 만들기'}).click();await expect.poll(()=>requested.length).toBe(2);await page.getByRole('button',{name:'초안 만들기 중지'}).click();release();await expect(page.getByRole('status')).toContainText('중지했습니다');expect(requested).toHaveLength(2);
 await page.getByRole('button',{name:'미답변 전체 초안 만들기'}).click();await expect(page.getByRole('status')).toContainText('목록 확인을 마쳤습니다');expect(requested).toHaveLength(3);expect(new Set(requested).size).toBe(3);
});
test('review shows a concurrent reply, retains edits on close and retries unknown registration with the same payload',async({page})=>{
 await page.route('**/api/admin/questions/answer-drafts?**',r=>r.fulfill({json:{rows:[candidates[0]],snapshot:'2026-09-01T00:00:00.000Z',nextCursor:null}}));await page.route('**/api/admin/questions/answer-draft',r=>r.fulfill({json:{draft:'검토 전 초안'}}));const writes=await thread(page,{lost:true,existing:true});
 await open(page);await page.getByRole('button',{name:'미답변 전체 초안 만들기'}).click();await expect(page.getByRole('textbox',{name:'답변 초안'})).toHaveValue('검토 전 초안');await page.getByRole('button',{name:'초안 검토하고 등록'}).click();await expect(page.getByText('먼저 등록한 답변')).toBeVisible();await page.getByRole('textbox',{name:'새 답변',exact:true}).fill('수정해서 남긴 초안');await page.locator('.admin-dialog-footer').getByRole('button',{name:'닫기',exact:true}).click();await expect(page.getByRole('textbox',{name:'답변 초안'})).toHaveValue('수정해서 남긴 초안');
 await page.getByRole('button',{name:'초안 검토하고 등록'}).click();await page.getByRole('button',{name:'답변 추가하기'}).click();await expect(page.getByRole('textbox',{name:'새 답변',exact:true})).toBeDisabled();await page.getByRole('button',{name:'같은 요청 결과 확인'}).click();await expect(page.getByRole('status').filter({hasText:'답변을 추가했습니다'})).toBeVisible();expect(writes[0]).toEqual(writes[1]);expect(writes[0].expectedHeadId).toBe(id(99));
});
test('list failures do not erase prepared drafts and leaving the page warns before discarding them',async({page})=>{
 let failed=false;await page.route('**/api/admin/questions/answer-drafts?**',r=>r.fulfill(failed?{status:503,json:{error:'목록 연결 실패'}}:{json:{rows:[candidates[0]],snapshot:'2026-09-01T00:00:00.000Z',nextCursor:null}}));await page.route('**/api/admin/questions/answer-draft',r=>r.fulfill({json:{draft:'보존할 초안'}}));
 await open(page);await page.getByRole('button',{name:'미답변 전체 초안 만들기'}).click();await expect(page.getByRole('textbox',{name:'답변 초안'})).toHaveValue('보존할 초안');failed=true;await page.getByRole('button',{name:'미답변 전체 초안 만들기'}).click();await expect(page.getByRole('status')).toContainText('목록 연결 실패');await expect(page.getByRole('textbox',{name:'답변 초안'})).toHaveValue('보존할 초안');page.once('dialog',d=>d.dismiss());await page.getByRole('link',{name:'다른 메뉴'}).click();await expect(page).toHaveURL(/question-ai-batch-test/);
});
