// Article list: member-only free VOD banner. Kept separate from the scheduled p2 free class detail.
const articleBannerConfig=JSON.parse(JSON.stringify(ARTICLE_BANNER_DEFAULT));
Object.assign(state,{articleType:'전체',articleQuery:'',articleLesson:0,articlePlaying:false,articleReturn:false});
DATA.articles.forEach(a=>{a.type='글';a.videoURL='';});
DATA.articles.push({id:4,type:'영상',tag:'마케팅 실행',title:'고객의 질문을 콘텐츠로 바꾸는 법',desc:'한 가지 고객 질문으로 콘텐츠의 주제와 전달 순서를 설계합니다.',date:'2026.09.11',minutes:'8분 40초',videoURL:''},{id:5,type:'영상',tag:'AI 활용',title:'좋은 AI 요청문에 필요한 세 가지',desc:'업무의 목적과 맥락, 원하는 결과를 구체적으로 전달해 보세요.',date:'2026.09.11',minutes:'11분 20초',videoURL:''});
const originalArticleCard=articleCard;
articleCard=function(a){if(a.type!=='영상')return originalArticleCard(a);return `<a class="article-card article-video-card" href="#article" data-article="${a.id}"><div class="article-video-cover"><span class="article-video-label">VIDEO INSIGHT</span><span class="article-video-play">${icon('play')}</span><span class="article-video-duration">${a.minutes}</span></div><div class="article-video-body"><div class="flex gap8">${badge('영상','red')}<span class="tag">${a.tag}</span></div><h3>${a.title}</h3><p class="muted" style="font-size:var(--type-small)">${a.desc}</p><span class="meta">${a.date} · 영상 아티클 ${icon('arrow')}</span></div></a>`;};
function articleResults(){return DATA.articles.filter(a=>(state.articleTag==='전체'||a.tag===state.articleTag)&&(state.articleType==='전체'||a.type===state.articleType)&&a.title.toLowerCase().includes(state.articleQuery.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)).map(articleCard).join('')||empty('조건에 맞는 아티클이 없어요.','카테고리, 콘텐츠 유형 또는 검색어를 변경해 보세요.',btn('검색 조건 초기화','reset-article-filters','small'));}
function frontArticleBanner(){return articleBannerMarkup(articleBannerConfig,{member:state.logged,index:state.articleLesson,playing:state.articlePlaying});}
views.articles=()=>`<div class="wrap"><h1 class="sr-only" tabindex="-1">아티클 · 무료강의와 일하는 방식에 관한 이야기</h1>${articleBannerConfig.enabled?`<div class="article-banner-region" id="article-free-class">${frontArticleBanner()}</div>`:''}<section class="section article-library" id="article-library"><div class="section-head"><div><div class="eyebrow">Insights for your work</div><h2>읽고, 보고, 내 일에 적용하세요.</h2><p>일하는 방식에 관한 글과 영상을 한곳에서 만나보세요.</p></div><div class="meta">총 ${DATA.articles.length}개 콘텐츠</div></div><div class="filter-row"><div class="chips" aria-label="아티클 카테고리">${['전체','업무 설계','마케팅 실행','AI 활용'].map(t=>`<button type="button" class="chip ${state.articleTag===t?'active':''}" data-article-tag="${t}" aria-pressed="${state.articleTag===t}">${t}</button>`).join('')}</div><div class="flex article-search-controls"><select id="article-type" aria-label="아티클 콘텐츠 유형">${['전체','글','영상'].map(t=>`<option value="${t}" ${state.articleType===t?'selected':''}>${t==='전체'?'전체 유형':t==='글'?'글 아티클':'영상 아티클'}</option>`).join('')}</select><div class="search">${icon('search')}<input id="article-search" type="search" placeholder="아티클 검색" aria-label="아티클 검색" value="${esc(state.articleQuery)}"></div></div></div><div class="grid3" id="article-results">${articleResults()}</div></section></div>`;
const textArticleView=views.article;
views.article=()=>{const a=DATA.articles.find(a=>a.id===state.articleId)||DATA.articles[0];if(a.type!=='영상')return textArticleView().replace('<span class="eyebrow">관련 무료 클래스</span><h3>AI 직원을 둔 일당백 1인 회사 만들기</h3><p>내 일을 이해하고 함께 실행하는 AI 업무 시스템.</p>',`<span class="eyebrow">회원 무료 3강</span><h3>사업자를 위한 마케팅·AI 매출 진단</h3><p>가입 후 아티클 상단에서 바로 무료강의를 볼 수 있습니다.</p>`).replace(link('무료 클래스 살펴보기 '+icon('arrow'),'free','primary mt16'),link('무료 3강 보러 가기 '+icon('arrow'),'articles','primary mt16'));return `<div class="wrap"><article class="article-detail video-article-detail">${crumbs([['아티클','articles'],[a.tag]])}<div class="flex gap8">${badge('영상 아티클','red')}${badge(a.tag)}</div><h1 tabindex="-1">${a.title}</h1><div class="meta">브랜디액션 · ${a.date} · ${a.minutes} · 시안용 콘텐츠</div><div class="article-inline-player"><span class="article-inline-label">VIDEO ARTICLE</span><button type="button" class="play-btn" data-action="article-video-play" aria-label="${esc(a.title)} 재생 화면 보기">${icon('play')}</button><strong>${a.title}</strong><p>영상 재생 영역 · UIUX 시안</p><span class="article-inline-footer">${icon('play')} <span>00:00 / ${a.minutes}</span><span class="article-progress-rail"></span><span>영상</span></span></div><div class="article-body"><h2>영상에서 살펴볼 내용</h2><p>${a.desc}</p><ul><li>지금 먼저 해결해야 하는 업무의 문제</li><li>AI와 함께할 일과 직접 검토할 일</li><li>이번 주에 시도할 작은 실행 한 가지</li></ul><h2>내 업무에 적용해 보세요.</h2><p>가장 먼저 바꿔보고 싶은 업무를 한 가지 적고, 필요한 결과와 확인할 기준을 정리해 보세요.</p></div><div class="related"><span class="eyebrow">무료로 더 깊이 살펴보기</span><h3>사업자를 위한 마케팅·AI 매출 진단</h3><p>회원가입 후 무료 3강 전체를 아티클 상단에서 볼 수 있습니다.</p>${link('무료 3강 보러 가기 '+icon('arrow'),'articles','primary mt16')}</div><div class="between mt32"><a class="link" href="#articles">${icon('back')} 아티클 목록</a>${btn(icon('link')+' 링크 복사','copy-link','small')}</div></article></div>`;};
const articleSignupOriginal=views.signup,articleLoginOriginal=views.login;
views.signup=()=>state.returnTo==='articles'?articleSignupOriginal().replace('배움을 실행으로 바꾸는 시작.','가입하고 무료 3강을 바로 보세요.').replace('클래스와 자료를 한 계정에서 관리하세요.','가입 후 이 아티클 화면으로 돌아와 무료강의를 볼 수 있습니다.').replace('<button type="submit" class="btn primary full large">회원가입</button>','<button type="submit" class="btn primary full large">가입하고 무료 3강 보기</button>'):articleSignupOriginal();
views.login=()=>state.returnTo==='articles'?articleLoginOriginal().replace('다시 만나 반가워요.','로그인하고 무료강의를 이어보세요.').replace('로그인하고 내 일의 다음 단계를 이어가세요.','로그인 후 선택한 무료강의가 있는 아티클 화면으로 돌아갑니다.'):articleLoginOriginal();
// ARTICLE FRONT EVENTS
document.addEventListener('click',e=>{const b=e.target.closest('[data-ab-action]');if(!b)return;e.preventDefault();const action=b.dataset.abAction;if(action==='lesson')state.articleLesson=Number(b.dataset.abIndex);if(!state.logged&&['signup','login','lesson','play'].includes(action)){state.returnTo='articles';state.articleReturn=true;go(action==='login'?'login':'signup');return;}if(action==='scroll'){$('#article-library')?.scrollIntoView({behavior:'smooth',block:'start'});return;}if(['lesson','play'].includes(action)){state.articlePlaying=action==='play';const target=$('#article-free-class');if(target){target.innerHTML=frontArticleBanner();target.querySelector(`[data-ab-index="${state.articleLesson}"]`)?.focus({preventScroll:true});}if(action==='play')toast('무료강의 재생 화면 시안입니다. 실제 영상은 연결하지 않았습니다.');}});
document.addEventListener('input',e=>{if(e.target.id==='article-search'){state.articleQuery=e.target.value;$('#article-results').innerHTML=articleResults();}});
document.addEventListener('change',e=>{if(e.target.id==='article-type'){state.articleType=e.target.value;$('#article-results').innerHTML=articleResults();}});
