'use strict';
const ROUTES={
home:['홈','01-home.html','둘러보기'],classes:['클래스 목록','02-classes.html','둘러보기'],free:['무료 클래스 상세','03-free-class.html','둘러보기'],paid:['유료 클래스 상세','04-paid-class.html','둘러보기'],digital:['디지털 상품 상세','05-digital-product.html','둘러보기'],login:['로그인','06-login.html','신청·결제'],apply:['무료 클래스 신청','07-free-apply.html','신청·결제'],applied:['무료 신청 완료','08-free-applied.html','신청·결제'],checkout:['주문·결제','09-checkout.html','신청·결제'],result:['결제 결과','10-order-result.html','신청·결제'],mypage:['마이페이지','11-my-dashboard.html','나의 학습'],myclasses:['내 클래스','12-my-classes.html','나의 학습'],learning:['학습실','13-learning-room.html','나의 학습'],mission:['미션 제출·피드백','14-mission.html','나의 학습'],questions:['내 질문','15-my-questions.html','나의 학습'],orders:['신청·주문 내역','16-my-orders.html','내 계정'],coupons:['내 쿠폰','17-my-coupons.html','내 계정'],resources:['내 자료실','18-my-resources.html','내 계정'],profile:['회원 정보','19-my-profile.html','내 계정'],articles:['아티클','20-articles.html','콘텐츠'],article:['아티클 상세','21-article-detail.html','콘텐츠'],stories:['고객 이야기','22-customer-stories.html','콘텐츠'],myreviews:['내 상품 후기','23-my-reviews.html','내 계정'],signup:['회원가입','24-signup.html','신청·결제']};
const DATA={products:[
{id:'p2',type:'무료 클래스',route:'free',name:'AI 직원을 둔 일당백 1인 회사 만들기',short:'AI 직원을 둔\n일당백 1인 회사',cover:'red',label:'FREE LIVE CLASS',note:'9.28 (월) 21:00 · 온라인 라이브',price:0,status:'모집 중',tag:'무료 자료 포함'},
{id:'p1',type:'유료 클래스',route:'paid',name:'사업자를 위한 AI 마케팅 실전 과정',short:'혼자 하던 마케팅,\n실행하는 시스템으로',cover:'dark',label:'AI MARKETING / COHORT 05',note:'10.06–10.27 · 4주 라이브 과정',price:1490000,status:'모집 중',tag:'5기 모집'},
{id:'p5',type:'유료 클래스',route:'paid',name:'AI 온보딩 챌린지',short:'작게 배우고,\n매일 실행하는 AI',cover:'blue',label:'AI ONBOARDING / 30 DAYS',note:'6주 · 30개 학습과 미션',price:99000,status:'수강 중',tag:'1기'},
{id:'p3',type:'디지털 상품',route:'digital',name:'AI 업무 템플릿 팩',short:'내 업무에 바로 쓰는\nAI 워크시트',cover:'sand',label:'WORK TOOLKIT / DIGITAL',note:'업무 정리 · 프롬프트 · 실행 기록',price:29000,status:'상시 판매',tag:'구매 후 다운로드'}],
articles:[{id:1,tag:'업무 설계',title:'AI를 쓰기 전에, 내 일을 먼저 정리하는 법',desc:'반복하는 일과 판단이 필요한 일을 나누는 것부터 시작해 보세요.',date:'2026.09.08',minutes:'5분'},{id:2,tag:'마케팅 실행',title:'콘텐츠 아이디어를 실행 계획으로 바꾸기',desc:'좋은 아이디어가 실제 발행으로 이어지게 하는 세 가지 질문.',date:'2026.09.06',minutes:'4분'},{id:3,tag:'AI 활용',title:'나만의 프롬프트를 기록해야 하는 이유',desc:'성공한 질문의 맥락을 남기면 다음 업무가 쉬워집니다.',date:'2026.09.03',minutes:'4분'}],
lessons:['Claude란 무엇인가','모델 선택하기','대화 컨텍스트 작동 방식','Context Window 이해하기','주요 활용 사례 탐색','요금제 & 인터페이스 파악','1주차 복습','Role Prompting 실습','Context Stacking 연습','Chain-of-Thought Prompting','제약 조건 추가하기','Prompt Chaining 설계','고급 프롬프팅 조합','2주차 복습','Artifacts 입문','Artifact 프롬프팅 고도화','라이브 편집 & 정제','To-Do 앱 / 계산기 만들기','Skills 개념 & 첫 Skill 만들기','글쓰기 & 리서치 Skills','3주차 복습','Coworker 모드 실전','Connectors & 파일 분석','자동화 기초 (MCP 개념)','Claude Code 입문','파워 유저 시스템 설계','초보자 실수 10가지 점검','나만의 Skill 라이브러리 완성','실제 프로젝트 1개 완성하기','30일 총복습 & 다음 단계'],
quiz:[{q:'업무를 요청하기 전에 가장 먼저 정리할 것은?',options:['업무의 목표와 맥락','사용할 도구의 개수','완성된 문장의 길이','모든 작업의 자동화 방법'],answer:0,explain:'해결하려는 문제와 필요한 결과를 구체적으로 정리합니다.'},{q:'생성된 결과를 검토할 때 중요한 것은?',options:['빠르게 생성되었는지','문장이 충분히 긴지','사실 여부와 우리 업무 기준에 맞는지','도구 이름이 포함되어 있는지'],answer:2,explain:'결과를 그대로 사용하기 전에 사실 여부와 업무 기준을 확인합니다.'},{q:'학습을 업무에 연결하는 첫 행동은?',options:['전체 업무를 한 번에 바꾸기','다음 강의만 계속 보기','성공할 때까지 기록하지 않기','작은 업무에 적용하고 결과 기록하기'],answer:3,explain:'작은 실행과 기록을 반복하며 적용 범위를 넓혀 갑니다.'}]
};
const state={route:'home',logged:false,returnTo:'apply',classType:'전체',classQuery:'',classSort:'추천순',checkoutId:'p1',paidId:'p1',applied:false,paid:false,purchases:[],paymentFailed:false,coupon:false,lesson:1,completed:new Set([2,3,4]),quizResult:null,lessonAnswers:{},missionState:'draft',missionText:'',missionURL:'',missionFile:'',missionTab:'write',orderType:'전체',orderQuery:'',orderFrom:'',orderTo:'',couponTab:'사용 가능',resourceFilter:'전체 자료',articleId:1,articleTag:'전체',myClassTab:'수강 중',reviewTab:'작성 가능한 후기',rating:5,reviewText:'',questionFilter:'전체',questions:[],reviews:[],profileName:'김지민',dialogOrigin:null};
const views={};
const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>Number(v).toLocaleString('ko-KR');
const product=id=>DATA.products.find(p=>p.id===id)||DATA.products[1];
const currentProduct=()=>product(state.checkoutId);
const hasPurchase=id=>state.purchases.some(o=>o.product===id);
function recordPurchase(){let o=state.purchases.find(o=>o.product===state.checkoutId);if(!o){o={id:'BA-20260910-'+String(102+state.purchases.length).padStart(4,'0'),date:'2026-09-10',product:state.checkoutId,cohort:state.checkoutId==='p1'?'5기 · 10.06–10.27':'디지털 자료 3종',price:currentProduct().price-(state.coupon&&state.checkoutId==='p1'?30000:0),status:'결제 완료'};state.purchases.push(o);}state.lastOrder=o.id;}
const ICONS={arrow:'M5 12h14m-5-5 5 5-5 5',back:'M19 12H5m5-5-5 5 5 5',chevron:'m9 5 7 7-7 7',down:'m6 9 6 6 6-6',check:'m5 12 4 4 10-10',close:'m6 6 12 12M18 6 6 18',download:'M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5',book:'M3 4h6c2 0 3 1 3 2v15c0-2-2-3-4-3H3zm18 0h-6c-2 0-3 1-3 2m0 15c0-2 2-3 4-3h5V4',file:'M14 2H5v20h14V7zm0 0v5h5M8 12h8m-8 4h6',calendar:'M4 5h16v16H4zM8 2v6m8-6v6M4 11h16',clock:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20m0-15v5l3 2',user:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8M4 21v-2a7 7 0 0 1 16 0v2',users:'M9 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8M2 21v-2a7 7 0 0 1 14 0v2M17 4a4 4 0 0 1 0 8m2 3c2 1 3 3 3 6',grid:'M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z',chat:'M3 4h18v13H8l-5 4zm5 5h8m-8 4h5',coupon:'M3 5h18v5a2 2 0 0 0 0 4v5H3v-5a2 2 0 0 0 0-4zm12 0v3m0 3v2m0 3v3',order:'M6 2h12v20l-3-2-3 2-3-2-3 2zm3 5h6m-6 4h6m-6 4h3',search:'M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16m6-2 6 6',menu:'M4 6h16M4 12h16M4 18h16',lock:'M6 10h12v11H6zm3 0V6a3 3 0 0 1 6 0v4m-3 5v2',play:'m9 5 11 7-11 7z',target:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18m0-5a4 4 0 1 0 0-8 4 4 0 0 0 0 8m0-4h.01',edit:'m4 16-1 5 5-1L21 7l-4-4zM14 6l4 4',logout:'M9 3H3v18h6m6-14 5 5-5 5M8 12h12',info:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20m0-12v6m0-10h.01',star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',upload:'M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5',link:'m10 13 4-4m-6 7-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2-1 1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0'};
const icon=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${ICONS[name]||ICONS.file}"/></svg>`;
const link=(text,r,style='',extra='')=>`<a href="#${r}" class="btn ${style}" ${extra}>${text}</a>`;
const btn=(text,action,style='',extra='')=>`<button type="button" class="btn ${style}" data-action="${action}" ${extra}>${text}</button>`;
const badge=(text,color='')=>`<span class="badge ${color}">${text}</span>`;
const empty=(title,text,cta='')=>`<div class="empty">${icon('search')}<h3>${title}</h3><p>${text}</p>${cta}</div>`;
const head=(title,desc,extra='')=>title?`<div class="page-head"><div class="between"><div><h1 tabindex="-1">${title}</h1>${desc?`<p>${desc}</p>`:''}</div>${extra}</div></div>`:`<div style="height:30px" aria-hidden="true"></div>`;
const cover=(p)=>`<div class="cover ${p.cover}"><span class="cover-label">${p.label}</span><strong>${p.short.split('\n').map(esc).join('<br>')}</strong><div class="cover-bottom"><span>BRANDYACTION EDU</span>${icon('arrow')}</div><span class="cover-line" aria-hidden="true"></span></div>`;
const courseCard=p=>`<a class="course-card" href="#${p.route}" ${p.route==='paid'?`data-product="${p.id}"`:''} data-course-type="${p.type}" data-course-name="${esc(p.name)}">${cover(p)}<div class="card-body"><div class="flex gap8">${badge(p.type,p.price===0?'red':'')}${badge(p.tag)}</div><h3>${p.name}</h3><p>${p.note}</p><div class="card-price">${p.price===0?'무료':n(p.price)+'원'}<span>${p.price===0?'바로 신청 가능':''}</span>${icon('arrow','arrow')}</div></div></a>`;
function resourceRow(id,title,meta='워크시트 · HTML · 예시 자료',locked=false){return `<div class="resource-row"><span class="file-icon">${icon('file')}</span><div class="resource-text"><b>${title}</b><small>${meta}</small></div>${locked?btn(icon('lock')+' 구매 후 이용','buy-digital','small'):btn(icon('download')+' 다운로드','download','small',`data-resource="${id}"`)}</div>`;}
const crumbs=(items)=>`<div class="breadcrumbs">${items.map((x,i)=>`${i?icon('chevron'):''}${x[1]?`<a href="#${x[1]}">${x[0]}</a>`:`<span>${x[0]}</span>`}`).join('')}</div>`;
const summaryProduct=(p,sub='')=>`<div class="summary-product"><div class="summary-thumb" style="${p.id==='p3'?'background:#e9e3d9;color:#383631':p.id==='p5'?'background:#294958':''}">${p.id==='p2'?'FREE<br>LIVE':p.id==='p3'?'AI<br>TOOLKIT':p.id==='p5'?'AI<br>30 DAYS':'AI<br>CLASS'}</div><div><h3>${p.name}</h3><p>${sub||p.note}</p></div></div>`;
const accountRoutes=['mypage','myclasses','questions','resources','myreviews','orders','coupons','profile'];
const accountIcons=['grid','book','chat','download','star','order','coupon','user'];
const accountLabels=['마이페이지','내 클래스','내 질문','내 자료실','내 상품 후기','신청·주문 내역','내 쿠폰','회원 정보'];
function account(body){return `<div class="account-bg"><div class="wrap account-layout"><aside class="account-aside"><div class="account-profile"><span class="avatar">김</span><div><b>${esc(state.profileName)}</b><p>실행을 쌓아가는 중</p></div></div><nav class="account-nav" aria-label="마이페이지">${accountRoutes.map((r,i)=>`<a href="#${r}" class="${state.route===r?'active':''}" ${state.route===r?'aria-current="page"':''}>${icon(accountIcons[i])}${accountLabels[i]}</a>`).join('')}</nav></aside><div class="account-main">${body}</div></div></div>`;}
function marketingHeader(){const signed=state.logged||accountRoutes.includes(state.route)||['learning','mission','applied','result','checkout','apply'].includes(state.route);const navs=[['free','무료 클래스'],['classes','전체 클래스'],['stories','고객 이야기'],['articles','아티클']];return `<a class="skip" href="#main">본문으로 이동</a><div class="reviewbar"><div><span class="dot"></span>UIUX 시안 <span class="review-note">· 예시 콘텐츠 / 서비스 연결 없음</span></div><label class="sr-only" for="page-select">시안 페이지 선택</label><select id="page-select">${['둘러보기','신청·결제','나의 학습','내 계정','콘텐츠'].map(g=>`<optgroup label="${g}">${Object.entries(ROUTES).filter(([k,v])=>v[2]===g).map(([k,v])=>`<option value="${k}" ${state.route===k?'selected':''}>${v[1].slice(0,2)} · ${v[0]}</option>`).join('')}</optgroup>`).join('')}</select><span>FRONTEND DESIGN / ${Object.keys(ROUTES).length} SCREENS</span></div><header class="site-header"><div class="wrap header-inner"><a href="#home" class="brand" aria-label="brandyaction EDU 홈"><span class="brand-mark">b</span>brandyaction <small>EDU</small></a><nav class="main-nav" aria-label="주 메뉴">${navs.map(([r,t])=>`<a class="${state.route===r||r==='classes'&&['paid','digital'].includes(state.route)||r==='articles'&&state.route==='article'?'active':''}" href="#${r}">${t}</a>`).join('')}</nav><div class="header-user">${signed?`<a href="#mypage" class="link">마이페이지</a><a href="#mypage" class="avatar" aria-label="마이페이지">김</a>`:link('로그인','login','','data-return="mypage"')}<button class="icon-btn mobile-only" type="button" data-action="menu" aria-label="메뉴 열기" aria-expanded="false" aria-controls="mobile-menu">${icon('menu')}</button></div></div><nav class="mobile-nav" id="mobile-menu" aria-label="모바일 메뉴">${navs.map(([r,t])=>`<a href="#${r}">${t}</a>`).join('')}<a href="#mypage">마이페이지</a></nav></header>`;}
function marketingFooter(){return `<footer class="footer"><div class="wrap"><div class="between"><a class="brand" href="#home"><span class="brand-mark">b</span>brandyaction <small>EDU</small></a><div class="footer-links">${btn('이용약관','terms','ghost small')}${btn('개인정보 처리방침','privacy','ghost small')}${btn('고객 문의','contact','ghost small')}</div></div><p>배움을 실행으로, 실행을 내 일의 변화로 연결합니다.<br>시안용 예시 콘텐츠입니다. 교육 일정·가격·자료·후기 및 사업자 정보는 최종 운영 정보로 교체됩니다.</p><div class="footer-bottom">© BRANDYACTION EDU. ALL RIGHTS RESERVED.</div></div></footer>`;}
function ctaFree(){return `<aside class="bottom-cta" aria-label="무료 클래스 신청"><div class="wrap"><div><div class="cta-price">무료</div><div class="meta">자료 포함<span class="cta-caption"> · 온라인 클래스</span></div></div>${state.applied?link('신청 내역 확인하기 '+icon('arrow'),'applied','primary large'):btn('수강 신청하기 '+icon('arrow'),'enroll-free','primary large')}</div></aside>`;}
function ctaProduct(p){return `<aside class="bottom-cta product-mobile-cta" aria-label="상품 신청"><div class="wrap"><div><div class="cta-price">${n(p.price)}원</div><div class="meta">${p.type}</div></div>${hasPurchase(p.id)?link(p.id==='p3'?'내 자료실':'내 클래스',p.id==='p3'?'resources':'myclasses','primary large'):btn(p.id==='p3'?'구매하기':'수강 신청하기','buy','primary large',`data-id="${p.id}"`)}</div></aside>`;}

function inLearningArea(){return [...accountRoutes,'learning','mission'].includes(state.route);}
function header(){
  const original=marketingHeader();if(!inLearningArea())return original;
  const review=original.slice(0,original.indexOf('<header class="site-header">'));
  return review+`<header class="site-header"><div class="wrap learning-chrome"><a href="#mypage" class="brand" aria-label="Brandy Edu 나의 학습"><span class="brand-mark">b</span>brandyaction <small>EDU</small></a><div class="learning-context">${['learning','mission'].includes(state.route)?'<b>AI 온보딩 챌린지</b><span>1기 · 나의 학습</span>':'<b>나의 학습</b><span>배움을 실행으로 이어가는 공간</span>'}</div><div class="learning-chrome-actions">${link('내 클래스','myclasses','ghost small')}${link('마이페이지','mypage','small')}</div></div></header>`;
}
function footer(){return inLearningArea()?`<footer class="learning-footer"><div class="wrap"><span>BRANDYACTION EDU · 나의 배움과 실행</span><div>${btn('이용 문의','contact','ghost small')}${link('홈으로','home','ghost small')}</div></div></footer>`:marketingFooter();}
