// Member workspace: local example records, shared with the existing learning and submission views.
ROUTES.mymissions=['내 미션','25-my-missions.html','나의 학습'];
accountRoutes.splice(2,0,'mymissions');accountIcons.splice(2,0,'target');accountLabels.splice(2,0,'내 미션');
Object.assign(state,{memberClass:'p5',myMissionFilter:'전체'});
const PERSONAL_MISSIONS=[
 {day:1,title:'내 업무의 AI 활용 지점 찾기',status:'draft',deadline:'9.14 (월)',text:''},
 {day:2,title:'AI에 맡길 업무와 직접 할 업무 나누기',status:'submitted',deadline:'9.14 (월)',text:'반복하는 고객 질문을 정리하고, AI로 초안을 만든 뒤 사실과 브랜드 표현을 직접 검토하겠습니다.'},
 {day:3,title:'고객 질문으로 업무 요청문 작성하기',status:'returned',deadline:'9.14 (월)',text:'고객 안내 콘텐츠의 초안을 작성하는 요청문을 만들었습니다. 대상 고객과 출력 형식을 추가하겠습니다.'},
 {day:4,title:'우리 브랜드의 결과물 검토 기준 정하기',status:'approved',deadline:'9.14 (월)',text:'사실 여부, 고객의 이해도, 브랜드 표현을 기준으로 결과물을 검토하고 수정했습니다.'},
 {day:5,title:'이번 주 작은 업무 하나에 적용하기',status:'draft',deadline:'9.14 (월)',text:''}
];
const PERSONAL_STATUS={draft:['제출 전',''],submitted:['검토 대기','amber'],returned:['보완 요청','red'],approved:['승인 완료','green']};
function personalMission(day){const seed=PERSONAL_MISSIONS.find(m=>m.day===day)||{day,title:'배운 내용을 업무에 적용하기',status:'draft',text:'',deadline:'공개 후 안내'};const saved=typeof missionDrafts!=='undefined'?missionDrafts.get(day):null;return {...seed,...saved,...(state.lesson===day?{status:state.missionState,text:state.missionText}:{}),day};}
function personalCounts(){const rows=PERSONAL_MISSIONS.map(m=>personalMission(m.day));return {rows,approved:rows.filter(m=>m.status==='approved').length,pending:rows.filter(m=>m.status==='submitted').length,returned:rows.filter(m=>m.status==='returned').length,draft:rows.filter(m=>m.status==='draft').length};}
function memberProgress(value,max,label){return `<div class="progress" role="progressbar" aria-label="${label}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${value}"><span style="width:${Math.min(100,value/max*100)}%"></span></div>`;}
function memberMetric(label,value,suffix,detail,route,ic){return `<a class="member-stat" href="#${route}"><div>${icon(ic)}<span>${label}</span>${icon('chevron')}</div><strong>${value}<small>${suffix}</small></strong><p>${detail}</p></a>`;}
account=function(body){const groups=[['나의 학습',['mypage','myclasses','mymissions','questions','resources']],['내 계정',['orders','coupons','myreviews','profile']]];return `<div class="account-bg"><div class="wrap account-layout"><aside class="account-aside"><div class="account-profile"><span class="avatar">${esc(state.profileName[0])}</span><div><b>${esc(state.profileName)}님</b><p>나의 배움과 실행</p></div></div><nav class="account-nav" aria-label="마이페이지">${groups.map(([title,routes])=>`<div class="member-nav-group"><span class="member-nav-label">${title}</span>${routes.map(r=>{const i=accountRoutes.indexOf(r);return `<a href="#${r}" class="${state.route===r?'active':''}" ${state.route===r?'aria-current="page"':''}>${icon(accountIcons[i])}${accountLabels[i]}</a>`;}).join('')}</div>`).join('')}</nav><div class="member-help">${btn(icon('chat')+' 이용 문의','contact','ghost small')}${btn(icon('logout')+' 로그아웃','logout','ghost small')}</div></aside><div class="account-main">${body}</div></div></div>`;};
views.mypage=()=>{const c=personalCounts(),next=state.completed.has(state.lesson)?DATA.lessons.findIndex((_,i)=>!state.completed.has(i+1))+1:state.lesson;const day=next||1,level=c.approved>=5?3:c.approved>=1?2:1,target=level===1?1:level===2?5:10;return account(`${head('마이페이지',`${esc(state.profileName)}님, 오늘의 학습과 실행을 이어가세요.`,link(icon('user')+' 회원 정보','profile','small'))}
<div class="member-focus-grid"><section class="member-continue"><div class="member-kicker">이어서 학습하기 <span>1기</span></div><p class="member-class-name">AI 온보딩 챌린지</p><h2>${esc(DATA.lessons[day-1])}</h2><p class="member-lesson-meta">DAY ${String(day).padStart(2,'0')} <span>·</span> 약 5분 <span>·</span> 확인 퀴즈 3문항</p><div class="member-progress-caption"><span>전체 학습 진도</span><b>${Math.round(state.completed.size/30*100)}%</b></div>${memberProgress(state.completed.size,30,'AI 온보딩 학습 진도')}<div class="member-continue-foot"><span>${state.completed.size}개 완료 / 전체 30개</span>${btn('학습 이어가기 '+icon('arrow'),'member-resume','primary',`data-day="${day}"`)}</div></section>
<section class="member-level panel"><div class="between"><h2>나의 실행 레벨</h2>${btn(icon('info'),'member-level','ghost small','aria-label="레벨 기준 보기"')}</div><div class="member-level-value"><span>Lv.${level}</span><strong>${level===1?'시작':level===2?'실행':'성장'}</strong></div><p>AI 온보딩 챌린지 · 1기</p><div class="member-progress-caption"><span>미션 승인</span><b>${c.approved} / ${target}</b></div>${memberProgress(c.approved,target,'다음 레벨까지 미션 승인')}<p class="member-level-next">다음 레벨까지 <b>${Math.max(0,target-c.approved)}개 승인</b>이 필요해요.</p><a class="link" href="#mymissions">내 미션 확인 ${icon('arrow')}</a></section></div>
<div class="member-stats">${memberMetric('수강 중',2,'개','클래스별 학습 이어가기','myclasses','book')}${memberMetric('학습 완료',state.completed.size,'/ 30','AI 온보딩 챌린지 · 1기','learning','check')}${memberMetric('검토 대기',c.pending,'건',`보완이 필요한 미션 ${c.returned}건`,'mymissions','target')}${memberMetric('사용 가능한 쿠폰',1,'장','10.04까지 사용 가능','coupons','coupon')}</div>
<div class="member-lower-grid"><section class="panel member-tasks"><div class="panel-head"><h2>지금 확인할 일</h2><a class="link" href="#mymissions">내 미션 ${icon('chevron')}</a></div>${c.rows.filter(m=>m.status==='returned').slice(0,1).map(m=>memberTask(m,'강사 피드백을 확인하고 내용을 보완해 주세요.')).join('')}${c.rows.filter(m=>m.status==='draft').slice(0,1).map(m=>memberTask(m,m.deadline+' 23:59까지 · 텍스트 / URL / 파일')).join('')}<a class="member-task" href="#questions"><span class="member-task-icon">${icon('chat')}</span><div>${badge('답변 완료','green')}<h3>작성한 업무 목록은 얼마나 나누면 되나요?</h3><p>내 질문에 등록된 강사 답변을 확인해 주세요.</p></div>${icon('chevron')}</a></section>
<section class="panel member-agenda"><div class="panel-head"><h2>다가오는 일정</h2>${icon('calendar')}</div><div class="member-event"><div class="member-date"><span>9월</span><b>15</b></div><div>${badge('온라인 라이브')}<h3>AI 마케팅 실전 · 4기 3회차</h3><p>화요일 20:00–21:30</p><p class="member-event-note">입장 링크는 시작 30분 전에 열립니다.</p>${btn('클래스 안내 보기','open-marketing-room','small')}</div></div>${state.applied?`<div class="member-event"><div class="member-date"><span>9월</span><b>28</b></div><div>${badge('신청 완료','green')}<h3>일당백 1인 회사 만들기</h3><p>월요일 21:00 · 무료 라이브</p>${link('참여 안내','applied','small mt16')}</div></div>`:''}<a class="member-agenda-link" href="#orders">신청·주문 내역 확인 ${icon('arrow')}</a></section></div>
<section class="member-classes"><div class="section-head"><div><h2>내 클래스</h2><p>배우던 클래스와 자료를 바로 열어보세요.</p></div><a class="link" href="#myclasses">전체 보기 ${icon('arrow')}</a></div>${enrolledCard('p5')}${enrolledCard('p1')}</section>
<div class="member-shortcuts"><a href="#resources">${icon('download')}<div><b>내 자료실</b><span>수강 자료와 구매한 파일</span></div>${icon('arrow')}</a><a href="#articles" data-member-free="true">${icon('play')}<div><b>회원 무료강의 3강</b><span>가입 혜택으로 바로 시청</span></div>${icon('arrow')}</a><a href="#myreviews">${icon('star')}<div><b>내 상품 후기</b><span>수강 경험 남기기</span></div>${icon('arrow')}</a></div>`);};
function memberTask(m,desc){const [label,color]=PERSONAL_STATUS[m.status];return `<button class="member-task" type="button" data-action="member-mission" data-day="${m.day}"><span class="member-task-icon ${m.status==='returned'?'red':''}">${icon(m.status==='returned'?'edit':'target')}</span><div>${badge(label,color)}<h3>${m.title}</h3><p>${desc}</p></div>${icon('chevron')}</button>`;}
function memberMissionRows(){const c=personalCounts();if(state.memberClass!=='p5')return empty('현재 공개된 미션이 없어요.','선택한 기수의 미션이 공개되면 이곳에서 확인할 수 있습니다.',btn('클래스 안내 보기','open-marketing-room'));const rows=c.rows.filter(m=>state.myMissionFilter==='전체'||PERSONAL_STATUS[m.status][0]===state.myMissionFilter);return rows.length?`<div class="member-mission-list">${rows.map(m=>{const [label,color]=PERSONAL_STATUS[m.status];return `<article class="member-mission-row"><span class="member-mission-day">DAY<strong>${String(m.day).padStart(2,'0')}</strong></span><div class="row-text"><div class="flex gap8">${badge('WEEK 1')}${badge(label,color)}</div><h3>${m.title}</h3><p>${m.deadline} 23:59까지${m.status==='returned'?' · 강사의 보완 요청이 있어요.':m.status==='submitted'?' · 제출물을 검토하고 있어요.':''}</p></div>${btn(m.status==='draft'?'미션 작성':m.status==='returned'?'피드백 확인':m.status==='submitted'?'제출 내용':'승인 내용','member-mission',m.status==='returned'?'primary small':'small',`data-day="${m.day}"`)}</article>`;}).join('')}</div>`:empty('이 상태의 미션이 없어요.','다른 상태를 선택하면 전체 진행 상황을 확인할 수 있습니다.');}
views.mymissions=()=>{const c=personalCounts();return account(`${head('내 미션','제출부터 피드백, 승인까지 클래스별로 확인하세요.')}<div class="member-mission-filter"><label for="member-class">클래스 · 기수<select id="member-class"><option value="p5" ${state.memberClass==='p5'?'selected':''}>AI 온보딩 챌린지 · 1기</option><option value="p1" ${state.memberClass==='p1'?'selected':''}>AI 마케팅 실전 과정 · 4기</option></select></label><div class="member-mission-summary"><span>전체 <b>${state.memberClass==='p5'?5:0}</b></span><span>승인 완료 <b>${state.memberClass==='p5'?c.approved:0}</b></span></div></div><div class="chips member-mission-tabs" aria-label="미션 상태">${['전체','제출 전','검토 대기','보완 요청','승인 완료'].map(label=>`<button type="button" class="chip ${state.myMissionFilter===label?'active':''}" data-personal-status="${label}" aria-pressed="${state.myMissionFilter===label}">${label} <span>${state.memberClass!=='p5'?0:label==='전체'?5:c.rows.filter(m=>PERSONAL_STATUS[m.status][0]===label).length}</span></button>`).join('')}</div><div id="member-mission-results">${memberMissionRows()}</div><div class="notice mt24">미션은 강사 승인 후 완료로 반영됩니다. 보완 요청이 있으면 피드백을 확인하고 다시 제출해 주세요.</div>`);};
const originalPersonalMission=views.mission;
views.mission=()=>{const m=personalMission(state.lesson);return originalPersonalMission().replace('내 업무의 AI 활용 지점 찾기',m.title).replace(crumbs([['내 클래스','myclasses'],['학습실','learning'],['미션 제출']]),crumbs([['마이페이지','mypage'],['내 미션','mymissions'],['DAY '+state.lesson+' · 미션 상세']])).replace('미션을 실행으로 남겨보세요.','미션 제출 · 피드백');};
// MYPAGE EVENTS
document.addEventListener('click',e=>{const b=e.target.closest('[data-personal-status]');if(b){state.myMissionFilter=b.dataset.personalStatus;render(false);document.querySelector(`[data-personal-status="${state.myMissionFilter}"]`)?.focus();}if(e.target.closest('[data-member-free]'))state.logged=true;});
document.addEventListener('change',e=>{if(e.target.id==='member-class'){state.memberClass=e.target.value;state.myMissionFilter='전체';render(false);document.getElementById('member-class')?.focus();}});
