// UI prototype only: all changes remain in this tab's memory. No service requests, analytics, or persistence.
let toastTimer;const missionDrafts=new Map(PERSONAL_MISSIONS.filter(m=>m.day!==1).map(m=>[m.day,{text:m.text,url:'',file:'',status:m.status}]));
function toast(message){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true;},4200);}
function render(focus=true){const r=ROUTES[state.route]?state.route:'home';state.route=r;if([...accountRoutes,'learning','mission','applied','result','checkout','apply'].includes(r))state.logged=true;document.title=`${ROUTES[r][0]} · Brandyaction EDU UIUX`;document.body.className=r==='free'?'has-cta':r==='digital'||r==='paid'&&state.paidId!=='p5'?'product-page':'';$('#app').innerHTML=header()+`<main id="main" tabindex="-1">${views[r]()}</main>`+footer();if(focus){window.scrollTo({top:0,behavior:'instant'});const h=$('#main h1');h?.focus({preventScroll:true});}}
function go(r){if(!ROUTES[r])return;if(location.hash==='#'+r){state.route=r;render();}else location.hash=r;}
function openDialog(title,body,actions=''){const d=$('#modal');state.dialogOrigin=document.activeElement;d.innerHTML=`<div class="modal-head"><h2 id="modal-title">${title}</h2><button type="button" class="icon-btn" data-action="close-dialog" aria-label="닫기">${icon('close')}</button></div><div class="modal-body">${body}</div><div class="modal-footer">${actions||btn('확인','close-dialog','dark')}</div>`;d.showModal();}
function closeDialog(){const d=$('#modal');if(d.open)d.close();state.dialogOrigin?.isConnected&&state.dialogOrigin.focus();}
function goAuth(target){state.returnTo=target;go(state.logged?target:'login');}
function loginDemo(){state.logged=true;closeDialog();go(state.returnTo||'mypage');toast('예시 계정으로 화면을 이어갑니다. 실제 인증은 연결하지 않았습니다.');}
function saveMissionDraft(){state.missionText=$('#mission-content')?.value??state.missionText;state.missionURL=$('#mission-url')?.value??state.missionURL;missionDrafts.set(state.lesson,{text:state.missionText,url:state.missionURL,file:state.missionFile,status:state.missionState});}
function selectLesson(day){if(day>15){toast('공개 예정인 학습입니다. 공개 후 학습할 수 있습니다.');return;}if(day<1)return;if(state.route==='mission')saveMissionDraft();state.lesson=day;state.quizResult=null;const d=missionDrafts.get(day);state.missionText=d?.text||'';state.missionURL=d?.url||'';state.missionFile=d?.file||'';state.missionState=d?.status||'draft';if(state.route==='learning')render();else go('learning');}
function downloadFile(filename,content,type='text/html;charset=utf-8'){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);}
function readReview(id,edit=false){state.editReviewId=id;const old=edit?state.reviews.find(x=>x.product===id):null;state.rating=old?.rating||5;openDialog(edit?'상품 후기 수정':'상품 후기 작성',`<form id="review-form"><p>${product(id).name} · ${id==='p1'?'4기':'1기'}</p><label class="field">이 클래스는 어떠셨나요?</label><div class="review-rating" id="rating-buttons">${ratingButtons()}</div><input type="hidden" name="product" value="${id}"><label class="field">수강 경험<textarea name="text" rows="5" required maxlength="1500" placeholder="해결하고 싶었던 문제와 적용해 본 경험을 적어주세요.">${esc(old?.text||'')}</textarea></label><p class="meta mt8">작성한 후기는 해당 상품의 후기에 연결되는 구조입니다.</p></form>`,btn('취소','close-dialog')+`<button type="submit" form="review-form" class="btn primary">${edit?'수정 내용 저장':'후기 등록'}</button>`);}
function ratingButtons(){return Array.from({length:5},(_,i)=>`<button type="button" class="rating-btn" data-rating="${i+1}" aria-label="${i+1}점" aria-pressed="${state.rating===i+1}">${i<state.rating?'★':'☆'}</button>`).join('');}
function askLesson(){openDialog('학습 질문하기',`<form id="question-form"><label class="field">클래스<input readonly value="AI 온보딩 챌린지 · 1기"></label><label class="field">연결 학습<select name="lesson">${DATA.lessons.slice(0,15).map((t,i)=>`<option value="${i+1}" ${state.lesson===i+1?'selected':''}>Day ${i+1} · ${t}</option>`).join('')}</select></label><label class="field">질문 제목<input name="title" placeholder="궁금한 내용을 한 문장으로 적어주세요" required maxlength="100"></label><label class="field">질문 내용<textarea name="body" rows="5" placeholder="어떤 부분에서 막혔는지 구체적으로 알려주세요" required maxlength="3000"></textarea></label></form>`,btn('취소','close-dialog')+`<button type="submit" form="question-form" class="btn primary">질문 등록</button>`);}
function findOrder(id){return orderData().find(x=>x.id===id);}
const actions={
'article-video-play':()=>toast('영상 아티클의 재생 화면 시안입니다. 실제 영상은 연결하지 않았습니다.'),
'reset-article-filters':()=>{state.articleTag='전체';state.articleType='전체';state.articleQuery='';render(false);},
'menu':b=>{const open=$('#mobile-menu').classList.toggle('open');b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'메뉴 닫기':'메뉴 열기');},
'close-dialog':closeDialog,
'enroll-free':()=>state.applied?go('applied'):goAuth('apply'),
'buy':b=>{state.checkoutId=b.dataset.id||'p1';state.coupon=false;state.paymentFailed=false;goAuth('checkout');},
'buy-digital':()=>{state.checkoutId='p3';state.coupon=false;goAuth('checkout');},
'social-login':b=>openDialog(`${b.dataset.provider} 로그인 연결 화면`,`<p>실제 계정 인증 없이 예시 회원으로 신청 흐름을 확인합니다. 최종 개발 시 ${esc(b.dataset.provider)} 인증을 마친 뒤 원래 신청 화면으로 돌아옵니다.</p>`,btn('취소','close-dialog')+btn('예시 회원으로 계속하기','login-demo','primary')),
'login-demo':loginDemo,
'reset-password':()=>openDialog('비밀번호 재설정',`<form id="password-form"><p>가입한 이메일로 재설정 안내를 받는 화면입니다.</p><label class="field">이메일<input name="email" type="email" autocomplete="email" required placeholder="name@example.com"></label></form>`,btn('취소','close-dialog')+`<button type="submit" form="password-form" class="btn primary">재설정 안내 받기</button>`),
'terms':()=>openDialog('이용약관',`<p>회원 가입, 클래스 이용, 서비스 제공 범위를 안내할 약관 전문 영역입니다.</p><div class="notice mt16">현재는 UI 시안입니다. 승인된 실제 이용약관을 이 영역에 연결합니다.</div>`),
'privacy':()=>openDialog('개인정보 수집·이용 안내',`<p>클래스 신청과 참여 안내에 필요한 항목, 이용 목적, 보유 기간, 동의 거부에 관한 내용을 안내하는 영역입니다.</p><div class="notice mt16">현재는 UI 시안입니다. 필수 서비스 이용 동의와 선택적 소식 수신 동의를 구분하며, 실제 정책 전문은 운영 정책 확정 후 연결합니다.</div>`),
'refund-policy':()=>openDialog('이용·환불 안내',`<p>해당 상품의 이용 기간, 콘텐츠 제공 방식, 취소·환불 조건을 결제 전에 확인하는 영역입니다.</p><div class="notice mt16">실제 환불 기준은 확정되지 않았습니다. 이 시안은 임의의 환불률이나 법적 기준을 제시하지 않으며, 상품별 승인된 안내를 연결할 위치를 보여줍니다.</div>`),
'contact':()=>openDialog('고객 문의',`<p>계정, 신청, 결제에 관한 문의를 운영팀에 전달하는 화면입니다.</p><label class="field">문의 구분<select><option>클래스 신청</option><option>결제·환불</option><option>계정 이용</option></select></label><label class="field">문의 내용<textarea rows="4" placeholder="문의 내용을 적어주세요."></textarea></label>`,btn('닫기','close-dialog')+btn('접수 화면 확인','contact-demo','primary')),
'contact-demo':()=>{closeDialog();toast('문의 접수 상태를 확인했습니다. 실제 문의는 전송되지 않았습니다.');},
'reset-class':()=>{state.classType='전체';state.classQuery='';state.classSort='추천순';render(false);},
'download':b=>{const id=b.dataset.resource||'work-map';const file=WORKSHEETS[id]||WORKSHEETS['work-map'];downloadFile(file.filename,file.html);toast('시안용 워크시트 파일을 다운로드합니다.');},
'calendar':()=>{downloadFile('brandyaction-free-class.ics','BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Brandyaction//UIUX Sample//KO\r\nBEGIN:VEVENT\r\nUID:brandyaction-free-live-sample-20260928\r\nDTSTAMP:20260910T000000Z\r\nDTSTART:20260928T120000Z\r\nDTEND:20260928T133000Z\r\nSUMMARY:Brandyaction 무료 클래스 (시안 일정)\r\nDESCRIPTION:AI 직원을 둔 일당백 1인 회사 만들기. UIUX 시안용 예시 일정입니다. 실제 참여 안내를 확인해 주세요.\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n','text/calendar;charset=utf-8');toast('예시 일정 파일을 다운로드합니다.');},
'payment-success':()=>{recordPurchase();state.paid=true;state.logged=true;state.paymentFailed=false;state.myClassTab='수강 예정';closeDialog();go('result');toast('결제 완료 화면 시안입니다. 실제 결제는 진행되지 않았습니다.');},
'payment-failure':()=>{state.paymentFailed=true;closeDialog();go('result');},
'toggle-payment-result':()=>{state.paymentFailed=!state.paymentFailed;render(false);},
'learning-menu':b=>{const open=$('#learning-nav').classList.toggle('open');b.setAttribute('aria-expanded',String(open));},
'prev-lesson':()=>selectLesson(state.lesson-1),
'check-quiz':()=>{const answered=DATA.quiz.every((q,i)=>state.lessonAnswers[`${state.lesson}:${i}`]!==undefined);if(!answered){toast('모든 문제의 답을 선택해 주세요.');return;}const correct=DATA.quiz.filter((q,i)=>state.lessonAnswers[`${state.lesson}:${i}`]===q.answer).length;state.quizResult={correct};const top=window.scrollY;render(false);window.scrollTo(0,top);$('#quiz-summary')?.scrollIntoView({block:'nearest',behavior:'smooth'});toast(`${correct}/3문항 정답입니다.`);},
'complete-lesson':()=>{if(!state.completed.has(state.lesson)&&state.quizResult?.correct!==3){toast('확인 퀴즈를 모두 맞힌 뒤 학습을 완료할 수 있어요.');$('#lesson-quiz')?.scrollIntoView({block:'start',behavior:'smooth'});return;}state.completed.add(state.lesson);if(state.lesson>=15){render(false);toast('공개된 학습을 마쳤어요. 다음 학습은 공개 후 이어갈 수 있습니다.');}else{selectLesson(state.lesson+1);toast('학습을 완료하고 다음 내용으로 이동했습니다.');}},
'ask-lesson':askLesson,
'mission-draft':()=>{saveMissionDraft();toast('이 탭 안에 임시저장했습니다. 새로고침하면 초기화됩니다.');},
'mission-submit':()=>{state.missionState='submitted';saveMissionDraft();closeDialog();render();toast('시안에서 제출 완료 상태로 변경했습니다. 실제 제출은 전송되지 않았습니다.');},
'mission-states':()=>openDialog('미션 상태 미리보기',`<p>같은 미션의 작성 전, 제출 후, 보완 요청, 승인 완료 화면을 비교합니다.</p><div class="stack mt16">${[['draft','작성 중'],['submitted','검토 대기'],['returned','보완 요청'],['approved','승인 완료']].map(([v,t])=>btn(t,'set-mission-state',v===state.missionState?'dark':'',`data-value="${v}"`)).join('')}</div>`),
'set-mission-state':b=>{saveMissionDraft();state.missionState=b.dataset.value;if(state.missionState!=='draft'&&!state.missionText)state.missionText='매주 작성하는 고객 안내 콘텐츠의 초안을 만드는 일입니다. 고객 질문을 정리하고 자료를 준비해 초안 작성을 요청하겠습니다. 사실 여부와 브랜드 표현은 직접 검토하겠습니다.';saveMissionDraft();closeDialog();render(false);},
'open-marketing-room':()=>openDialog('AI 마케팅 실전 과정 · 4기',`<div class="video-mock"><button type="button" class="play-btn" data-action="video-demo" aria-label="강의 영상 미리보기">${icon('play')}</button><b>1주차 · 고객과 전환 병목</b><small>라이브 다시보기 · 120분</small></div><div class="notice">다음 라이브 · 9.15 (화) 20:00<br>시작 30분 전 입장 버튼이 공개됩니다.</div><h3 class="mt24" style="font-size:var(--type-large)">1주차 학습 자료</h3>${resourceRow('journey','고객 여정 진단 워크시트')}<p class="meta mt16">공개된 회차와 자료를 한곳에서 확인하는 화면 예시입니다.</p>`,btn('닫기','close-dialog')),
'video-demo':()=>toast('영상 영역의 디자인 시안입니다. 실제 재생 소스는 연결하지 않았습니다.'),
'filter-orders':()=>{const from=$('#order-from').value,to=$('#order-to').value;if(from&&to&&from>to){$('#order-date-error').textContent='시작일은 종료일보다 늦을 수 없습니다.';return;}state.orderFrom=from;state.orderTo=to;state.orderType=$('#order-product').value;$('#order-date-error').textContent='';$('#order-results').innerHTML=orderResults();},
'reset-orders':()=>{state.orderFrom='';state.orderTo='';state.orderType='전체';render(false);},
'order-detail':b=>{const o=findOrder(b.dataset.order);if(!o)return;openDialog('주문 상세',`${summaryProduct(product(o.product),o.cohort)}<dl class="info-lines"><div><dt>주문 번호</dt><dd>${o.id}</dd></div><div><dt>주문일</dt><dd>${o.date}</dd></div><div><dt>신청자</dt><dd>${esc(state.profileName)}</dd></div><div><dt>결제 수단</dt><dd>신용카드</dd></div><div><dt>결제 금액</dt><dd>${n(o.price)}원</dd></div><div><dt>상태</dt><dd>${o.status}</dd></div></dl>`);},
'receipt':b=>{const o=findOrder(b.dataset.order);if(!o)return;openDialog('결제 영수증',`<dl class="info-lines"><div><dt>주문 번호</dt><dd>${o.id}</dd></div><div><dt>결제 금액</dt><dd>${n(o.price)}원</dd></div><div><dt>결제 상태</dt><dd>${o.status}</dd></div></dl><div class="notice">영수증 연결 위치를 보여주는 시안입니다. 실제 결제 증빙은 결제 서비스 연동 후 제공됩니다.</div>`);},
'refund':b=>{const o=findOrder(b.dataset.order);if(!o)return;state.refundOrder=o.id;openDialog('취소·환불 요청',`<form id="refund-form">${summaryProduct(product(o.product),o.cohort)}<label class="field">요청 사유<select name="reason" required><option value="">선택해 주세요</option><option>일정 변경</option><option>중복 신청</option><option>이용 계획 변경</option><option>기타</option></select></label><label class="field">추가 설명<textarea rows="3" name="details" placeholder="운영자가 확인할 내용을 적어주세요."></textarea></label><div class="notice mt16">환불 가능 여부와 금액은 상품별 이용 내역과 정책을 확인한 뒤 안내됩니다.</div></form>`,btn('취소','close-dialog')+`<button type="submit" form="refund-form" class="btn primary">환불 요청</button>`);},
'coupon-products':()=>{state.classType='유료 클래스';state.classQuery='마케팅';go('classes');},
'copy-link':async()=>{try{await navigator.clipboard.writeText(location.href);toast('로컬 시안 주소를 복사했습니다.');}catch{openDialog('아티클 주소',`<p>파일로 열린 시안의 주소입니다. 다른 환경에서는 전체 HTML 파일을 함께 전달해 주세요.</p><label class="field">시안 주소<input readonly value="${esc(location.href)}"></label>`);}},
'logout':()=>{state.logged=false;go('home');toast('시안의 로그인 표시를 초기화했습니다.');},
'withdraw':()=>openDialog('회원 탈퇴',`<p>탈퇴 전 수강 중인 클래스, 보유 자료, 진행 중인 결제·환불 내역을 확인하는 화면입니다.</p><div class="notice mt16">현재는 UI 시안입니다. 실제 탈퇴와 데이터 삭제는 진행되지 않습니다.</div>`,btn('돌아가기','close-dialog')+btn('탈퇴 완료 화면 확인','withdraw-demo','danger')),
'withdraw-demo':()=>{state.logged=false;closeDialog();go('home');toast('탈퇴 완료 상태의 시안을 확인했습니다. 실제 데이터는 삭제되지 않았습니다.');},
'write-review':b=>readReview(b.dataset.id),
'edit-review':b=>readReview(b.dataset.id,true),
'delete-review':b=>openDialog('상품 후기 삭제',`<p>이 후기를 삭제하시겠어요?</p>`,btn('취소','close-dialog')+btn('삭제','confirm-delete-review','danger',`data-id="${b.dataset.id}"`)),
'confirm-delete-review':b=>{state.reviews=state.reviews.filter(r=>r.product!==b.dataset.id);closeDialog();render(false);toast('시안에서 후기를 삭제했습니다.');}
};
Object.assign(actions,{
'member-resume':b=>{selectLesson(Number(b.dataset.day));},
'member-mission':b=>{if(state.route==='mission')saveMissionDraft();const m=personalMission(Number(b.dataset.day));state.lesson=m.day;state.missionState=m.status;state.missionText=m.text||'';state.missionURL=m.url||'';state.missionFile=m.file||'';state.quizResult=null;go('mission');},
'member-level':()=>openDialog('나의 실행 레벨',`<p>클래스별로 승인된 미션을 기준으로 실행 레벨이 올라갑니다. 영상 학습 진도는 별도로 표시됩니다.</p><ul class="member-level-guide"><li><b>Lv.1 시작</b><span>클래스 수강 시작</span></li><li><b>Lv.2 실행</b><span>미션 1개 승인</span></li><li><b>Lv.3 성장</b><span>미션 5개 승인</span></li><li><b>Lv.4 확장</b><span>미션 10개 승인</span></li></ul><p class="mt16">현재 UI 시안의 예시 기준입니다. 운영 기준은 클래스 설정에 따라 적용됩니다.</p>`)
});
document.addEventListener('click',e=>{const b=e.target.closest('a,button');if(!b||b.disabled)return;const d=b.dataset;if(d.scroll||b.getAttribute('href')==='#main'){e.preventDefault();const el=document.getElementById(d.scroll||'main');el?.scrollIntoView({behavior:'smooth',block:'start'});return;}if(d.action){e.preventDefault();actions[d.action]?.(b);return;}if(d.product)state.paidId=d.product;if(d.return)state.returnTo=d.return;if(d.article)state.articleId=Number(d.article);if(d.lesson){e.preventDefault();selectLesson(Number(d.lesson));return;}if(d.classType){state.classType=d.classType;render(false);return;}const tabs={articleTag:'articleTag',myclassTab:'myClassTab',couponTab:'couponTab',reviewTab:'reviewTab',questionFilter:'questionFilter'};for(const [key,target]of Object.entries(tabs)){if(d[key]){state[target]=d[key];render(false);return;}}if(d.rating){state.rating=Number(d.rating);$('#rating-buttons').innerHTML=ratingButtons();$(`[data-rating="${state.rating}"]`).focus();return;}if(b.matches('a[href^="#"]')&&ROUTES[b.hash.slice(1)]){e.preventDefault();go(b.hash.slice(1));}});
document.addEventListener('input',e=>{const t=e.target;if(t.id==='class-search'){state.classQuery=t.value;$('#course-results').innerHTML=classResults();}if(t.id==='mission-content'){state.missionText=t.value;$('#mission-length').textContent=t.value.length;}if(t.id==='mission-url')state.missionURL=t.value;});
document.addEventListener('change',e=>{const t=e.target;if(t.id==='page-select')go(t.value);if(t.id==='class-sort'){state.classSort=t.value;$('#course-results').innerHTML=classResults();}if(t.id==='checkout-coupon'){state.coupon=t.value==='welcome';const discount=state.coupon&&state.checkoutId==='p1'?30000:0;$('#coupon-discount').textContent='−'+n(discount)+'원';$('#checkout-total').textContent=n(currentProduct().price-discount)+'원';}if(t.id==='resource-filter'){state.resourceFilter=t.value;render(false);}if(t.dataset.quiz!==undefined){state.lessonAnswers[`${state.lesson}:${t.dataset.quiz}`]=Number(t.value);state.quizResult=null;$$('.quiz-card').forEach(c=>c.classList.remove('correct','wrong'));$$('.quiz-feedback').forEach(c=>c.remove());$('#quiz-summary').innerHTML='';}if(t.id==='mission-file'){const f=t.files[0];if(!f)return;if(f.size>20*1024*1024){t.value='';state.missionFile='';$('#mission-file-name').textContent='20MB 이하 파일을 선택해 주세요.';return;}if(!/\.(pdf|png|jpe?g|docx|xlsx|txt|html)$/i.test(f.name)){t.value='';state.missionFile='';$('#mission-file-name').textContent='지원하는 형식의 파일을 선택해 주세요.';return;}state.missionFile=f.name;$('#mission-file-name').textContent=f.name+' · 로컬 선택 완료';}});
document.addEventListener('submit',e=>{const form=e.target;if(!form.matches('form'))return;e.preventDefault();const f=new FormData(form);switch(form.id){
case 'login-form':loginDemo();break;
case 'signup-form':state.profileName=String(f.get('name')).trim()||'김지민';state.logged=true;go(state.returnTo||'mypage');toast('가입 완료 화면으로 이동합니다. 실제 계정은 생성되지 않았습니다.');break;
case 'password-form':closeDialog();toast('재설정 안내 접수 상태입니다. 실제 이메일은 발송되지 않았습니다.');break;
case 'apply-form':state.profileName=String(f.get('name')).trim()||'김지민';state.applied=true;state.logged=true;state.myClassTab='수강 예정';go('applied');toast('신청 완료 화면 시안입니다. 실제 신청·안내 발송은 진행되지 않았습니다.');break;
case 'checkout-form':openDialog('결제 결과 미리보기',`${summaryProduct(currentProduct())}<p>실제 결제 없이 완료 또는 실패 화면으로 이동합니다. 입력한 결제 수단은 외부 서비스에 전달되지 않습니다.</p>`,btn('돌아가기','close-dialog')+btn('실패 화면 보기','payment-failure')+btn('완료 화면 보기','payment-success','primary'));break;
case 'mission-form':saveMissionDraft();if(!state.missionText.trim()){const err=$('#mission-error');err.textContent='실행 내용을 입력해 주세요.';$('#mission-content').focus();return;}openDialog('미션 제출 확인',`<p>작성한 실행 내용과 첨부 정보를 확인해 주세요.</p><div class="notice mt16" style="white-space:pre-wrap">${esc(state.missionText.slice(0,350))}${state.missionText.length>350?'…':''}</div>${state.missionFile?`<p class="mt16">첨부: ${esc(state.missionFile)}</p>`:''}<p class="meta mt16">이 시안에서는 제출 상태만 변경합니다.</p>`,btn('계속 수정','close-dialog')+btn('제출하기','mission-submit','primary'));break;
case 'question-form':{const day=Number(f.get('lesson'));state.questions.unshift({id:Date.now(),title:String(f.get('title')).trim(),body:String(f.get('body')).trim(),answer:'',date:'2026.09.10',lesson:`Day ${day} · ${DATA.lessons[day-1]}`});state.questionFilter='전체';closeDialog();go('questions');toast('이 탭 안에 질문을 추가했습니다. 실제 전송은 하지 않았습니다.');break;}
case 'refund-form':{if(state.refundOrder==='BA-20260828-0041')state.refundRequested=true;else state.extraRefunds=Object.assign(state.extraRefunds||{},{[state.refundOrder]:true});closeDialog();render(false);toast('환불 요청 상태를 시연했습니다. 실제 환불은 진행되지 않았습니다.');break;}
case 'coupon-form':$('#coupon-message').textContent=String(f.get('code')).trim().toUpperCase()==='WELCOME10'?'이미 보유한 쿠폰입니다. 아래에서 사용 조건을 확인해 주세요.':'유효한 쿠폰을 찾지 못했어요. 시안 예시 코드는 WELCOME10입니다.';break;
case 'profile-form':state.profileName=String(f.get('name')).trim()||'김지민';render(false);toast('이 탭 안에서 회원 이름을 변경했습니다. 실제 계정은 변경되지 않았습니다.');break;
case 'review-form':{const id=String(f.get('product')),text=String(f.get('text')).trim();if(!text){toast('후기 내용을 입력해 주세요.');return;}state.reviews=state.reviews.filter(x=>x.product!==id);state.reviews.push({product:id,text,rating:state.rating});state.reviewTab='내가 쓴 후기';closeDialog();render(false);toast('시안 안에 후기를 등록했습니다. 실제 상품에는 게시되지 않았습니다.');break;}
}});
window.addEventListener('hashchange',()=>{const r=location.hash.slice(1);if(ROUTES[r]){state.route=r;render();}});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const rect=$('#modal').getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)closeDialog();}});
state.route=ROUTES[location.hash.slice(1)]?location.hash.slice(1):INITIAL_ROUTE;
if(['mypage','myclasses','learning','mission','questions','orders','resources','coupons','profile','myreviews','checkout','apply','applied','result'].includes(state.route))state.logged=true;
if(state.route==='applied'){state.applied=true;state.myClassTab='수강 예정';}
if(state.route==='result'){recordPurchase();state.paid=true;state.myClassTab='수강 예정';}
render(false);
