import Link from "next/link";
import { ArrowRight, CalendarClock, CircleDollarSign, MoreHorizontal, TrendingUp, UserPlus, Users } from "lucide-react";
import { AdminPageTitle, AdminShell } from "../components/admin-shell";

export default function AdminDashboard(){return <AdminShell active="dashboard"><AdminPageTitle eyebrow="OVERVIEW" title="대시보드" description="판매와 수강 현황을 빠르게 확인하세요." action={<div className="date-filter">2026.08.01 — 08.31</div>}/>
  <section className="metric-grid"><article><div><span>이번 달 결제액</span><CircleDollarSign/></div><strong>₩ 12,840,000</strong><p><TrendingUp/> 지난달 대비 24.8%</p></article><article><div><span>신규 회원</span><UserPlus/></div><strong>184<small>명</small></strong><p><TrendingUp/> 지난달 대비 12.1%</p></article><article><div><span>수강 신청</span><Users/></div><strong>38<small>건</small></strong><p><TrendingUp/> 전환율 8.4%</p></article><article><div><span>진행 중인 기수</span><CalendarClock/></div><strong>2<small>개</small></strong><p>다음 개강 D-16</p></article></section>
  <div className="admin-dashboard-layout"><section className="admin-panel sales-chart"><div className="admin-panel-head"><div><h2>매출 추이</h2><p>최근 30일 결제 완료 기준</p></div><div className="tiny-tabs"><button>일간</button><button className="active">주간</button><button>월간</button></div></div><div className="chart-area"><div className="chart-y"><span>500만</span><span>400만</span><span>300만</span><span>200만</span><span>100만</span><span>0</span></div><div className="bars">{[26,40,31,58,49,73,68,92,80,100,73,88].map((v,i)=><div key={i}><i style={{height:`${v}%`}}/><span>{i%2===0?`${i+1}주`:""}</span></div>)}</div></div></section><section className="admin-panel cohort-summary"><div className="admin-panel-head"><div><h2>기수 모집 현황</h2><p>한 강의의 여러 기수</p></div><Link href="/admin/cohorts">전체보기 <ArrowRight/></Link></div><div className="cohort-mini"><div><span className="red-dot"/><div><strong>자영업 마케팅 실전반 1기</strong><small>모집 중 · 8월 19일 개강</small></div><em>23 / 30명</em></div><div className="mini-progress"><i style={{width:"77%"}}/></div></div><div className="cohort-mini"><div><span className="blue-dot"/><div><strong>자영업 마케팅 실전반 0기</strong><small>종료 · 녹화본 무기한 제공</small></div><em>30 / 30명</em></div><div className="mini-progress blue"><i style={{width:"100%"}}/></div></div></section></div>
  <div className="admin-bottom-grid"><section className="admin-panel"><div className="admin-panel-head"><div><h2>최근 주문</h2><p>오늘 12건의 주문이 있습니다.</p></div><Link href="/admin/orders">전체보기 <ArrowRight/></Link></div><div className="compact-table"><div className="table-head"><span>주문자</span><span>상품</span><span>금액</span><span>상태</span><span/></div>{[["김민지","자영업 마케팅 실전반 1기","450,000원"],["박성호","자영업 마케팅 실전반 1기","450,000원"],["이지은","자영업 마케팅 실전반 1기","490,000원"]].map(row=><div className="table-row" key={row[0]}><span><b className="mini-avatar">{row[0][0]}</b>{row[0]}</span><span>{row[1]}</span><strong>{row[2]}</strong><span className="status-label success">결제 완료</span><button><MoreHorizontal/></button></div>)}</div></section><section className="admin-panel task-panel"><div className="admin-panel-head"><div><h2>운영 체크</h2><p>오늘 확인할 업무</p></div></div><label><input type="checkbox"/><span><strong>1기 강의자료 최종 확인</strong><small>4개 회차 · D-16</small></span></label><label><input type="checkbox"/><span><strong>가상계좌 미입금 3건 확인</strong><small>24시간 자동 취소 예정</small></span></label><label><input type="checkbox" defaultChecked/><span><strong>지난주 정산 확인</strong><small>완료</small></span></label></section></div>
</AdminShell>}
