"use client";
import { FormEvent, useEffect, useState } from "react";
import { Copy, Pencil, Plus, Save, TicketPercent, Trash2, X } from "lucide-react";
import { useAdminUnsavedChanges } from "./use-admin-unsaved-changes";

type Course={id:string;title:string;status:string};
type Coupon={id:string;name:string;description:string|null;code:string;usage_limit:number|null;product_scope:"all"|"specific";discount_type:"fixed"|"percentage";discount_value:number;starts_at:string|null;ends_at:string|null;is_active:boolean;courseIds:string[];usedCount:number};
type Form={id?:string;name:string;description:string;code:string;usageLimit:string;productScope:"all"|"specific";courseIds:string[];discountType:"fixed"|"percentage";discountValue:string;periodType:"unlimited"|"range";startsAt:string;endsAt:string;isActive:boolean};
const empty:Form={name:"",description:"",code:"",usageLimit:"",productScope:"all",courseIds:[],discountType:"fixed",discountValue:"",periodType:"unlimited",startsAt:"",endsAt:"",isActive:true};
const local=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):"";
const date=(value:string|null)=>value?new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(value)):"제한 없음";

export function AdminCouponsManager(){
  const [coupons,setCoupons]=useState<Coupon[]>([]);
  const [courses,setCourses]=useState<Course[]>([]);
  const [form,setForm]=useState<Form>(empty);
  const [modalOpen,setModalOpen]=useState(false);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [error,setError]=useState("");
  const [copied,setCopied]=useState("");
  const dirty=modalOpen&&Boolean(form.id||form.name||form.description||form.code||form.usageLimit||form.discountValue||form.courseIds.length||form.startsAt||form.endsAt);
  useAdminUnsavedChanges(dirty&&!saving);
  const load=async()=>{setLoading(true);const response=await fetch("/api/admin/coupons",{cache:"no-store"});const data=await response.json();if(!response.ok)setError(data.error||"쿠폰을 불러오지 못했습니다.");else{setCoupons(data.coupons);setCourses(data.courses)}setLoading(false)};
  useEffect(()=>{let active=true;fetch("/api/admin/coupons",{cache:"no-store"}).then(async response=>({response,data:await response.json()})).then(({response,data})=>{if(!active)return;if(!response.ok)setError(data.error||"쿠폰을 불러오지 못했습니다.");else{setCoupons(data.coupons);setCourses(data.courses)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const close=(force:unknown=false)=>{if(force!==true&&dirty&&!saving&&!window.confirm("저장하지 않은 쿠폰 변경사항을 버릴까요?"))return;setModalOpen(false);setForm(empty);setError("")};
  const create=()=>{setForm(empty);setError("");setModalOpen(true)};
  const edit=(item:Coupon)=>{setForm({id:item.id,name:item.name,description:item.description||"",code:item.code,usageLimit:item.usage_limit?String(item.usage_limit):"",productScope:item.product_scope,courseIds:item.courseIds,discountType:item.discount_type,discountValue:String(item.discount_value),periodType:item.starts_at||item.ends_at?"range":"unlimited",startsAt:local(item.starts_at),endsAt:local(item.ends_at),isActive:item.is_active});setError("");setModalOpen(true)};
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError("");const response=await fetch("/api/admin/coupons",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,usageLimit:form.usageLimit?Number(form.usageLimit):null,discountValue:Number(form.discountValue),startsAt:form.periodType==="range"&&form.startsAt?new Date(form.startsAt).toISOString():null,endsAt:form.periodType==="range"&&form.endsAt?new Date(form.endsAt).toISOString():null})});const data=await response.json();if(!response.ok)setError(data.error||"쿠폰을 저장하지 못했습니다.");else{close(true);await load()}setSaving(false)};
  const remove=async(id:string)=>{const item=coupons.find(coupon=>coupon.id===id);if(!window.confirm(`‘${item?.name||"선택한 쿠폰"}’을 삭제할까요? 결제 화면에서 즉시 사용할 수 없게 되며 사용 이력은 보존됩니다.`))return;const response=await fetch("/api/admin/coupons",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const data=await response.json();if(!response.ok)setError(data.error||"쿠폰을 삭제하지 못했습니다.");else await load()};
  const toggle=async(item:Coupon)=>{setError("");const response=await fetch("/api/admin/coupons",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,isActive:!item.is_active})});const data=await response.json();if(!response.ok)setError(data.error||"쿠폰 상태를 변경하지 못했습니다.");else setCoupons(rows=>rows.map(row=>row.id===item.id?{...row,is_active:!row.is_active}:row))};
  const copy=async(code:string)=>{await navigator.clipboard.writeText(code);setCopied(code);window.setTimeout(()=>setCopied(""),1400)};
  if(loading)return <section className="admin-panel admin-loading-state"><strong>쿠폰 정보를 불러오는 중입니다.</strong></section>;
  const active=coupons.filter(item=>item.is_active&&(!item.ends_at||new Date(item.ends_at)>new Date())).length;const totalUsed=coupons.reduce((sum,item)=>sum+item.usedCount,0);const ended=coupons.filter(item=>!item.is_active||(item.ends_at&&new Date(item.ends_at)<=new Date())).length;
  return <>
    <section className="coupon-summary"><span>전체 쿠폰 <strong>{coupons.length}</strong></span><span>사용 중 <strong>{active}</strong></span><span>누적 사용 <strong>{totalUsed}건</strong></span><span>종료 <strong>{ended}</strong></span></section>
    <section className="admin-panel coupon-list coupon-list-full coupon-table-view">
      <header><div><h2>쿠폰</h2><p>할인 코드와 실제 사용 현황을 관리합니다.</p></div><button className="admin-primary" onClick={create}><Plus/>쿠폰 만들기</button></header>
      {coupons.length>0&&<div className="coupon-table-head"><span>쿠폰명</span><span>코드</span><span>할인</span><span>적용 대상</span><span>사용 기간</span><span>사용</span><span>상태</span><span>관리</span></div>}
      {coupons.length?coupons.map(item=><article key={item.id} className={!item.is_active?"inactive":""}><div className="coupon-name-cell"><strong>{item.name}</strong><small>{item.description||"설명 없음"}</small></div><button className="coupon-code-copy" onClick={()=>void copy(item.code)}><code>{item.code}</code><Copy/><small>{copied===item.code?"복사됨":""}</small></button><strong className="coupon-discount-cell">{item.discount_value.toLocaleString("ko-KR")}{item.discount_type==="fixed"?"원":"%"}</strong><span>{item.product_scope==="all"?"전체 상품":`${item.courseIds.length}개 상품`}</span><span>{item.starts_at?`${date(item.starts_at)} — ${date(item.ends_at)}`:"상시"}</span><span>{item.usedCount}{item.usage_limit?` / ${item.usage_limit}`:""}</span><button className={`coupon-toggle ${item.is_active?"on":""}`} onClick={()=>void toggle(item)} aria-label={`${item.name} ${item.is_active?"중지":"활성화"}`}><i/></button><div className="coupon-row-actions"><button onClick={()=>edit(item)} aria-label="쿠폰 수정"><Pencil/></button><button onClick={()=>remove(item.id)} aria-label="쿠폰 삭제"><Trash2/></button></div></article>):<div className="coupon-empty"><TicketPercent/><strong>등록된 쿠폰이 없습니다.</strong><p>새 쿠폰 등록 버튼에서 첫 쿠폰을 만들어 결제 화면에서 테스트하세요.</p><button className="admin-primary" onClick={create}><Plus/>새 쿠폰 등록</button></div>}
      {!modalOpen&&error&&<p className="admin-save-error" role="alert">{error}</p>}
    </section>
    {modalOpen&&<div className="coupon-modal-backdrop" role="presentation" onMouseDown={(event)=>{if(event.target===event.currentTarget)close()}}><div className="coupon-modal" role="dialog" aria-modal="true" aria-labelledby="coupon-modal-title"><form className="coupon-form" onSubmit={submit}>
      <header><div><span><TicketPercent/>COUPON SETTING</span><h2 id="coupon-modal-title">{form.id?"쿠폰 수정":"새 쿠폰 등록"}</h2><p>결제 단계에서 서버가 사용 조건과 할인 금액을 다시 검증합니다.</p></div><button type="button" className="coupon-modal-close" onClick={close} aria-label="닫기"><X/></button></header>
      <div className="coupon-modal-scroll"><label>쿠폰 이름<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>쿠폰 설명<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="coupon-form-two"><label>쿠폰 코드<input value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,"")})} placeholder="AIBIZ20" required/></label><label>사용 수량<input type="number" min="1" value={form.usageLimit} onChange={e=>setForm({...form,usageLimit:e.target.value})} placeholder="비우면 제한 없음"/></label></div>
      <fieldset><legend>사용 상품</legend><div className="coupon-choice"><button type="button" className={form.productScope==="all"?"active":""} onClick={()=>setForm({...form,productScope:"all",courseIds:[]})}>전체 상품</button><button type="button" className={form.productScope==="specific"?"active":""} onClick={()=>setForm({...form,productScope:"specific"})}>특정 상품</button></div>{form.productScope==="specific"&&<div className="coupon-product-list">{courses.map(course=><label key={course.id}><input type="checkbox" checked={form.courseIds.includes(course.id)} onChange={e=>setForm({...form,courseIds:e.target.checked?[...form.courseIds,course.id]:form.courseIds.filter(id=>id!==course.id)})}/><span>{course.title}<small>{course.status}</small></span></label>)}</div>}</fieldset>
      <fieldset><legend>할인 방식</legend><div className="coupon-choice"><button type="button" className={form.discountType==="fixed"?"active":""} onClick={()=>setForm({...form,discountType:"fixed"})}>가격 할인</button><button type="button" className={form.discountType==="percentage"?"active":""} onClick={()=>setForm({...form,discountType:"percentage"})}>퍼센트 할인</button></div><label>할인 값<div className="coupon-value"><input type="number" min="1" max={form.discountType==="percentage"?100:undefined} value={form.discountValue} onChange={e=>setForm({...form,discountValue:e.target.value})} required/><span>{form.discountType==="fixed"?"원":"%"}</span></div></label></fieldset>
      <fieldset><legend>사용 기한</legend><div className="coupon-choice"><button type="button" className={form.periodType==="unlimited"?"active":""} onClick={()=>setForm({...form,periodType:"unlimited",startsAt:"",endsAt:""})}>제한 없음</button><button type="button" className={form.periodType==="range"?"active":""} onClick={()=>setForm({...form,periodType:"range"})}>지정 기간</button></div>{form.periodType==="range"&&<div className="coupon-form-two"><label>시작<input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>종료<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label></div>}</fieldset><label className="coupon-active"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/>결제 화면에서 사용 가능</label>{error&&<p className="admin-save-error" role="alert">{error}</p>}</div>
      <footer><button type="button" className="admin-outline" onClick={close}>취소</button><button className="admin-primary" disabled={saving}><Save/>{saving?"저장 중...":"쿠폰 저장"}</button></footer>
    </form></div></div>}
  </>;
}
