"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, Megaphone, MessageSquareText, Plus, RefreshCw, Save, Send, Tags, Trash2, Users } from "lucide-react";

type Tag={id:string;name:string;color:string;description:string|null};
type Template={id:string;name:string;channel:"sms"|"lms"|"alimtalk";purpose:"marketing"|"transactional";content:string;alimtalk_template_id:string|null;is_active:boolean};
type Member={id:string;email:string;full_name:string|null;phone:string|null;status:string;marketing_consent:boolean;marketing_consent_at:string|null};
type Campaign={id:string;name:string;status:string;recipient_count:number;success_count:number;failure_count:number;sent_at:string|null;error_message:string|null;crm_templates:{name:string;channel:string}|Array<{name:string;channel:string}>|null;crm_tags:{name:string}|Array<{name:string}>|null};
type MemberTag={member_id:string;tag_id:string};
type Data={tags:Tag[];templates:Template[];campaigns:Campaign[];members:Member[];memberTags:MemberTag[];solapiConfigured:boolean;alimtalkConfigured:boolean};
const empty:Data={tags:[],templates:[],campaigns:[],members:[],memberTags:[],solapiConfigured:false,alimtalkConfigured:false};
const templateDraft={name:"",channel:"sms" as Template["channel"],purpose:"marketing" as Template["purpose"],content:"",alimtalkTemplateId:"",isActive:true};
const one=<T,>(value:T|T[]|null)=>Array.isArray(value)?value[0]||null:value;

async function api(body?:Record<string,unknown>){const response=await fetch("/api/admin/crm",body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"});const data=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok)throw new Error(String(data.error||"CRM 요청을 처리하지 못했습니다."));return data}

export function AdminCrmManager(){
  const [data,setData]=useState<Data>(empty);const [tab,setTab]=useState<"audience"|"templates"|"campaigns">("audience");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const [tagName,setTagName]=useState("");const [memberQuery,setMemberQuery]=useState("");const [draft,setDraft]=useState({...templateDraft});const [editingTemplate,setEditingTemplate]=useState<string|null>(null);const [campaign,setCampaign]=useState({name:"",templateId:"",targetTagId:""});
  const load=async()=>{setError("");const result=await api() as unknown as Data;setData(result);setLoading(false)};
  useEffect(()=>{void Promise.resolve().then(load).catch(reason=>{setError(reason instanceof Error?reason.message:"CRM을 불러오지 못했습니다.");setLoading(false)})},[]);
  const mutate=async(body:Record<string,unknown>,success:string)=>{setSaving(true);setError("");setMessage("");try{const result=await api(body);setMessage(success);await load();return result}catch(reason){setError(reason instanceof Error?reason.message:"저장하지 못했습니다.");return null}finally{setSaving(false)}};
  const memberTags=(id:string)=>data.memberTags.filter(row=>row.member_id===id).map(row=>row.tag_id);
  const toggleTag=async(memberId:string,tagId:string)=>{const current=memberTags(memberId);await mutate({action:"setMemberTags",memberId,tagIds:current.includes(tagId)?current.filter(id=>id!==tagId):[...current,tagId]},"회원 태그를 저장했습니다.")};
  const visibleMembers=useMemo(()=>data.members.filter(member=>[member.full_name||"",member.email,member.phone||""].some(value=>value.toLowerCase().includes(memberQuery.toLowerCase()))),[data.members,memberQuery]);
  const saveTemplate=async()=>{const result=await mutate({action:"saveTemplate",id:editingTemplate||undefined,...draft},"메시지 템플릿을 저장했습니다.");if(result){setDraft({...templateDraft});setEditingTemplate(null)}};
  const editTemplate=(item:Template)=>{setEditingTemplate(item.id);setDraft({name:item.name,channel:item.channel,purpose:item.purpose,content:item.content,alimtalkTemplateId:item.alimtalk_template_id||"",isActive:item.is_active})};
  const createCampaign=async(sendNow:boolean)=>{const result=await mutate({action:"saveCampaign",name:campaign.name,templateId:campaign.templateId,targetTagId:campaign.targetTagId||null},"캠페인을 저장했습니다.");if(result?.id&&sendNow){const sent=await mutate({action:"sendCampaign",campaignId:result.id},"메시지 발송 요청을 완료했습니다.");if(sent)setCampaign({name:"",templateId:"",targetTagId:""})}};
  if(loading)return <section className="admin-panel admin-loading-state"><RefreshCw className="spin"/><strong>CRM 데이터를 불러오는 중입니다.</strong></section>;
  return <div className="crm-page">
    <div className="crm-status"><article><Users/><span>관리 회원<strong>{data.members.length}</strong></span></article><article><Check/><span>마케팅 수신 동의<strong>{data.members.filter(m=>m.marketing_consent&&m.phone).length}</strong></span></article><article><Tags/><span>고객 태그<strong>{data.tags.length}</strong></span></article><article className={data.solapiConfigured?"ready":"warning"}><Send/><span>SOLAPI<strong>{data.solapiConfigured?"발송 가능":"환경변수 필요"}</strong></span></article></div>
    <nav className="crm-tabs"><button className={tab==="audience"?"active":""} onClick={()=>setTab("audience")}><Users/>고객·태그</button><button className={tab==="templates"?"active":""} onClick={()=>setTab("templates")}><MessageSquareText/>메시지 템플릿</button><button className={tab==="campaigns"?"active":""} onClick={()=>setTab("campaigns")}><Megaphone/>캠페인·발송</button></nav>
    {tab==="audience"&&<div className="crm-audience-layout"><section className="admin-panel crm-tag-panel"><header><h2>고객 태그</h2><span>{data.tags.length}개</span></header><div className="crm-tag-add"><input value={tagName} onChange={event=>setTagName(event.target.value)} placeholder="예: 무료강의 참여"/><button onClick={async()=>{const result=await mutate({action:"saveTag",name:tagName},"태그를 만들었습니다.");if(result)setTagName("")}} disabled={!tagName.trim()||saving}><Plus/></button></div>{data.tags.map(tag=><article key={tag.id}><i style={{background:tag.color}}/><strong>{tag.name}</strong><small>{data.memberTags.filter(row=>row.tag_id===tag.id).length}명</small><button onClick={()=>void mutate({action:"deleteTag",id:tag.id},"태그를 삭제했습니다.")}><Trash2/></button></article>)}</section><section className="admin-panel crm-member-panel"><header><div><h2>회원 태그 분류</h2><p>회원별로 여러 개의 태그를 지정할 수 있습니다.</p></div><input value={memberQuery} onChange={event=>setMemberQuery(event.target.value)} placeholder="이름·이메일 검색"/></header><div className="crm-member-list">{visibleMembers.map(member=><article key={member.id}><div><strong>{member.full_name||"이름 미입력"}</strong><small>{member.email} · {member.phone||"휴대폰 없음"}</small></div><span className={member.marketing_consent?"consent yes":"consent"}>{member.marketing_consent?"마케팅 동의":"미동의"}</span><div>{data.tags.map(tag=><button key={tag.id} className={memberTags(member.id).includes(tag.id)?"selected":""} onClick={()=>void toggleTag(member.id,tag.id)}>{tag.name}</button>)}</div></article>)}</div></section></div>}
    {tab==="templates"&&<div className="crm-template-layout"><section className="admin-panel crm-template-form"><h2>{editingTemplate?"템플릿 수정":"새 메시지 템플릿"}</h2><label>템플릿 이름<input value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})} placeholder="무료강의 참여 안내"/></label><div className="form-two"><label>채널<select value={draft.channel} onChange={event=>setDraft({...draft,channel:event.target.value as Template["channel"]})}><option value="sms">SMS</option><option value="lms">LMS</option><option value="alimtalk">카카오 알림톡</option></select></label><label>용도<select value={draft.purpose} onChange={event=>setDraft({...draft,purpose:event.target.value as Template["purpose"]})}><option value="marketing">마케팅</option><option value="transactional">정보성</option></select></label></div>{draft.channel==="alimtalk"&&<label>알림톡 승인 템플릿 ID<input value={draft.alimtalkTemplateId} onChange={event=>setDraft({...draft,alimtalkTemplateId:event.target.value})}/></label>}<label>메시지 내용<textarea value={draft.content} onChange={event=>setDraft({...draft,content:event.target.value})} placeholder={'#{이름}님, 브랜디액션의 새로운 클래스가 열렸습니다.'}/><small>개인화 변수: #&#123;이름&#125;</small></label><div><button className="admin-outline" onClick={()=>{setDraft({...templateDraft});setEditingTemplate(null)}}>초기화</button><button className="admin-primary" onClick={()=>void saveTemplate()} disabled={saving||!draft.name.trim()||!draft.content.trim()}><Save/>저장</button></div></section><section className="admin-panel crm-template-list"><header><h2>등록된 템플릿</h2><span>{data.templates.length}개</span></header>{data.templates.map(item=><article key={item.id}><span>{item.channel.toUpperCase()}</span><div><strong>{item.name}</strong><small>{item.purpose==="marketing"?"마케팅":"정보성"} · {item.content.slice(0,70)}</small></div><button onClick={()=>editTemplate(item)}>수정</button><button onClick={()=>void mutate({action:"deleteTemplate",id:item.id},"템플릿을 삭제했습니다.")}><Trash2/></button></article>)}</section></div>}
    {tab==="campaigns"&&<div className="crm-campaign-layout"><section className="admin-panel crm-campaign-form"><h2>캠페인 만들기</h2><label>캠페인 이름<input value={campaign.name} onChange={event=>setCampaign({...campaign,name:event.target.value})} placeholder="8월 무료강의 참여 안내"/></label><label>메시지 템플릿<select value={campaign.templateId} onChange={event=>setCampaign({...campaign,templateId:event.target.value})}><option value="">템플릿 선택</option>{data.templates.filter(t=>t.is_active).map(item=><option value={item.id} key={item.id}>{item.name} · {item.channel.toUpperCase()}</option>)}</select></label><label>대상 태그<select value={campaign.targetTagId} onChange={event=>setCampaign({...campaign,targetTagId:event.target.value})}><option value="">전체 수신 동의 회원</option>{data.tags.map(tag=><option value={tag.id} key={tag.id}>{tag.name} · {data.memberTags.filter(row=>row.tag_id===tag.id).length}명</option>)}</select></label><p>실제 발송 시 활성 상태·휴대폰 보유·마케팅 수신 동의를 다시 검증합니다. 최대 500명까지 한 번에 발송합니다.</p><div><button className="admin-outline" onClick={()=>void createCampaign(false)} disabled={saving}>임시 저장</button><button className="admin-primary" onClick={()=>void createCampaign(true)} disabled={saving||!campaign.name.trim()||!campaign.templateId||!data.solapiConfigured}><Send/>즉시 발송</button></div></section><section className="admin-panel crm-campaign-list"><header><h2>캠페인 이력</h2><span>{data.campaigns.length}개</span></header>{data.campaigns.map(item=><article key={item.id}><span className={`campaign-status ${item.status}`}>{item.status}</span><div><strong>{item.name}</strong><small>{one(item.crm_templates)?.name} · {one(item.crm_tags)?.name||"전체 동의 회원"}</small>{item.error_message&&<em>{item.error_message}</em>}</div><span>대상 {item.recipient_count}</span><span>성공 {item.success_count} / 실패 {item.failure_count}</span>{["draft","failed"].includes(item.status)?<button onClick={()=>void mutate({action:"sendCampaign",campaignId:item.id},"메시지 발송 요청을 완료했습니다.")} disabled={saving||!data.solapiConfigured}><Send/>발송</button>:<time>{item.sent_at?new Intl.DateTimeFormat("ko-KR",{dateStyle:"short",timeStyle:"short"}).format(new Date(item.sent_at)):"-"}</time>}</article>)}</section></div>}
    {message&&<p className="admin-save-success"><Check/>{message}</p>}{error&&<p className="admin-save-error" role="alert">{error}</p>}
  </div>
}
