"use client";
import { useEffect, useState } from "react";
import { defaultSeoSettings, type SeoSettings } from "@/lib/seo-settings-shared";
import { useAdminUnsavedChanges } from "./use-admin-unsaved-changes";
export function AdminSeoManager() {
  const [value, setValue] = useState<SeoSettings>(defaultSeoSettings); const [saved, setSaved] = useState("");
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useAdminUnsavedChanges(!loading && Boolean(saved) && JSON.stringify(value) !== saved);
  useEffect(() => { let active = true; fetch("/api/admin/seo", { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); if (active) { setValue(result.settings); setSaved(JSON.stringify(result.settings)); } }).catch((reason) => { if (active) setError(reason.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const save = async () => { setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/seo", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSaved(JSON.stringify(value)); setMessage("SEO 설정을 저장했습니다."); } catch (reason) { setError(reason instanceof Error ? reason.message : "저장하지 못했습니다."); } finally { setBusy(false); } };
  return <div className="seo-workspace"><section className="admin-panel admin-form-card"><header><h2>검색·공유 기본 정보</h2><p className="studio-help">사이트 제목·설명과 공유 미리보기 이미지를 관리합니다.</p></header><fieldset className="admin-editor-fields" disabled={loading || busy}><label>검색 제목<input value={value.title} maxLength={120} onChange={(e) => setValue({ ...value, title: e.target.value })}/><small>{value.title.length} / 120자</small></label><label>검색 설명<textarea value={value.description} maxLength={300} onChange={(e) => setValue({ ...value, description: e.target.value })}/><small>{value.description.length} / 300자</small></label><label>공유 이미지 주소 (선택)<input type="url" placeholder="https://" value={value.image} onChange={(e) => setValue({ ...value, image: e.target.value })}/></label><button className="admin-primary" onClick={() => void save()}>{busy ? "저장 중…" : "SEO 저장"}</button></fieldset>{error && <p className="admin-save-error" role="alert">{error}</p>}{message && <p className="admin-save-success" role="status">{message}</p>}</section><section className="admin-panel seo-preview"><h2>검색 결과 미리보기</h2><small>브랜디액션 에듀</small><strong>{value.title}</strong><p>{value.description}</p><hr/><p className="studio-help">검색 서비스에서 제목과 설명이 다르게 표시될 수 있습니다. DEV 환경은 검색 노출을 차단합니다.</p></section></div>;
}
