"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { CSSProperties } from "react";
import { AlertTriangle, Check, ChevronRight, Edit3, Megaphone, MessageSquareText, RefreshCw, Save, Send, Tags, Trash2, Users } from "lucide-react";

type Tag = { id: string; name: string; color: string; description: string | null };
type Template = { id: string; name: string; channel: "sms" | "lms" | "alimtalk"; purpose: "marketing" | "transactional"; content: string; alimtalk_template_id: string | null; is_active: boolean };
type Member = { id: string; email: string; full_name: string | null; phone: string | null; status: string; marketing_consent: boolean; marketing_consent_at: string | null };
type Campaign = { id: string; name: string; status: string; recipient_count: number; success_count: number; failure_count: number; sent_at: string | null; error_message: string | null; crm_templates: Template | Template[] | null; crm_tags: Tag | Tag[] | null };
type MemberTag = { member_id: string; tag_id: string };
type Data = { tags: Tag[]; templates: Template[]; campaigns: Campaign[]; members: Member[]; memberTags: MemberTag[]; solapiConfigured: boolean; alimtalkConfigured: boolean };
const empty: Data = { tags: [], templates: [], campaigns: [], members: [], memberTags: [], solapiConfigured: false, alimtalkConfigured: false };
const emptyTag = { id: "", name: "", color: "#A10D12", description: "" };
const emptyTemplate = { id: "", name: "", channel: "sms" as Template["channel"], purpose: "marketing" as Template["purpose"], content: "", alimtalkTemplateId: "", isActive: true };
const one = <T,>(value: T | T[] | null) => Array.isArray(value) ? value[0] || null : value;

async function api(body?: Record<string, unknown>) {
  const response = await fetch("/api/admin/crm", body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : { cache: "no-store" });
  const result = await response.json().catch(() => ({})) as Record<string, unknown>;
  if (!response.ok) throw new Error(String(result.error || "CRM 요청을 처리하지 못했습니다."));
  return result;
}

export function AdminCrmManager() {
  const [data, setData] = useState<Data>(empty);
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [memberQuery, setMemberQuery] = useState("");
  const [tagDraft, setTagDraft] = useState({ ...emptyTag });
  const [templateDraft, setTemplateDraft] = useState({ ...emptyTemplate });
  const [campaign, setCampaign] = useState({ name: "", targetTagId: "", templateId: "" });
  const load = async () => { setError(""); try { setData(await api() as unknown as Data); } catch (reason) { setError(reason instanceof Error ? reason.message : "CRM 데이터를 불러오지 못했습니다."); } finally { setLoading(false); } };
  useEffect(() => { void Promise.resolve().then(load); }, []);
  const mutate = async (body: Record<string, unknown>, success: string) => { setSaving(true); setError(""); setMessage(""); try { const result = await api(body); setMessage(success); await load(); return result; } catch (reason) { setError(reason instanceof Error ? reason.message : "저장하지 못했습니다."); return null; } finally { setSaving(false); } };
  const memberTagIds = useCallback((memberId: string) => data.memberTags.filter((row) => row.member_id === memberId).map((row) => row.tag_id), [data.memberTags]);
  const targetMembers = useMemo(() => campaign.targetTagId ? data.members.filter((member) => memberTagIds(member.id).includes(campaign.targetTagId)) : data.members, [data.members, campaign.targetTagId, memberTagIds]);
  const selectedTag = data.tags.find((tag) => tag.id === campaign.targetTagId) || null;
  const selectedTemplate = data.templates.find((template) => template.id === campaign.templateId) || null;
  const requiresConsent = selectedTemplate?.purpose !== "transactional";
  const eligible = targetMembers.filter((member) => member.status === "active" && (!requiresConsent || member.marketing_consent) && member.phone);
  const excluded = { inactive: targetMembers.filter((member) => member.status !== "active").length, noConsent: requiresConsent ? targetMembers.filter((member) => member.status === "active" && !member.marketing_consent).length : 0, noPhone: targetMembers.filter((member) => member.status === "active" && (!requiresConsent || member.marketing_consent) && !member.phone).length };
  const visibleMembers = data.members.filter((member) => [member.full_name || "", member.email, member.phone || ""].some((value) => value.toLowerCase().includes(memberQuery.toLowerCase())));
  const saveTag = async () => { const result = await mutate({ action: "saveTag", id: tagDraft.id || undefined, name: tagDraft.name, color: tagDraft.color, description: tagDraft.description }, tagDraft.id ? "고객 태그를 수정했습니다." : "고객 태그를 만들었습니다."); if (result) setTagDraft({ ...emptyTag }); };
  const toggleTag = async (memberId: string, tagId: string) => { const current = memberTagIds(memberId); await mutate({ action: "setMemberTags", memberId, tagIds: current.includes(tagId) ? current.filter((id) => id !== tagId) : [...current, tagId] }, "회원 태그를 저장했습니다."); };
  const saveTemplate = async () => { const result = await mutate({ action: "saveTemplate", id: templateDraft.id || undefined, name: templateDraft.name, channel: templateDraft.channel, purpose: templateDraft.purpose, content: templateDraft.content, alimtalkTemplateId: templateDraft.alimtalkTemplateId, isActive: templateDraft.isActive }, templateDraft.id ? "템플릿을 수정했습니다." : "템플릿을 저장했습니다."); if (result) { setTemplateDraft({ ...emptyTemplate }); if (!campaign.templateId && data.templates.length === 0) await load(); } };
  const editTemplate = (template: Template) => { setTemplateDraft({ id: template.id, name: template.name, channel: template.channel, purpose: template.purpose, content: template.content, alimtalkTemplateId: template.alimtalk_template_id || "", isActive: template.is_active }); };
  const createCampaign = async (sendNow: boolean) => {
    if (!campaign.name.trim() || !campaign.templateId) { setError("캠페인 이름과 메시지 템플릿을 선택해 주세요."); return; }
    if (sendNow && !window.confirm(`${eligible.length}명에게 실제 메시지를 발송할까요? 발송 후에는 취소할 수 없습니다.`)) return;
    const created = await mutate({ action: "saveCampaign", name: campaign.name, templateId: campaign.templateId, targetTagId: campaign.targetTagId || null }, sendNow ? "발송 준비를 완료했습니다." : "캠페인을 임시 저장했습니다.");
    if (created?.id && sendNow) { const sent = await mutate({ action: "sendCampaign", campaignId: created.id }, `${eligible.length}명에게 발송 요청을 완료했습니다.`); if (sent) { setCampaign({ name: "", targetTagId: "", templateId: "" }); setStep(1); } }
  };

  if (loading) return <section className="admin-panel admin-loading-state"><RefreshCw className="spin"/><strong>실행 가능한 CRM 환경을 준비하는 중입니다.</strong></section>;
  return <div className="crm-workspace">
    <section className="crm-readiness">
      <article><Users/><span>전체 회원<strong>{data.members.length}명</strong></span></article>
        <article><Check/><span>마케팅 발송 가능<strong>{data.members.filter((member) => member.status === "active" && member.marketing_consent && member.phone).length}명</strong></span></article>
      <article><Tags/><span>고객 태그<strong>{data.tags.length}개</strong></span></article>
      <article className={data.solapiConfigured ? "ready" : "blocked"}><Send/><span>실발송 연결<strong>{data.solapiConfigured ? "SOLAPI 준비 완료" : "환경변수 필요"}</strong></span></article>
    </section>
    <nav className="crm-steps" aria-label="CRM 실행 단계">
      {([{ id: 1, label: "대상 분류", desc: "태그·동의 확인", icon: Users }, { id: 2, label: "메시지 작성", desc: "템플릿·미리보기", icon: MessageSquareText }, { id: 3, label: "검토·발송", desc: "대상 확정·실행", icon: Send }] as const).map((item, index) => { const Icon = item.icon; return <div key={item.id}><button className={step === item.id ? "active" : step > item.id ? "done" : ""} onClick={() => setStep(item.id)}><span>{step > item.id ? <Check/> : <Icon/>}</span><div><small>STEP {item.id}</small><strong>{item.label}</strong><em>{item.desc}</em></div></button>{index < 2 && <ChevronRight/>}</div>; })}
    </nav>

    {step === 1 && <div className="crm-audience-workspace">
      <section className="admin-panel crm-tag-builder"><header><div><h2>고객 태그 관리</h2><p>세그먼트의 기준과 용도를 함께 기록하세요.</p></div><span>{data.tags.length}개</span></header><div className="tag-builder-form"><div><input type="color" value={tagDraft.color} onChange={(event) => setTagDraft({ ...tagDraft, color: event.target.value })}/><input value={tagDraft.name} onChange={(event) => setTagDraft({ ...tagDraft, name: event.target.value })} placeholder="예: 무료강의 참여"/></div><textarea value={tagDraft.description} onChange={(event) => setTagDraft({ ...tagDraft, description: event.target.value })} placeholder="이 태그가 붙는 기준과 활용 목적"/><div>{tagDraft.id && <button className="admin-outline" onClick={() => setTagDraft({ ...emptyTag })}>취소</button>}<button className="admin-primary" onClick={() => void saveTag()} disabled={!tagDraft.name.trim() || saving}><Save/>{tagDraft.id ? "수정 저장" : "태그 추가"}</button></div></div><div className="tag-library">{data.tags.map((tag) => <article key={tag.id} className={campaign.targetTagId === tag.id ? "target" : ""}><i style={{ background: tag.color }}/><div><strong>{tag.name}</strong><small>{tag.description || "설명 없음"} · {data.memberTags.filter((row) => row.tag_id === tag.id).length}명</small></div><button onClick={() => setTagDraft({ id: tag.id, name: tag.name, color: tag.color, description: tag.description || "" })}><Edit3/></button><button onClick={() => void mutate({ action: "deleteTag", id: tag.id }, "태그를 삭제했습니다.")}><Trash2/></button></article>)}</div></section>
      <section className="admin-panel crm-segment-members"><header><div><h2>회원 태그 배정</h2><p>한 회원에게 여러 태그를 지정할 수 있습니다.</p></div><input value={memberQuery} onChange={(event) => setMemberQuery(event.target.value)} placeholder="이름·이메일·휴대폰 검색"/></header><div>{visibleMembers.map((member) => <article key={member.id}><div><strong>{member.full_name || "이름 미입력"}</strong><small>{member.email} · {member.phone || "휴대폰 없음"}</small></div><span className={member.marketing_consent ? "consent yes" : "consent"}>{member.marketing_consent ? "마케팅 동의" : "미동의"}</span><div>{data.tags.map((tag) => <button key={tag.id} className={memberTagIds(member.id).includes(tag.id) ? "selected" : ""} style={{ "--tag-color": tag.color } as CSSProperties} onClick={() => void toggleTag(member.id, tag.id)}>{tag.name}</button>)}</div></article>)}</div></section>
      <aside className="admin-panel crm-next-card"><span>발송 대상 선택</span><h2>{selectedTag?.name || "전체 수신 동의 회원"}</h2><p>현재 조건에서 실제 발송 가능한 회원은 <strong>{eligible.length}명</strong>입니다.</p><label>대상 태그<select value={campaign.targetTagId} onChange={(event) => setCampaign({ ...campaign, targetTagId: event.target.value })}><option value="">전체 회원</option>{data.tags.map((tag) => <option key={tag.id} value={tag.id}>{tag.name} · {data.memberTags.filter((row) => row.tag_id === tag.id).length}명</option>)}</select></label><dl><div><dt>태그 대상</dt><dd>{targetMembers.length}명</dd></div><div><dt>마케팅 미동의</dt><dd>-{excluded.noConsent}명</dd></div><div><dt>휴대폰 없음</dt><dd>-{excluded.noPhone}명</dd></div><div><dt>비활성</dt><dd>-{excluded.inactive}명</dd></div></dl><button className="admin-primary" onClick={() => setStep(2)} disabled={!eligible.length}>대상 확정하고 메시지 작성<ChevronRight/></button></aside>
    </div>}

    {step === 2 && <div className="crm-compose-workspace">
      <section className="admin-panel crm-template-editor"><header><div><h2>{templateDraft.id ? "메시지 템플릿 수정" : "새 메시지 템플릿"}</h2><p>광고성 여부와 채널을 먼저 선택하면 필수 조건을 확인할 수 있습니다.</p></div></header><div className="form-two"><label>템플릿 이름<input value={templateDraft.name} onChange={(event) => setTemplateDraft({ ...templateDraft, name: event.target.value })} placeholder="무료강의 참여 안내"/></label><label>채널<select value={templateDraft.channel} onChange={(event) => setTemplateDraft({ ...templateDraft, channel: event.target.value as Template["channel"] })}><option value="sms">SMS</option><option value="lms">LMS</option><option value="alimtalk">카카오 알림톡</option></select></label></div><label>메시지 용도<select value={templateDraft.purpose} onChange={(event) => setTemplateDraft({ ...templateDraft, purpose: event.target.value as Template["purpose"] })}><option value="marketing">마케팅·광고</option><option value="transactional">정보성 안내</option></select></label>{templateDraft.channel === "alimtalk" && <label>알림톡 승인 템플릿 ID<input value={templateDraft.alimtalkTemplateId} onChange={(event) => setTemplateDraft({ ...templateDraft, alimtalkTemplateId: event.target.value })}/></label>}<label>메시지 내용<textarea value={templateDraft.content} onChange={(event) => setTemplateDraft({ ...templateDraft, content: event.target.value })} placeholder={'#{이름}님, 브랜디액션의 새로운 클래스가 열렸습니다.'}/><small>개인화 변수 #&#123;이름&#125; · 현재 {templateDraft.content.length}자</small></label><div className="template-editor-actions"><button className="admin-outline" onClick={() => setTemplateDraft({ ...emptyTemplate })}>초기화</button><button className="admin-primary" onClick={() => void saveTemplate()} disabled={saving || !templateDraft.name.trim() || !templateDraft.content.trim()}><Save/>템플릿 저장</button></div></section>
      <section className="crm-compose-side"><div className="admin-panel crm-phone-preview"><span>고객 화면 미리보기</span><div><small>{templateDraft.channel.toUpperCase()} · 브랜디액션</small><p>{(templateDraft.content || "메시지 내용을 입력하면 여기에 표시됩니다.").replaceAll("#{이름}", "리키")}</p>{templateDraft.purpose === "marketing" && templateDraft.channel !== "alimtalk" && <em>(광고) 표시와 무료수신거부 번호는 발송 시 자동 추가됩니다.</em>}</div></div><section className="admin-panel crm-template-library"><header><h2>등록된 템플릿</h2><span>{data.templates.length}개</span></header>{data.templates.map((template) => <article key={template.id} className={campaign.templateId === template.id ? "selected" : ""}><button className="template-select" onClick={() => setCampaign({ ...campaign, templateId: template.id })}><span>{template.channel.toUpperCase()}</span><div><strong>{template.name}</strong><small>{template.purpose === "marketing" ? "마케팅" : "정보성"} · {template.content.slice(0, 54)}</small></div></button><button onClick={() => editTemplate(template)}><Edit3/></button><button onClick={() => void mutate({ action: "deleteTemplate", id: template.id }, "템플릿을 삭제했습니다.")}><Trash2/></button></article>)}</section><button className="admin-primary crm-compose-next" onClick={() => setStep(3)} disabled={!campaign.templateId}>선택한 메시지 검토하기<ChevronRight/></button></section>
    </div>}

    {step === 3 && <div className="crm-review-workspace">
      <section className="admin-panel crm-send-review"><header><span>FINAL CHECK</span><h2>발송 전 마지막 확인</h2><p>대상, 동의 여부, 휴대폰 정보와 메시지 내용을 다시 확인합니다.</p></header><div className="crm-review-grid"><article><Users/><span>발송 대상</span><strong>{selectedTag?.name || "전체 수신 동의 회원"}</strong><em>{eligible.length}명 발송 가능</em></article><article><MessageSquareText/><span>메시지</span><strong>{selectedTemplate?.name || "선택 필요"}</strong><em>{selectedTemplate?.channel.toUpperCase()} · {selectedTemplate?.purpose === "marketing" ? "마케팅" : "정보성"}</em></article><article><Megaphone/><span>발송 시스템</span><strong>{data.solapiConfigured ? "SOLAPI 연결 완료" : "환경변수 미설정"}</strong><em>{data.solapiConfigured ? "실제 발송 가능" : "임시 저장만 가능"}</em></article></div><label className="campaign-name-field">캠페인 이름<input value={campaign.name} onChange={(event) => setCampaign({ ...campaign, name: event.target.value })} placeholder="예: 8월 무료강의 참여 안내"/></label><div className="crm-final-message"><span>실제 발송 내용</span><p>{selectedTemplate?.content.replaceAll("#{이름}", "회원명") || "메시지 템플릿을 선택해 주세요."}</p></div><div className="crm-exclusion-summary"><AlertTriangle/><div><strong>{targetMembers.length - eligible.length}명은 자동 제외됩니다.</strong><p>마케팅 미동의 {excluded.noConsent}명 · 휴대폰 없음 {excluded.noPhone}명 · 비활성 {excluded.inactive}명</p></div></div><footer><button className="admin-outline" onClick={() => void createCampaign(false)} disabled={!campaign.name.trim() || !campaign.templateId || saving}>임시 저장</button><button className="admin-primary" onClick={() => void createCampaign(true)} disabled={!campaign.name.trim() || !campaign.templateId || !eligible.length || !data.solapiConfigured || saving}><Send/>{saving ? "처리 중..." : `${eligible.length}명에게 실제 발송`}</button></footer>{!data.solapiConfigured && <p className="crm-config-warning">SOLAPI 키·시크릿·발신번호가 없어 실제 발송만 잠겨 있습니다. 태그·템플릿·캠페인 준비는 정상 사용할 수 있습니다.</p>}</section>
      <section className="admin-panel crm-history"><header><div><h2>캠페인 이력</h2><p>저장·발송 결과를 확인하고 실패 건은 다시 실행합니다.</p></div><span>{data.campaigns.length}개</span></header>{data.campaigns.map((item) => <article key={item.id}><span className={`campaign-status ${item.status}`}>{item.status}</span><div><strong>{item.name}</strong><small>{one(item.crm_templates)?.name} · {one(item.crm_tags)?.name || "전체 동의 회원"}</small>{item.error_message && <em>{item.error_message}</em>}</div><span>대상 {item.recipient_count}</span><span>성공 {item.success_count} / 실패 {item.failure_count}</span>{["draft", "failed"].includes(item.status) ? <button onClick={() => void mutate({ action: "sendCampaign", campaignId: item.id }, "메시지 발송 요청을 완료했습니다.")} disabled={!data.solapiConfigured || saving}><Send/>발송</button> : <time>{item.sent_at ? new Intl.DateTimeFormat("ko-KR", { dateStyle: "short", timeStyle: "short" }).format(new Date(item.sent_at)) : "-"}</time>}</article>)}</section>
    </div>}
    {message && <p className="admin-save-success"><Check/>{message}</p>}{error && <p className="admin-save-error" role="alert">{error}</p>}
  </div>;
}
