"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, Clock3, Edit3, Play, Plus, RefreshCw, Save, Trash2, Workflow, X } from "lucide-react";

type Template={id:string;name:string;channel:string;purpose:string;is_active:boolean};
type Tag={id:string;name:string};type Course={id:string;title:string;status:string};
type Automation={id:string;name:string;trigger_type:Trigger;trigger_tag_id:string|null;trigger_course_id:string|null;template_id:string;delay_minutes:number;is_active:boolean;crm_templates:{name:string;channel:string;purpose:string}|Array<{name:string;channel:string;purpose:string}>|null;crm_tags:{name:string}|Array<{name:string}>|null;courses:{title:string}|Array<{title:string}>|null};
type Run={id:string;automation_id:string;status:string;scheduled_for:string;executed_at:string|null;error_message:string|null;created_at:string};
type Trigger="member_joined"|"marketing_consent"|"tag_assigned"|"purchase_completed";
type Data={automations:Automation[];automationRuns:Run[];templates:Template[];tags:Tag[];courses:Course[];solapiConfigured:boolean;engineConfigured:boolean};
type Draft={id?:string;name:string;triggerType:Trigger;triggerTagId:string;triggerCourseId:string;templateId:string;delayValue:string;delayUnit:"minutes"|"hours"|"days";isActive:boolean};
const blank:Draft={name:"",triggerType:"member_joined",triggerTagId:"",triggerCourseId:"",templateId:"",delayValue:"0",delayUnit:"minutes",isActive:false};
const labels:Record<Trigger,{title:string;copy:string}>={member_joined:{title:"회원가입 완료",copy:"신규 회원 프로필이 생성되면 시작"},marketing_consent:{title:"마케팅 수신 동의",copy:"미동의에서 동의로 바뀌면 시작"},tag_assigned:{title:"고객 태그 지정",copy:"선택한 태그가 회원에게 지정되면 시작"},purchase_completed:{title:"결제 완료",copy:"주문이 결제 완료 상태가 되면 시작"}};
const one=<T,>(value:T|T[]|null)=>Array.isArray(value)?value[0]||null:value;
const minutes=(draft:Draft)=>Math.max(0,Number(draft.delayValue)||0)*(draft.delayUnit==="days"?1440:draft.delayUnit==="hours"?60:1);
const delayLabel=(value:number)=>value>=1440&&value%1440===0?`${value/1440}일 후`:value>=60&&value%60===0?`${value/60}시간 후`:value?`${value}분 후`:"즉시";
async function request(body?:Record<string,unknown>){const response=await fetch("/api/admin/crm",body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"CRM 자동화 요청을 처리하지 못했습니다.");return data}

export function AdminCrmAutomationManager(){
  const [data,setData]=useState<Data>({automations:[],automationRuns:[],templates:[],tags:[],courses:[],solapiConfigured:false,engineConfigured:false});
  const [draft,setDraft]=useState<Draft>(blank);const [modal,setModal]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
  const load=async()=>{const result=await request() as Data;setData(result);setLoading(false)};
  useEffect(()=>{let active=true;request().then(result=>{if(active)setData(result as Data)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"자동화 데이터를 불러오지 못했습니다.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const runs=useMemo(()=>new Map(data.automations.map(item=>[item.id,data.automationRuns.filter(run=>run.automation_id===item.id)])),[data.automations,data.automationRuns]);
  const openNew=()=>{setDraft(blank);setError("");setModal(true)};
  const edit=(item:Automation)=>{const delayUnit=item.delay_minutes>=1440&&item.delay_minutes%1440===0?"days":item.delay_minutes>=60&&item.delay_minutes%60===0?"hours":"minutes";const divisor=delayUnit==="days"?1440:delayUnit==="hours"?60:1;setDraft({id:item.id,name:item.name,triggerType:item.trigger_type,triggerTagId:item.trigger_tag_id||"",triggerCourseId:item.trigger_course_id||"",templateId:item.template_id,delayValue:String(item.delay_minutes/divisor),delayUnit,isActive:item.is_active});setModal(true)};
  const mutate=async(body:Record<string,unknown>,success:string)=>{setSaving(true);setError("");setMessage("");try{const result=await request(body);setMessage(success);await load();return result}catch(reason){setError(reason instanceof Error?reason.message:"자동화를 저장하지 못했습니다.");return null}finally{setSaving(false)}};
  const save=async(event:FormEvent)=>{event.preventDefault();const result=await mutate({action:"saveAutomation",id:draft.id,name:draft.name,triggerType:draft.triggerType,triggerTagId:draft.triggerTagId||null,triggerCourseId:draft.triggerCourseId||null,templateId:draft.templateId,delayMinutes:minutes(draft),isActive:draft.isActive},draft.id?"자동화 규칙을 수정했습니다.":"자동화 규칙을 만들었습니다.");if(result){setModal(false);setDraft(blank)}};
  const toggle=async(item:Automation)=>{if(!item.is_active&&!window.confirm("자동화를 활성화하면 다음 조건 발생부터 실제 발송 대기열에 등록됩니다. 활성화할까요?"))return;await mutate({action:"toggleAutomation",id:item.id,isActive:!item.is_active},item.is_active?"자동화를 일시중지했습니다.":"자동화를 활성화했습니다.")};
  const remove=async(item:Automation)=>{if(!window.confirm(`‘${item.name}’ 자동화를 삭제할까요?`))return;await mutate({action:"deleteAutomation",id:item.id},"자동화를 삭제했습니다.")};
  if(loading)return <section className="admin-panel admin-loading-state"><RefreshCw className="spin"/><strong>자동화 엔진을 불러오는 중입니다.</strong></section>;
  const completed=data.automationRuns.filter(run=>run.status==="completed").length;const pending=data.automationRuns.filter(run=>["pending","processing","accepted"].includes(run.status)).length;const failed=data.automationRuns.filter(run=>["failed","skipped"].includes(run.status)).length;
  return <div className="crm-automation-page">
    <section className="crm-automation-kpis"><article><Workflow/><span>활성 자동화<strong>{data.automations.filter(item=>item.is_active).length}개</strong></span></article><article><Clock3/><span>발송 대기<strong>{pending}건</strong></span></article><article><Activity/><span>완료<strong>{completed}건</strong></span></article><article className={failed?"warning":""}><X/><span>실패·제외<strong>{failed}건</strong></span></article></section>
    <section className="admin-panel crm-automation-list"><header><div><span>AUTOMATION ENGINE</span><h2>고객 행동 기반 자동화</h2><p>조건이 발생하면 대기 시간을 계산하고 수신 자격을 다시 확인한 뒤 솔라피로 발송합니다.</p></div><div><button className="admin-outline" onClick={()=>void mutate({action:"runEngine"},"대기 중인 작업을 확인했습니다.")} disabled={saving||!data.solapiConfigured}><Play/>지금 엔진 실행</button><button className="admin-primary" onClick={openNew}><Plus/>자동화 만들기</button></div></header>
      {!data.engineConfigured&&<p className="crm-engine-notice">CRON_SECRET이 아직 설정되지 않아 자동 실행이 잠겨 있습니다. 현재는 ‘지금 엔진 실행’으로 DEV 테스트할 수 있습니다.</p>}
      {data.automations.map(item=>{const itemRuns=runs.get(item.id)||[];const template=one(item.crm_templates);return <article key={item.id} className={item.is_active?"active":"paused"}><div className="automation-state"><i/><span>{item.is_active?"실행 중":"일시중지"}</span></div><div className="automation-flow"><span><small>WHEN</small><strong>{labels[item.trigger_type].title}</strong><em>{one(item.crm_tags)?.name||one(item.courses)?.title||labels[item.trigger_type].copy}</em></span><b>→</b><span><small>WAIT</small><strong>{delayLabel(item.delay_minutes)}</strong><em>예약 큐에서 대기</em></span><b>→</b><span><small>SEND</small><strong>{template?.name||"템플릿 없음"}</strong><em>{template?.channel.toUpperCase()} · {template?.purpose==="marketing"?"수신 동의 확인":"정보성"}</em></span></div><div className="automation-result"><strong>{itemRuns.filter(run=>run.status==="completed").length}건 완료</strong><small>대기 {itemRuns.filter(run=>["pending","processing","accepted"].includes(run.status)).length} · 실패/제외 {itemRuns.filter(run=>["failed","skipped"].includes(run.status)).length}</small></div><div className="automation-actions"><button onClick={()=>void toggle(item)}>{item.is_active?"일시중지":"활성화"}</button><button onClick={()=>edit(item)} aria-label="수정"><Edit3/></button><button onClick={()=>void remove(item)} aria-label="삭제"><Trash2/></button></div></article>})}
      {!data.automations.length&&<div className="coupon-empty"><Workflow/><strong>등록된 자동화가 없습니다.</strong><p>회원가입이나 태그 지정 이후 반복하는 안내부터 자동화해 보세요.</p><button className="admin-primary" onClick={openNew}><Plus/>첫 자동화 만들기</button></div>}
    </section>
    {message&&<p className="admin-save-success">{message}</p>}{!modal&&error&&<p className="admin-save-error">{error}</p>}
    {modal&&<div className="coupon-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setModal(false)}}><form className="admin-panel crm-automation-modal" onSubmit={save}><header><div><span>AUTOMATION BUILDER</span><h2>{draft.id?"자동화 수정":"새 자동화 만들기"}</h2><p>활성화 전 조건과 발송 대상을 충분히 테스트하세요.</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></header><div className="crm-automation-form"><label>자동화 이름<input value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})} placeholder="무료 클래스 신청 후 안내" required/></label><label>시작 조건<select value={draft.triggerType} onChange={event=>setDraft({...draft,triggerType:event.target.value as Trigger,triggerTagId:"",triggerCourseId:""})}>{Object.entries(labels).map(([id,value])=><option value={id} key={id}>{value.title}</option>)}</select><small>{labels[draft.triggerType].copy}</small></label>{draft.triggerType==="tag_assigned"&&<label>기준 태그<select value={draft.triggerTagId} onChange={event=>setDraft({...draft,triggerTagId:event.target.value})} required><option value="">태그 선택</option>{data.tags.map(tag=><option value={tag.id} key={tag.id}>{tag.name}</option>)}</select></label>}{draft.triggerType==="purchase_completed"&&<label>기준 상품 <small>선택하지 않으면 전체 상품</small><select value={draft.triggerCourseId} onChange={event=>setDraft({...draft,triggerCourseId:event.target.value})}><option value="">전체 상품</option>{data.courses.map(course=><option value={course.id} key={course.id}>{course.title}</option>)}</select></label>}<div className="automation-delay"><label>대기 시간<input type="number" min="0" value={draft.delayValue} onChange={event=>setDraft({...draft,delayValue:event.target.value})}/></label><label>단위<select value={draft.delayUnit} onChange={event=>setDraft({...draft,delayUnit:event.target.value as Draft["delayUnit"]})}><option value="minutes">분</option><option value="hours">시간</option><option value="days">일</option></select></label></div><label>발송 템플릿<select value={draft.templateId} onChange={event=>setDraft({...draft,templateId:event.target.value})} required><option value="">템플릿 선택</option>{data.templates.filter(template=>template.is_active).map(template=><option value={template.id} key={template.id}>{template.name} · {template.channel.toUpperCase()}</option>)}</select></label><label className="coupon-active"><input type="checkbox" checked={draft.isActive} onChange={event=>setDraft({...draft,isActive:event.target.checked})}/>저장 즉시 자동화 활성화</label>{error&&<p className="admin-save-error">{error}</p>}</div><footer><button type="button" className="admin-outline" onClick={()=>setModal(false)}>취소</button><button className="admin-primary" disabled={saving}><Save/>{saving?"저장 중...":"자동화 저장"}</button></footer></form></div>}
  </div>;
}
