"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowUp, BookOpen, Check, ChevronDown, ChevronRight, Copy, FileText, GripVertical, Link2, Pencil, Plus, Trash2, Video, X } from "lucide-react";
import type { CurriculumLesson, CurriculumWeek } from "@/app/data";
import { RESOURCE_MAX_BYTES, resourceMime, validateCurriculum } from "@/lib/course-content";
import type { QuizDefinition } from "@/lib/mission-quiz";

const kinds = { VOD: Video, 자료: FileText, 텍스트: BookOpen, 링크: Link2 };
const steps = ["기본 정보", "콘텐츠", "확인 퀴즈", "공개 설정", "검토"];
function move<T>(items: T[], from: number, to: number) {
  if (from < 0 || to < 0 || from >= items.length || to >= items.length) return items;
  const next = [...items]; next.splice(to, 0, next.splice(from, 1)[0]); return next;
}
type Props = {
  weeks: CurriculumWeek[];
  onChange: (weeks: CurriculumWeek[]) => void;
  onResource: (id: string, file: File | null) => void;
  resources: Map<string, File>;
  courseId: string;
  slug: string;
  busy: boolean;
};

export function CurriculumEditor({ weeks, onChange, onResource, resources, courseId, slug, busy }: Props) {
  const [collapsed, setCollapsed] = useState<string[]>([]);
  const [editing, setEditing] = useState<{ weekId: string; lesson: CurriculumLesson; isNew: boolean } | null>(null);
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState("");
  const changeWeek = (id: string, patch: Partial<CurriculumWeek>) => onChange(weeks.map((w) => w.id === id ? { ...w, ...patch } : w));
  const count = weeks.reduce((n, w) => n + w.lessons.length, 0);
  const free = weeks.reduce((n, w) => n + w.lessons.filter((l) => l.accessMode === "member").length, 0);
  const add = (weekId: string) => setEditing({ weekId, isNew: true, lesson: { id: crypto.randomUUID(), day: 0, title: "", description: "", kind: "VOD", duration: "", isPublished: false, accessMode: "enrolled" } });
  return <div className="content-studio">
    <section className="content-offer-note"><div><span className="studio-eyebrow">콘텐츠 운영</span><h2>배우고, 실행하고, 완주하는 클래스</h2><p>섹션 {weeks.length}개 · 콘텐츠 {count}개 · 가입 회원 무료 {free}개</p></div><button type="button" className="admin-primary" disabled={busy || weeks.length >= 52} onClick={() => onChange([...weeks, { id: crypto.randomUUID(), label: "", title: `섹션 ${weeks.length + 1}`, goal: "", isPublished: true, lessons: [] }])}><Plus/>섹션 추가</button></section>
    <div className="studio-flow" aria-label="미션 완료 절차"><span>미션 수행</span><ChevronRight/><span>퀴즈 통과</span><ChevronRight/><span>관리자 승인</span><ChevronRight/><strong>달성도 반영</strong></div>
    <p className="studio-help">퀴즈는 과제별로 선택할 수 있습니다. 주차 자동 잠금 없이 공개한 순서로 제공하며, 필수 과제의 승인만 달성도에 반영합니다.</p>
    {free > 0 && <section className="studio-free-link"><div><strong>광고에 연결할 무료 콘텐츠 페이지</strong><code>/resources/{slug}</code><small>클래스·섹션·콘텐츠를 공개하고 저장하면, 가입 회원이 무료 콘텐츠를 받을 수 있습니다. 마케팅 수신 동의는 별도입니다.</small></div><button className="admin-outline" type="button" onClick={async () => { try { await navigator.clipboard.writeText(`${window.location.origin}/resources/${slug}`); setCopied(true); setCopyError(""); } catch { setCopyError("주소를 직접 복사해 주세요."); } }}><Copy/>{copied ? "주소 복사됨" : "주소 복사"}</button>{copyError && <p role="status">{copyError}</p>}</section>}
    {!weeks.length && <section className="studio-empty"><BookOpen/><h3>첫 섹션을 만들어 보세요</h3><p>Week 1, Part 1 등 운영 방식에 맞게 이름을 정하고 영상·자료·미션을 추가합니다.</p></section>}
    {weeks.map((week, wi) => <section className="studio-section" key={week.id}>
      <header><span className="studio-drag" draggable={!busy} onDragStart={(e) => e.dataTransfer.setData("application/x-brandy-section", String(wi))} aria-label="섹션 순서 드래그"><GripVertical/></span><div className="studio-section-title" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); const raw = e.dataTransfer.getData("application/x-brandy-section"); if (raw !== "" && !busy) onChange(move(weeks, Number(raw), wi)); }}><label><span className="studio-eyebrow">SECTION {String(wi + 1).padStart(2, "0")}</span><input aria-label={`${wi + 1}번째 섹션 제목`} value={week.title} maxLength={200} onChange={(e) => changeWeek(week.id, { title: e.target.value })}/></label><input aria-label={`${week.title} 학습 목표`} placeholder="이 섹션의 학습 목표 (선택)" value={week.goal} maxLength={2000} onChange={(e) => changeWeek(week.id, { goal: e.target.value })}/></div>
        <span className="studio-badge">{week.lessons.length}개</span><label className="studio-check"><input type="checkbox" checked={week.isPublished !== false} onChange={(e) => changeWeek(week.id, { isPublished: e.target.checked })}/>공개</label>
        <div className="studio-icon-actions"><button aria-label={`${week.title} 위로 이동`} disabled={busy || wi === 0} onClick={() => onChange(move(weeks, wi, wi - 1))}><ArrowUp/></button><button aria-label={`${week.title} 아래로 이동`} disabled={busy || wi === weeks.length - 1} onClick={() => onChange(move(weeks, wi, wi + 1))}><ArrowDown/></button><button aria-label={`${week.title} 삭제`} disabled={busy} onClick={() => { if (window.confirm("이 섹션과 콘텐츠를 삭제 목록에 넣을까요? 이용 기록이 있으면 저장 시 삭제가 차단됩니다. 숨기려면 공개를 해제하세요.")) onChange(weeks.filter((w) => w.id !== week.id)); }}><Trash2/></button><button aria-label={`${week.title} ${collapsed.includes(week.id) ? "펼치기" : "접기"}`} aria-expanded={!collapsed.includes(week.id)} onClick={() => setCollapsed(collapsed.includes(week.id) ? collapsed.filter((id) => id !== week.id) : [...collapsed, week.id])}><ChevronDown/></button></div>
      </header>
      {!collapsed.includes(week.id) && <><div className="studio-lesson-list">{week.lessons.map((lesson, li) => {
        const Icon = kinds[lesson.kind];
        return <article key={lesson.id} className="studio-lesson"><Icon/><div><strong>{lesson.title || "제목 미입력"}</strong><small>{lesson.kind} {lesson.duration && `· ${lesson.duration}`} {lesson.mission && `· ${lesson.mission.quiz ? "퀴즈 + 승인" : "과제 승인"}`}</small></div><span className={`studio-badge ${lesson.accessMode === "member" ? "free" : ""}`}>{lesson.accessMode === "member" ? "가입 회원 무료" : "수강생 전용"}</span><span className={`studio-badge ${lesson.isPublished === false || week.isPublished === false ? "" : "live"}`}>{lesson.isPublished === false || week.isPublished === false ? "비공개" : "공개"}</span><div className="studio-icon-actions"><button aria-label={`${lesson.title} 위로 이동`} disabled={busy || li === 0} onClick={() => changeWeek(week.id, { lessons: move(week.lessons, li, li - 1) })}><ArrowUp/></button><button aria-label={`${lesson.title} 아래로 이동`} disabled={busy || li === week.lessons.length - 1} onClick={() => changeWeek(week.id, { lessons: move(week.lessons, li, li + 1) })}><ArrowDown/></button><button aria-label={`${lesson.title} 편집`} disabled={busy} onClick={() => setEditing({ weekId: week.id, lesson: structuredClone(lesson), isNew: false })}><Pencil/></button><button aria-label={`${lesson.title} 삭제`} disabled={busy} onClick={() => { if (window.confirm("콘텐츠를 삭제 목록에 넣을까요? 이력이 있으면 비공개로 전환해 주세요.")) { changeWeek(week.id, { lessons: week.lessons.filter((l) => l.id !== lesson.id) }); onResource(lesson.id, null); } }}><Trash2/></button></div></article>;
      })}</div><button className="studio-add-content" disabled={busy} onClick={() => add(week.id)}><Plus/>콘텐츠 추가</button></>}
    </section>)}
    <p className="studio-help">변경사항은 상단의 ‘변경 저장’을 눌러야 반영됩니다. 진도·제출·자료 이용 기록이 있는 콘텐츠는 삭제할 수 없습니다.</p>
    {editing && <ContentDialog key={editing.lesson.id} {...editing} courseId={courseId} initialFile={resources.get(editing.lesson.id)} onClose={() => setEditing(null)} onApply={(lesson, file) => { const week = weeks.find((w) => w.id === editing.weekId); if (!week) return; changeWeek(week.id, { lessons: editing.isNew ? [...week.lessons, lesson] : week.lessons.map((l) => l.id === lesson.id ? lesson : l) }); onResource(lesson.id, file || null); setEditing(null); }}/>}
  </div>;
}

function ContentDialog({ lesson, isNew, courseId, initialFile, onClose, onApply }: { lesson: CurriculumLesson; isNew: boolean; courseId: string; initialFile?: File; onClose: () => void; onApply: (lesson: CurriculumLesson, file?: File) => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [draft, setDraft] = useState(lesson);
  const [file, setFile] = useState(initialFile);
  const [step, setStep] = useState(0);
  const [error, setError] = useState("");
  useEffect(() => { const node = dialog.current; node?.showModal(); return () => node?.close(); }, []);
  const patch = (value: Partial<CurriculumLesson>) => setDraft((current) => ({ ...current, ...value }));
  const missionPatch = (value: Partial<NonNullable<CurriculumLesson["mission"]>>) => setDraft((current) => ({ ...current, mission: current.mission ? { ...current.mission, ...value } : undefined }));
  const check = (value = draft) => validateCurriculum([{ id: "validation-section", label: "", title: "섹션", goal: "", lessons: [value] }], courseId);
  const finish = (published: boolean) => { const next = { ...draft, isPublished: published }; const invalid = check(next); if (invalid) { setError(invalid); return; } onApply(next, draft.kind === "자료" ? file : undefined); };
  const show = (s: number) => !isNew || step === s;
  return <dialog ref={dialog} className="studio-dialog" onCancel={(e) => { e.preventDefault(); onClose(); }} aria-labelledby="content-editor-title">
    <header><div><span className="studio-eyebrow">{isNew ? "NEW CONTENT" : "EDIT CONTENT"}</span><h2 id="content-editor-title">{isNew ? "콘텐츠 등록" : "콘텐츠 편집"}</h2></div><button aria-label="편집 닫기" onClick={onClose}><X/></button></header>
    {isNew && <ol className="studio-stepper">{steps.map((title, i) => <li key={title} className={i === step ? "current" : i < step ? "done" : ""} aria-current={i === step ? "step" : undefined}><span>{i < step ? <Check/> : i + 1}</span>{title}</li>)}</ol>}
    <div className="studio-dialog-body">
      {show(0) && <section><h3>1. 기본 정보</h3><label>콘텐츠 제목<input autoFocus value={draft.title} maxLength={200} onChange={(e) => patch({ title: e.target.value })} placeholder="교육생에게 표시할 제목"/></label><div className="studio-fields"><label>콘텐츠 형식<select value={draft.kind} onChange={(e) => patch({ kind: e.target.value as CurriculumLesson["kind"] })}>{Object.keys(kinds).map((kind) => <option key={kind}>{kind}</option>)}</select></label><label>분량 표기 (선택)<input value={draft.duration} maxLength={100} placeholder="예: 15분 / PDF 12쪽" onChange={(e) => patch({ duration: e.target.value })}/></label></div><label>짧은 안내<textarea value={draft.description} maxLength={2000} onChange={(e) => patch({ description: e.target.value })}/></label></section>}
      {show(1) && <section><h3>2. 콘텐츠</h3>{draft.kind === "자료" ? <label className="studio-upload">자료 파일 <span>PDF·문서·이미지·ZIP, 최대 50MB</span><input type="file" accept=".pdf,.zip,.txt,.csv,.jpg,.jpeg,.png,.hwp,.xls,.xlsx,.doc,.docx,.ppt,.pptx" onChange={(e) => { const selected = e.target.files?.[0]; e.target.value = ""; if (!selected) return; if (!resourceMime(selected.name) || selected.size > RESOURCE_MAX_BYTES || selected.size <= 0) { setError("지원되는 파일을 50MB 이하로 선택해 주세요."); return; } setFile(selected); patch({ resourceName: selected.name, resourcePath: undefined }); setError(""); }}/><strong>{file?.name || draft.resourceName || "파일 미선택"}</strong>{(file || draft.resourceName) && <button type="button" className="admin-outline" onClick={() => { setFile(undefined); patch({ resourceName: undefined, resourcePath: undefined }); }}>첨부 해제</button>}</label> : draft.kind === "텍스트" ? <label>본문<textarea className="studio-body-text" value={draft.bodyText || ""} onChange={(e) => patch({ bodyText: e.target.value })} maxLength={50000} placeholder="학습 안내, 워크시트, 이벤트 안내 등 (일반 텍스트)"/></label> : <label>{draft.kind === "VOD" ? "영상 링크 (YouTube·Vimeo 등)" : "외부 콘텐츠 링크"}<input type="url" value={draft.contentUrl || ""} onChange={(e) => patch({ contentUrl: e.target.value })} placeholder="https://" maxLength={2048}/><small>영상 파일 직접 업로드 대신 HTTPS 영상 주소를 등록합니다.</small></label>}</section>}
      {show(2) && <section><h3>3. 과제·확인 퀴즈</h3><label className="studio-check"><input type="checkbox" checked={Boolean(draft.mission)} onChange={(e) => patch({ mission: e.target.checked ? { title: draft.title ? `${draft.title} 실행 미션` : "실행 미션", instructions: "", required: true, submissionType: "quiz", isPublished: true, quiz: { questions: [{ id: crypto.randomUUID(), prompt: "", options: ["", ""], correctIndex: 0 }], passPercent: 100 } } : undefined })}/>이 콘텐츠에 실행 미션 연결</label>{draft.mission && <div className="studio-mission"><label>미션 제목<input value={draft.mission.title} maxLength={200} onChange={(e) => missionPatch({ title: e.target.value })}/></label><label>수행 방법과 승인 기준<textarea value={draft.mission.instructions} maxLength={10000} onChange={(e) => missionPatch({ instructions: e.target.value })}/></label><div className="studio-fields"><label>제출 방식<select value={draft.mission.submissionType} onChange={(e) => missionPatch({ submissionType: e.target.value as NonNullable<CurriculumLesson["mission"]>["submissionType"] })}><option value="quiz">퀴즈만 응시</option><option value="text">텍스트 제출</option><option value="link">링크 제출</option><option value="mixed">텍스트 또는 링크</option></select></label><label className="studio-check"><input type="checkbox" checked={draft.mission.required} onChange={(e) => missionPatch({ required: e.target.checked })}/>필수 미션 (달성도 반영)</label></div><label className="studio-check"><input type="checkbox" checked={Boolean(draft.mission.quiz)} onChange={(e) => missionPatch({ quiz: e.target.checked ? { questions: [{ id: crypto.randomUUID(), prompt: "", options: ["", ""], correctIndex: 0 }], passPercent: 100 } : undefined })}/>확인 퀴즈 사용</label>{draft.mission.quiz && <QuizBuilder quiz={draft.mission.quiz} onChange={(quiz) => missionPatch({ quiz })}/>}<p className="studio-help">퀴즈를 사용하면 통과 후 승인 대기에 들어갑니다. 오답은 재응시, 관리자 반려는 보완 후 재제출할 수 있습니다. 가입 회원 무료 콘텐츠에 연결한 미션도 참여하려면 해당 클래스 수강권이 필요합니다.</p></div>}</section>}
      {show(3) && <section><h3>4. 공개 설정</h3><label>콘텐츠를 볼 수 있는 대상<select value={draft.accessMode || "enrolled"} onChange={(e) => patch({ accessMode: e.target.value as "enrolled" | "member" })}><option value="enrolled">수강생 전용 · 활성 수강권 필요</option><option value="member">가입 회원 무료 · 광고 유입용</option></select></label><p className="studio-help">가입 회원 무료로 지정해도 비로그인 방문자에게는 제목·안내만 공개합니다. 파일·본문·실제 링크는 로그인과 공개 상태를 확인한 뒤 제공합니다.</p>{draft.mission && <label className="studio-check"><input type="checkbox" checked={draft.mission.isPublished} onChange={(e) => missionPatch({ isPublished: e.target.checked })}/>연결 미션 공개</label>}</section>}
      {show(4) && <section><h3>5. 최종 확인</h3><dl className="studio-review"><div><dt>제목</dt><dd>{draft.title || "미입력"}</dd></div><div><dt>형식</dt><dd>{draft.kind}</dd></div><div><dt>접근 권한</dt><dd>{draft.accessMode === "member" ? "가입 회원 무료" : "수강생 전용"}</dd></div><div><dt>완료 조건</dt><dd>{draft.mission ? `${draft.mission.quiz ? `퀴즈 ${draft.mission.quiz.passPercent}% 이상 + ` : ""}관리자 승인` : "콘텐츠 열람 (미션 없음)"}</dd></div></dl><p className="studio-help">아래 버튼은 편집 목록에 반영합니다. 실제 사이트에는 클래스 상단의 ‘변경 저장’을 눌러야 반영됩니다.</p></section>}
      {error && <p className="admin-save-error" role="alert">{error}</p>}
    </div>
    <footer><button type="button" className="admin-outline" onClick={isNew && step > 0 ? () => { setStep(step - 1); setError(""); } : onClose}>{isNew && step > 0 ? "이전" : "취소"}</button>{isNew && step < 4 ? <button className="admin-primary" onClick={() => { if (step === 0 && !draft.title.trim()) { setError("콘텐츠 제목을 입력해 주세요."); return; } setStep(step + 1); setError(""); dialog.current?.querySelector(".studio-dialog-body")?.scrollTo(0, 0); }}>다음<ChevronRight/></button> : <div><button className="admin-outline" onClick={() => finish(false)}>비공개로 {isNew ? "추가" : "반영"}</button><button className="admin-primary" onClick={() => finish(true)}><Check/>{isNew ? "추가·공개" : "반영·공개"}</button></div>}</footer>
  </dialog>;
}

function QuizBuilder({ quiz, onChange }: { quiz: QuizDefinition; onChange: (quiz: QuizDefinition) => void }) {
  const update = (index: number, patch: Partial<QuizDefinition["questions"][number]>) => onChange({ ...quiz, questions: quiz.questions.map((q, i) => i === index ? { ...q, ...patch } : q) });
  return <div className="studio-quiz"><label>통과 기준 (%)<input type="number" min={1} max={100} value={quiz.passPercent} onChange={(e) => onChange({ ...quiz, passPercent: Number(e.target.value) })}/><small>100%는 전 문항 정답입니다. 한 문항당 정답 1개를 선택하세요.</small></label>{quiz.questions.map((q, qi) => <fieldset key={q.id}><legend>문항 {qi + 1}</legend><label>질문<input value={q.prompt} maxLength={1000} onChange={(e) => update(qi, { prompt: e.target.value })}/></label>{q.options.map((option, oi) => <div className="studio-quiz-option" key={oi}><input type="radio" name={`correct-${q.id}`} checked={q.correctIndex === oi} aria-label={`${qi + 1}번 문항 ${oi + 1}번 선택지를 정답으로`} onChange={() => update(qi, { correctIndex: oi })}/><input aria-label={`${qi + 1}번 문항 선택지 ${oi + 1}`} value={option} maxLength={500} placeholder={`선택지 ${oi + 1}`} onChange={(e) => update(qi, { options: q.options.map((o, i) => i === oi ? e.target.value : o) })}/><button type="button" aria-label={`선택지 ${oi + 1} 삭제`} disabled={q.options.length <= 2} onClick={() => update(qi, { options: q.options.filter((_, i) => i !== oi), correctIndex: q.correctIndex === oi ? 0 : q.correctIndex > oi ? q.correctIndex - 1 : q.correctIndex })}><X/></button></div>)}<div className="studio-quiz-actions"><button className="admin-outline" disabled={q.options.length >= 6} onClick={() => update(qi, { options: [...q.options, ""] })}><Plus/>선택지</button><button className="admin-outline" disabled={quiz.questions.length <= 1} onClick={() => onChange({ ...quiz, questions: quiz.questions.filter((_, i) => i !== qi) })}><Trash2/>문항 삭제</button></div></fieldset>)}<button className="admin-outline" disabled={quiz.questions.length >= 20} onClick={() => onChange({ ...quiz, questions: [...quiz.questions, { id: crypto.randomUUID(), prompt: "", options: ["", ""], correctIndex: 0 }] })}><Plus/>문항 추가</button></div>;
}
