import test from 'node:test';import assert from 'node:assert/strict';import ts from 'typescript';import {readFileSync} from 'node:fs';
const audience = {};
new Function('exports','process',ts.transpileModule(readFileSync(new URL('../lib/diagnosis-audience.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(audience,{env:{}});
const user='00000000-0000-4000-8000-000000000001',course='00000000-0000-4000-8000-000000000002';
function fixture({enabled=true,actor={id:user,role:'admin'},error=null}={}) {
 const calls=[],route={};
 const mocks={'@/lib/diagnosis-audience':audience,'@/lib/server-auth':{getAuthenticatedUser:async()=>actor},'@/lib/supabase/admin':{createAdminClient:()=>({rpc:async(n,a)=>{calls.push([n,a]);return {data:{state:'preparing'},error};}})},'@/lib/edu-workflows':{uuid:v=>typeof v==='string'&&/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(v)}};
 new Function('exports','require','process',ts.transpileModule(readFileSync(new URL('../app/api/platform/diagnosis/route.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(route,n=>mocks[n],{env:{EDU_MYIN_DIAGNOSIS_ENABLED:enabled?'true':'false'}});
 return {route,calls,post:(body={courseId:course},origin='https://edu.test')=>route.POST(new Request('https://edu.test/api/platform/diagnosis',{method:'POST',headers:origin?{origin}:{},body:JSON.stringify(body)}))};
}
test('diagnosis rollout is closed by default and requires a verified login',async()=>{const h=fixture({enabled:false});assert.equal((await h.route.GET()).status,404);assert.equal((await h.post()).status,404);assert.equal(h.calls.length,0);const out=fixture({actor:null});assert.equal((await out.route.GET()).status,401);assert.equal((await out.post()).status,401);});
test('caller cannot choose another actor or bypass origin checks',async()=>{const h=fixture();for(const origin of [null,'https://attacker.test'])assert.equal((await h.post(undefined,origin)).status,403);assert.equal((await h.post({courseId:course,userId:course})).status,400);assert.equal(h.calls.length,0);});
test('owned reads and start pass only the server identity and are private',async()=>{const h=fixture();const r=await h.post();assert.equal(r.status,202);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.deepEqual(h.calls[0],['edu_diagnosis_begin',{p_actor:user,p_course:course}]);await h.route.GET();assert.deepEqual(h.calls[1],['edu_diagnosis_read',{p_actor:user}]);});
test('invalid and oversized bodies fail before storage; internal errors are redacted',async()=>{const h=fixture();for(const body of [null,[],{courseId:'bad'},{courseId:course,padding:'한'.repeat(1000)}])assert.equal((await h.post(body)).status,400);assert.equal(h.calls.length,0);const bad=fixture({error:{message:'private raw answers secret'}});const r=await bad.route.GET();assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/raw answers|secret/);const denied=fixture({error:{message:'DIAGNOSIS_FORBIDDEN'}});assert.equal((await denied.post()).status,403);});

test('student and staff cannot read or begin even when feature flags are enabled',async()=>{for(const role of ['student','staff',undefined]){const h=fixture({actor:{id:user,role}});assert.equal((await h.route.GET()).status,403);assert.equal((await h.post()).status,403);assert.equal(h.calls.length,0);}});
