import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{createRequire}from'node:module';import ts from'typescript';
const req=createRequire(import.meta.url),modules=new Map();function load(name){if(modules.has(name))return modules.get(name);const e={};modules.set(name,e);new Function('exports','require',ts.transpileModule(readFileSync(new URL('../lib/'+name+'.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(e,n=>n.startsWith('./')?load(n.slice(2)):req(n));return e;}
const {runDiagnosisAdmin}=load('diagnosis-admin-service'),{validateAdminReportRows,sendAdminDiagnosis,adminDiagnosisHeaders}=load('diagnosis-admin-bridge');
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor={id:id(99)},binding={subject:id(1),attemptId:id(2),responseId:id(3),releaseId:id(4),packageVersion:'v1'},version='a'.repeat(64);
const report={...binding,state:'needs_review',updatedAt:'2026-10-03T00:00:00Z',errorCode:'JOB_DEADLINE_REACHED',canRetry:true,version,details:[{code:'JOB_DEADLINE_REACHED',at:'2026-10-03T00:00:00Z'}]};
test('recorded timeline is allowlisted, timezone-qualified and never substituted with observation time',async()=>{
 const times={startedAt:'2026-10-04T11:24:00Z',submittedAt:'2026-10-04T23:30:00Z',issuedAt:'2026-10-05T00:40:00Z'};
 const h=fixture();h.send=async()=>({version:1,rows:[{...report,...times,state:'ready',canRetry:false}]});
 const list=await runDiagnosisAdmin(h,{action:'list'});
 for(const [key,value] of Object.entries(times))assert.equal(list.rows[0].report[key],value);
 assert.notEqual(list.rows[0].report.issuedAt,list.rows[0].report.checkedAt);
 const old=validateAdminReportRows({version:1,rows:[report]},[binding])[0];assert.equal(old.submittedAt,null);assert.equal(old.issuedAt,null);
 for(const patch of [{submittedAt:'2026-10-05'},{issuedAt:'invalid'},{issuedAt:times.issuedAt}])assert.throws(()=>validateAdminReportRows({version:1,rows:[{...report,...patch}]},[binding]));
});
function fixture({outage=false,forbidden=false}={}){let receipt=null;const calls=[],sends=[];return{calls,sends,actor,rpc:async(name,a)=>{calls.push([name,a]);assert.equal(a.p_actor,actor.id);if(forbidden)return{error:{message:'DIAGNOSIS_FORBIDDEN'}};if(name==='edu_diagnosis_admin_list')return{data:{enabled:true,allPublished:false,revision:0,eligibleCount:1,startedCount:1,nextCursor:null,rows:[{id:binding.subject,name:'학생 A',published:false,attemptId:binding.attemptId,state:'submitted',binding,report:{...report,checkedAt:report.updatedAt}}]}};if(name==='edu_diagnosis_admin_context')return{data:binding};if(name==='edu_diagnosis_admin_retry_receipt'){if(a.p_result)receipt=a.p_result;return{data:receipt};}return{data:null};},send:async input=>{sends.push(input);if(outage)throw Error('private provider key');return input.action==='status'?{version:1,rows:[{...report,rawAnswers:'private'}]}:{state:'queued',attemptId:binding.attemptId,responseId:binding.responseId,requestId:input.requestId,acceptedAt:report.updatedAt};}};}
test('admin list validates bound status and strips remote identity, raw answers and provider extras',async()=>{const h=fixture(),list=await runDiagnosisAdmin(h,{action:'list'});assert.equal(list.rows[0].report.canRetry,true);assert.doesNotMatch(JSON.stringify(list),/rawAnswers|binding|releaseId|responseId|subject/);assert.equal(h.calls.at(-1)[0],'edu_diagnosis_assert_admin');assert.equal(h.calls.find(c=>c[0]==='edu_diagnosis_admin_observe')[1].p_rows[0].rawAnswers,undefined);});
test('temporary remote outage marks saved observation stale and forbids retry; local permissions fail closed',async()=>{const h=fixture({outage:true}),list=await runDiagnosisAdmin(h,{action:'list'});assert.equal(list.remoteAvailable,false);assert.equal(list.rows[0].statusAvailable,false);assert.equal(list.rows[0].report.canRetry,false);assert.equal(h.calls.some(c=>c[0]==='edu_diagnosis_admin_observe'),false);await assert.rejects(runDiagnosisAdmin(fixture({forbidden:true}),{action:'list'}),e=>e.code==='FORBIDDEN');});
test('retry uses server-owned binding and an auditable idempotent receipt, without starting a new survey',async()=>{const h=fixture(),input={action:'retry',requestId:id(88),attemptId:binding.attemptId,expectedVersion:version};const receipt=await runDiagnosisAdmin(h,input);assert.equal(receipt.state,'queued');assert.deepEqual(await runDiagnosisAdmin(h,input),receipt);assert.equal(h.sends.length,1);assert.deepEqual(h.sends[0].binding,binding);assert.equal(h.calls.some(c=>/begin|restart/.test(c[0])),false);});
test('100-row batches reject duplicate, missing, foreign and malformed report bindings',()=>{const bindings=Array.from({length:100},(_,n)=>({...binding,attemptId:id(n+1000)})),rows=bindings.map(b=>({...report,...b}));assert.equal(validateAdminReportRows({version:1,rows},bindings).length,100);for(const patch of[{subject:id(9)},{responseId:id(9)},{packageVersion:'foreign'},{state:'ready',canRetry:true},{details:[{at:report.updatedAt,code:'raw secrets'}]}])assert.throws(()=>validateAdminReportRows({version:1,rows:[{...report,...patch}]},[binding]));assert.throws(()=>validateAdminReportRows({version:1,rows:[report,report]},[binding,{...binding,attemptId:id(10)}]));});
test('management transport stays pinned to environment with its own HMAC domain and bounded private response',async()=>{const env={NEXT_PUBLIC_APP_ENV:'dev',EDU_MYIN_BRIDGE_ENVIRONMENT:'dev',EDU_MYIN_BRIDGE_ORIGIN:'https://dev-server.myinlab.co.kr',EDU_MYIN_BRIDGE_SECRET:'11'.repeat(32)};let calls=0;const fetcher=async(url,o)=>{calls++;assert.equal(url,env.EDU_MYIN_BRIDGE_ORIGIN+'/api/integrations/edu/diagnosis/manage');assert.equal(o.redirect,'error');assert.equal(o.cache,'no-store');return Response.json({version:1,rows:[]});};await sendAdminDiagnosis({action:'status',actorId:actor.id,bindings:[]},{env,fetcher});for(const patch of[{NEXT_PUBLIC_APP_ENV:'production'},{EDU_MYIN_BRIDGE_ORIGIN:'https://foreign.test'},{EDU_MYIN_BRIDGE_SECRET:'bad'}])await assert.rejects(sendAdminDiagnosis({},{env:{...env,...patch},fetcher}));assert.equal(calls,1);assert.notEqual(adminDiagnosisHeaders('{}',env.EDU_MYIN_BRIDGE_SECRET,'dev','1790838000').Authorization,load('diagnosis-bridge').diagnosisBridgeHeaders('{}',env.EDU_MYIN_BRIDGE_SECRET,'dev','1790838000').Authorization);});
function routeFixture(user=actor){const e={},calls=[];new Function('exports','require','process',ts.transpileModule(readFileSync(new URL('../app/api/admin/diagnosis/route.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(e,n=>({'@/lib/server-auth':{getAuthenticatedUser:async()=>user},'@/lib/supabase/admin':{createAdminClient:()=>({})},'@/lib/edu-workflows':{uuid:v=>typeof v==='string'&&/^00000000-0000-4000-8000-\d{12}$/.test(v)},'@/lib/diagnosis-bridge':load('diagnosis-bridge'),'@/lib/diagnosis-admin-bridge':{},'@/lib/diagnosis-admin-service':{runDiagnosisAdmin:async(d,input)=>{calls.push({actor:d.actor,input});return{};}}})[n],{env:{EDU_MYIN_DIAGNOSIS_ENABLED:'true'}});return{calls,get:()=>e.GET(new Request('https://edu.test/api/admin/diagnosis')),post:(body,origin='https://edu.test')=>e.POST(new Request('https://edu.test/api/admin/diagnosis',{method:'POST',headers:origin?{origin}:{},body:JSON.stringify(body)}))};}
test('admin API rejects staff, browser actor spoofing, foreign origin and malformed changes before side effects',async()=>{for(const role of['staff','student']){const h=routeFixture({...actor,role});assert.equal((await h.get()).status,403);assert.equal(h.calls.length,0);}const h=routeFixture({...actor,role:'admin'}),body={action:'publish_all',requestId:id(80),enabled:true,revision:0};for(const origin of[null,'https://attacker.test'])assert.equal((await h.post(body,origin)).status,403);for(const bad of[{...body,actorId:id(8)},{...body,enabled:'true'},{...body,revision:-1},{...body,action:'publish_member'}])assert.equal((await h.post(bad)).status,400);assert.equal(h.calls.length,0);assert.equal((await h.post(body)).status,200);assert.equal(h.calls[0].actor.id,actor.id);});
test('queue snapshot survives the service allowlist and invalid or partial positions fail closed',async()=>{
 const queue={queuePosition:3,queuedAt:'2026-10-06T01:00:00Z',queueObservedAt:'2026-10-06T02:00:00Z'};
 const h=fixture();h.send=async()=>({version:1,rows:[{...report,state:'queued',canRetry:false,...queue}]});
 const list=await runDiagnosisAdmin(h,{action:'list'});for(const[k,v]of Object.entries(queue))assert.equal(list.rows[0].report[k],v);
 for(const patch of[{queuePosition:0},{queuePosition:1.5},{queuedAt:null},{queueObservedAt:'2026-10-06'},{queuePosition:'3'}])assert.throws(()=>validateAdminReportRows({version:1,rows:[{...report,...queue,...patch}]},[binding]));
 assert.equal(validateAdminReportRows({version:1,rows:[report]},[binding])[0].queuePosition,null);
});
test('rewrite forwards an explicit mode and replays same request after remote acceptance loses its response',async()=>{
 const h=fixture(),send=h.send;let remoteCalls=0,accepted;
 h.send=async i=>{remoteCalls++;if(!accepted){accepted=await send(i);throw new Error('response lost after acceptance');}assert.equal(i.requestId,accepted.requestId);return accepted;};
 const input={action:'retry',requestId:id(88),attemptId:binding.attemptId,expectedVersion:version,retryMode:'rewrite'};
 await assert.rejects(runDiagnosisAdmin(h,input));assert.deepEqual(await runDiagnosisAdmin(h,input),accepted);await runDiagnosisAdmin(h,input);
 assert.equal(remoteCalls,2);assert.equal(h.sends.length,1);assert.equal(h.sends[0].retryMode,'rewrite');assert.equal(h.sends[0].expectedVersion,version);
});
test('admin member deep link uses exact lookup; malformed member and retry mode rejected before service',async()=>{
 const h=fixture();const rpc=h.rpc;h.rpc=(n,a)=>rpc(n==='edu_diagnosis_admin_member'?'edu_diagnosis_admin_list':n,a);
 await runDiagnosisAdmin(h,{action:'list',member:binding.subject});assert.equal(h.calls[0][1].p_member,binding.subject);assert.equal(h.calls[0][1].p_query,undefined);
 const r=routeFixture({...actor,role:'admin'});
 assert.equal((await r.post({action:'retry',requestId:id(88),attemptId:id(2),expectedVersion:version,retryMode:'force'})).status,400);
 assert.equal((await r.post({action:'retry',requestId:id(88),attemptId:id(2),expectedVersion:version,retryMode:'rewrite'})).status,202);
});
