import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
function load(file,mocks={}) {const exports={};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('exports','require',code)(exports,name=>{if(mocks[name])return mocks[name];throw Error('Unexpected dependency '+name);});return exports;}
const logic=load('lib/landing.ts');
const id='aaaaaaaa-aaaa-4000-8000-000000000001';
const packet={landing_id:id,session_id:id,visitor_id:id,layout_ver:1,attribution:{utm_source:'meta',utm_content:'%ED%95%9C%EA%B8%80+%26+ad',email:'never-store',referrer:'https://ref.example/path?email=secret'},events:[{id,event_type:'click_cta',payload:{to:'sticky_cta',section:'proof',scrollPct:47,password:'never-store'}}]};
test('landing first-touch parsing preserves raw UTM and decodes labels safely',()=>{const a=logic.rawAttribution('?utm_content=%ED%95%9C%EA%B8%80+%26+ad&utm_content=overwrite&email=x','https://ref.example/path?secret=1');assert.equal(a.utm_content,'%ED%95%9C%EA%B8%80+%26+ad');assert.equal(logic.decodeLabel(a.utm_content),'한글 & ad');assert.equal(logic.decodeLabel('%broken'),'%broken');assert.equal(a.referrer,'https://ref.example');assert.equal(a.email,undefined);});
test('KST range includes midnight on the intended local date',()=>{assert.deepEqual(logic.reportRange('2026-09-14','2026-09-28'),{start:'2026-09-13T15:00:00.000Z',end:'2026-09-28T15:00:00.000Z'});assert.equal(logic.kstDate('2026-09-13T15:01:00Z'),'2026-09-14');assert.throws(()=>logic.reportRange('2026-02-31','2026-03-03'));});
test('landing settings reject unsafe URLs, duplicate IDs, and invalid thresholds',()=>{const cfg=logic.defaultConfig(id);assert.equal(logic.validateConfig(cfg).thresholds.cta_rate_min,null);assert.throws(()=>logic.validateConfig({...cfg,kakao_url:'https://open.kakao.com.attacker.example/o/a'}));assert.throws(()=>logic.validateConfig({...cfg,pixel_enabled:true}));assert.throws(()=>logic.validateConfig({...cfg,sections:[{id:'same'},{id:'same'}]}));assert.throws(()=>logic.validateConfig({...cfg,thresholds:{...cfg.thresholds,min_sessions:-1}}));assert.deepEqual(logic.sectionOrder({...cfg,custom_sections:true,sections:[{id:'new-name'},{id:'another'}]}),['hero','new-name','another','final']);});
test('event allowlist excludes personal fields and bounds malicious payloads',()=>{const clean=logic.validatePacket(packet);assert.equal(clean.attribution.email,undefined);assert.equal(clean.attribution.referrer,'https://ref.example');assert.equal(clean.events[0].payload.password,undefined);assert.throws(()=>logic.validatePacket({...packet,events:[{...packet.events[0],payload:{to:'sticky_cta',scrollPct:Infinity}}]}));assert.throws(()=>logic.validatePacket({...packet,layout_ver:0}));assert.throws(()=>logic.validatePacket({...packet,events:Array(31).fill(packet.events[0])}));});
test('test-mode cookie blocks event writes at server before parsing payload',async()=>{let called=0;const route=load('app/api/landing/events/route.ts',{'@/lib/landing':logic,'@/lib/supabase/admin':{createAdminClient:()=>{called++;throw Error('must not write');}}});const req=new Request('https://dev.example/api/landing/events',{method:'POST',headers:{origin:'https://dev.example',cookie:'other=x; edu_landing_test=1'},body:'bad-json'});assert.equal((await route.POST(req)).status,204);assert.equal(called,0);assert.equal(logic.isTestRequest('edu_landing_test=10'),false);});
test('event ingestion rejects cross-origin and uses server RPC for valid events',async()=>{const calls=[];const route=load('app/api/landing/events/route.ts',{'@/lib/landing':logic,'@/lib/supabase/admin':{createAdminClient:()=>({rpc:async(...args)=>{calls.push(args);return {error:null};}})}});const req=origin=>new Request('https://dev.example/api/landing/events',{method:'POST',headers:{origin},body:JSON.stringify(packet)});assert.equal((await route.POST(req('https://other.example'))).status,403);assert.equal(calls.length,0);assert.equal((await route.POST(req('https://dev.example'))).status,204);assert.equal(calls[0][0],'edu_ingest_landing');});
test('admin landing reads and writes require marketing permission and same origin',async()=>{const mocks={'@/lib/landing':logic,'@/lib/operator-permissions':{getOperatorUser:async()=>null},'@/lib/supabase/admin':{createAdminClient:()=>{throw Error('DB accessed without permission');}}};const route=load('app/api/landing/admin/route.ts',mocks);assert.equal((await route.GET(new Request('https://dev.example/api/landing/admin'))).status,403);assert.equal((await route.POST(new Request('https://dev.example/api/landing/admin',{method:'POST',headers:{origin:'https://dev.example'},body:'{}'}))).status,403);mocks['@/lib/operator-permissions'].getOperatorUser=async()=>({id});assert.equal((await route.POST(new Request('https://dev.example/api/landing/admin',{method:'POST',headers:{origin:'https://evil.example'},body:'{}'}))).status,403);});
test('manual actuals preserve missing values, zero and cumulative semantics',()=>{assert.deepEqual(logic.validateActuals({day:'2026-09-28',joins:0,exits:null,live_peak:'',payments:2}),{day:'2026-09-28',joins:0,exits:null,live_peak:null,payments:2});assert.throws(()=>logic.validateActuals({day:'2026-09-28',joins:-1}));assert.throws(()=>logic.validateMeta({day:'2026-09-28',campaign:'x',adset:'',creative:'x'}));});
