import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import ts from 'typescript';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

const require=createRequire(import.meta.url);
function load(file,mocks={}){const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const exports={};new Function('exports','require',code)(exports,name=>{if(name in mocks)return mocks[name];if(name.endsWith('.css'))return{};if(name.startsWith('@/')||name.startsWith('.')){const base=name.startsWith('@/')?name.slice(2):path.join(path.dirname(file),name);return load(['.ts','.tsx'].map(ext=>base+ext).find(value=>fs.existsSync(value)),mocks);}return require(name);});return exports;}
const logic=load('lib/landing-performance.ts');
const campaign={id:'bbbbbbbb-bbbb-4000-8000-000000000002',landing_id:'aaaaaaaa-aaaa-4000-8000-000000000001',name:'9월 캠페인',utm_campaign:'september',start_day:'2026-09-01',end_day:'2026-09-30',new_customer_price:1650000,existing_customer_price:1100000,live_peak:null,meta_ad_account_id:null,meta_campaign_id:null,meta_sync_status:'not_configured',meta_last_synced_at:null,meta_sync_error:null};
const summary={has_data:true,sessions:5,visitors:4,cta_click_sessions:2,cta_clicks:17,converted_visitors:2,avg_dwell_ms:12000,avg_scroll_depth:67,meta_impressions:1000,meta_link_clicks:30,spend:100000};
const report={campaign,summary_b:summary,summary_a:{...summary,sessions:0,visitors:0,cta_click_sessions:0,cta_clicks:0,converted_visitors:0,has_data:false},performance:[{campaign:'september',adset:'cold%20one',creative:'image%201',ad_type:'unclassified',sessions:5,visitors:4,cta_click_sessions:2,cta_clicks:17,avg_scroll_depth:67,avg_dwell_ms:12000,impressions:1000,link_clicks:30,spend:100000}],daily:[{day:'2026-09-14',sessions:5,visitors:4,cta_click_sessions:2,cta_clicks:17}],actuals:[],campaign_summary:{live_peak:300,kakao_members:450,kakao_delta:12,new_payments:2,existing_payments:1,revenue:4400000,spend:100000,roas:4400},options:{campaigns:['september'],ad_types:['unclassified'],adsets:['cold%20one'],creatives:['image%201'],devices:['mobile'],layouts:[1]},data_state:{sessions_exist:true,filtered_sessions_exist:true,meta_exists:true},range:{startDay:'2026-09-08',endDay:'2026-09-14',compareStartDay:'2026-09-01',compareEndDay:'2026-09-07'}};

test('KST presets, campaign bounds and equal-length comparison are deterministic',()=>{const now=new Date('2026-09-13T15:01:00Z');assert.deepEqual(logic.presetRange('today',campaign,now),{startDay:'2026-09-14',endDay:'2026-09-14'});assert.deepEqual(logic.presetRange('yesterday',campaign,now),{startDay:'2026-09-13',endDay:'2026-09-13'});assert.deepEqual(logic.presetRange('7d',campaign,now),{startDay:'2026-09-08',endDay:'2026-09-14'});assert.deepEqual(logic.campaignRange({startDay:'2026-09-01',endDay:'2026-09-14'},{start_day:'2026-09-14',end_day:'2026-09-28'}),{startDay:'2026-09-14',endDay:'2026-09-14'});assert.deepEqual(logic.previousRange('2026-09-08','2026-09-14'),{startDay:'2026-09-01',endDay:'2026-09-07'});assert.equal(logic.validateDashboardRange('2026-09-01','2026-09-30',campaign).length,30);assert.throws(()=>logic.validateDashboardRange('2026-08-31','2026-09-30',campaign));assert.throws(()=>logic.validateDashboardRange('2026-09-20','2026-09-10',campaign));});
test('partial actual parsing preserves blank, distinguishes zero and explicit clears',()=>{assert.deepEqual(logic.parsePartialActual({day:'2026-09-14',kakao_members:'',new_payments:'0',existing_payments:2,memo:'',clear:['kakao_members']}),{day:'2026-09-14',values:{new_payments:0,existing_payments:2},clear:['kakao_members']});assert.throws(()=>logic.parsePartialActual({day:'bad',new_payments:1}));assert.throws(()=>logic.parsePartialActual({day:'2026-09-14',new_payments:-1}));});
test('visitor and session conversions stay separate and unknown comparison is explicit',()=>{assert.equal(logic.rate(summary.converted_visitors,summary.visitors),50);assert.equal(logic.rate(summary.cta_click_sessions,summary.sessions),40);assert.equal(logic.delta(3,0,true).rate,null);assert.equal(logic.delta(3,0,false),null);assert.equal(logic.displayDimension('cold%20one'),'cold one');});
test('dashboard replaces fixed eight KPIs with ordered funnel and retains decoded detailed metrics',()=>{const {PerformanceDashboard}=load('app/ui/landing/performance-dashboard.tsx');const html=renderToStaticMarkup(React.createElement(PerformanceDashboard,{report,compare:true,onClassify:async()=>true}));for(const text of ['1. 방문','2. CTA 클릭','3. 카카오톡방','4. 결제','고유 방문자','방문자 CTA 전환율','방문 → CTA 40.0%','CTA 클릭 세션','CTA 클릭 횟수','누적 매출','ROAS','Meta 노출','Meta 링크 클릭','Meta CTR','cold one','image 1','비교 못함'])assert.ok(html.includes(text),text);assert.equal((html.match(/class="admin-metric"/g)||[]).length,12);assert.match(html,/<details class="tracking-metric-details">/);assert.doesNotMatch(html,/NaN|Infinity/);assert.ok(html.indexOf('소재별 성과')<html.indexOf('일별 방문·전환 추이'));});
test('admin preserves compact controls, integrated actuals and settings drawer',()=>{const source=['admin.tsx','tracking-controls.tsx','tracking-operations.tsx'].map(file=>fs.readFileSync('app/ui/landing/'+file,'utf8')).join('\n');for(const text of ['오늘','어제','7일','14일','캠페인 전체','비교 모드','상세 필터','CSV 내보내기','빈칸은 기존값을 유지','부분 저장','Meta 재동기화','history.replaceState','Meta 광고계정 ID','광고 세팅 후 캠페인 ID 입력','실측 데이터','일별 실측 기록','AdminDrawer','값 비우기'])assert.ok(source.includes(text),text);assert.doesNotMatch(source,/selectedOptions|select multiple|Ctrl 또는 Command|role="tablist"|role="tabpanel"/);assert.match(source,/name="meta_ad_account_id"/);const common=fs.readFileSync('app/ui/final/admin-system.tsx','utf8');assert.match(common,/dialog\.current|node\.showModal\(\)/);const styles=fs.readFileSync('app/ui/landing/tracking-admin.css','utf8');assert.match(styles,/\.tracking-options/);assert.match(styles,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);});
test('migration is additive, audited, RLS locked and snapshots prices',()=>{const sql=fs.readFileSync('supabase/migrations/20260914124755_free_class_marketing_dashboard.sql','utf8');for(const text of ['create table public.landing_campaigns','create table public.landing_campaign_actuals','create table public.landing_campaign_actual_audit','create table public.landing_campaign_meta_daily','enable row level security','revoke all','new_price_snapshot','existing_price_snapshot','edu_upsert_campaign_actual','edu_marketing_dashboard','edu_marketing_export'])assert.ok(sql.toLowerCase().includes(text.toLowerCase()),text);assert.doesNotMatch(sql,/drop table|truncate /i);});
test('Meta connector requires server-only token/version and preserves rows on failure',()=>{const source=fs.readFileSync('app/api/landing/performance/meta/route.ts','utf8');assert.match(source,/process\.env\.META_ACCESS_TOKEN/);assert.match(source,/process\.env\.META_GRAPH_API_VERSION/);assert.match(source,/기존 실적은 보존/);assert.doesNotMatch(source,/NEXT_PUBLIC_META|delete\(\).*landing_campaign_meta_daily/);});
test('common Meta account stays private and is the server source of truth',()=>{const sql=fs.readFileSync('supabase/migrations/20260914142335_common_meta_ad_account.sql','utf8');const api=fs.readFileSync('app/api/landing/performance/route.ts','utf8');assert.match(sql,/edu_meta_marketing/);assert.match(sql,/is_public[^\n]*false/i);assert.match(api,/commonMetaAccountId/);assert.match(api,/const account = await commonMetaAccountId\(db\)/);});
