import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import ts from 'typescript';
function load(name) {
  const exports = {};
  new Function('exports', 'require', ts.transpileModule(fs.readFileSync(new URL(`../lib/${name}.ts`, import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText)(exports, request => load(request.replace('./', '')));
  return exports;
}
const tools = load('lesson-guided-tools'), contract = load('lesson-blocks');
// These hashes and question fixtures were generated by evaluating the original
// Replit functions, not by the new implementation. Source hashes are included.
const golden = JSON.parse(fs.readFileSync(new URL('./fixtures/lesson-guided-golden.json', import.meta.url), 'utf8'));
const hash = text => createHash('sha256').update(text).digest('hex');

test('preserves all original question text, options, placeholders, order and full persona prompt', () => {
  assert.deepEqual(tools.PERSONA_QUESTIONS, golden.personaQuestions);
  assert.deepEqual(tools.LANDING_QUESTIONS, golden.landingQuestions);
  assert.equal(hash(tools.buildPersonaPrompt(golden.persona.answers)), golden.persona.promptSha256);
  assert.match(tools.buildPersonaPrompt(golden.persona.answers), /\$& \{고객\}/);
  assert.deepEqual(tools.personaIdentity({ age:'30대', gender:'여성 위주' }), { name:'지은 씨 (32세)', emoji:'👩' });
  assert.equal(tools.personaIdentity({ age:'10대', gender:'비슷비슷' }).name, '우리 핵심 고객');
});
for (const fixture of golden.landing) test(`preserves original ${fixture.name} branch, conversion event and complete prompt`, () => {
  assert.deepEqual(tools.Q4_1_MAP[fixture.name], fixture.branch);
  const prompt = tools.buildLandingPrompt(fixture.answers);
  assert.equal(hash(prompt), fixture.promptSha256);
  assert.ok(prompt.includes(`전환 이벤트 이름은 ${fixture.event}`));
  assert.ok(prompt.includes('$& {원문}\n둘째 줄'));
});

for (const type of ['persona-generator', 'landing-planner']) test(`${type} stores partial answers against fixed version and forbids modified question definitions`, () => {
  const block = tools.newGuidedBlock(type, 'tool'), doc = {schemaVersion:1,blocks:[block],checklist:[]};
  assert.deepEqual(contract.validateLessonBlocks(doc),doc);
  assert.equal(tools.hasGuidedDefinition(contract.publicLessonBlocks(doc).blocks[0]),true);
  assert.equal(tools.firstMissingGuidedAnswer(type,{}),0);
  const field=block.fields[0], draft={blocks:{tool:{[field.id]:field.options?.[0]||'첫 답변'}},checklist:[]};
  assert.deepEqual(contract.validateBlockAnswers(draft,doc),draft);
  assert.equal(tools.firstMissingGuidedAnswer(type,draft.blocks.tool),1);
  const all=type==='persona-generator'?golden.persona.answers:golden.landing[0].answers;
  assert.equal(tools.firstMissingGuidedAnswer(type,all),-1);
  for(const mutate of [b=>delete b.toolVersion,b=>b.toolVersion='future',b=>b.fields.reverse(),b=>b.fields[0].label='다른 질문',b=>b.fields[0].required=false,b=>b.fields[0].sensitive=true]) {
    const changed=structuredClone(doc);mutate(changed.blocks[0]);
    assert.equal(tools.hasGuidedDefinition(changed.blocks[0]),false);
    assert.throws(()=>contract.validateLessonBlocks(changed));
  }
  assert.throws(()=>contract.validateBlockAnswers({blocks:{tool:{unknown:'답변'}},checklist:[]},doc));
  const choice=block.fields.find(f=>f.options);
  assert.throws(()=>contract.validateBlockAnswers({blocks:{tool:{[choice.id]:'알 수 없는 선택'}},checklist:[]},doc));
  assert.throws(()=>contract.validateBlockAnswers({blocks:{tool:{[field.id]:'x'.repeat(20001)}},checklist:[]},doc));
});
