'use client';
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDown, ArrowUp, Plus, Trash2, RefreshCw, ExternalLink } from 'lucide-react';
import { defaultConfig, decodeLabel, kstDate, sectionOrder, type LandingConfig, type Thresholds } from '@/lib/landing';
import { UploadField } from '../editor-fields';
import { LandingDashboard, type Report } from './dashboard';
import { LiveSetup } from './live-setup';
type Course = { id: string; title: string; slug: string; status: string; metadata?: Record<string, unknown> };
async function api(body: Record<string, unknown>) {
 const r=await fetch('/api/landing/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}), v=await r.json();
 if(!r.ok)throw Error(v.error || '저장에 실패했습니다.'); return v;
}
export function LandingAdmin() {
 const [courses,setCourses]=useState<Course[]>([]),[configs,setConfigs]=useState<LandingConfig[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0),[saved,setSaved]=useState('');
 useEffect(()=>{const c=new AbortController();fetch('/api/landing/admin',{signal:c.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw Error(v.error);setCourses(v.courses);setConfigs(v.configs);const requested=new URLSearchParams(location.search).get('course');setSelected(id=>id || v.courses.find((course:Course)=>course.id===requested)?.id || v.configs[0]?.id || v.courses[0]?.id || '');setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[retry]);
 const course=courses.find(c=>c.id===selected), initial=configs.find(c=>c.id===selected) || defaultConfig(selected);
 return <div className="landing-admin"><div className="landing-toolbar"><label>대상 무료클래스<select value={selected} onChange={e=>{setSelected(e.target.value);setSaved('');}}>{courses.map(c=><option key={c.id} value={c.id}>{c.title}{c.status!=='published'?' · 미공개':''}</option>)}</select></label><button className="btn" onClick={()=>setRetry(x=>x+1)}><RefreshCw size={16}/>새로 불러오기</button>{course && <a className="btn" href={'/classes/'+course.slug+'?testmode=1'} target="_blank" rel="noreferrer">테스트 화면<ExternalLink size={16}/></a>}</div>{error && <p className="notice" role="alert">{error}</p>}{saved && <p className="notice" role="status">{saved}</p>}{loading && <p role="status">랜딩 설정을 불러오는 중입니다.</p>}{!loading && !course && !error && <p className="notice">상품 관리에서 무료클래스를 먼저 등록해 주세요.</p>}{course && <><LiveSetup key={'live:'+selected+':'+initial.revision+':'+retry} course={course} initial={initial} onSaved={(config,image)=>{setConfigs(all=>[config,...all.filter(c=>c.id!==config.id)]);setCourses(all=>all.map(c=>c.id===config.id?{...c,metadata:{...c.metadata,detail_image_url:image,detailImageUrl:undefined}}:c));setSaved('CTA와 상세 이미지를 함께 저장·발행했습니다. 반영 화면에서 확인해 주세요.');}}/><details className="landing-advanced"><summary>고급 설정 · Pixel / 성과 분석 / 맞춤 섹션</summary><LandingWorkspace key={selected+':'+initial.revision} course={course} initial={initial} onSaved={config=>setConfigs(all=>[config,...all.filter(c=>c.id!==config.id)])}/></details></>}</div>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
const thresholds: [keyof Thresholds,string,number,number][] = [['min_sessions','판정 최소 세션 수',1,1000000],['min_clicks','위너 후보 최소 CTA 클릭 수',1,1000000],['cta_rate_min','CTA 클릭률 하한 (%) · 미설정 가능',0,100],['meta_ctr_min','Meta 링크 CTR 하한 (%)',0,100],['alive_seconds','이동 실패 의심 대기 시간 (초)',1,60],['gap_percent','링크클릭 대비 세션 갭 경고 (%)',0,100]];
function LandingWorkspace({course,initial,onSaved}:{course:Course;initial:LandingConfig;onSaved:(c:LandingConfig)=>void}) {
 const [tab,setTab]=useState(initial.revision?'report':'settings'),[config,setConfig]=useState(initial),[pending,setPending]=useState(false),[message,setMessage]=useState(''),[note,setNote]=useState(''),[report,setReport]=useState<Report | null>(null),[reload,setReload]=useState(0);
 const [filters,setFilters]=useState({start:initial.campaign_start,end:initial.campaign_end,campaign:'',adset:'',creative:'',traffic:''});
 const [reportError,setReportError]=useState(''),[reportLoading,setReportLoading]=useState(false);const busy=useRef(false);
 const query=new URLSearchParams({landing:course.id,...filters}).toString();
 useEffect(()=>{if(!initial.revision)return;const c=new AbortController(),timer=setTimeout(()=>setReportLoading(true),0);fetch('/api/landing/admin?'+query,{signal:c.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw Error(v.error);setReport(v);setReportError('');}).catch(e=>{if(e.name!=='AbortError')setReportError(e.message);}).finally(()=>{if(!c.signal.aborted)setReportLoading(false);});return()=>{clearTimeout(timer);c.abort();};},[query,reload,initial.revision]);
 async function save(body:Record<string,unknown>) {if(busy.current)return;busy.current=true;setPending(true);setMessage('');try{const v=await api(body);setMessage('저장했습니다.');setReload(x=>x+1);return v;}catch(e){setMessage(e instanceof Error?e.message:'저장하지 못했습니다.');}finally{busy.current=false;setPending(false);}}
 async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const sections=config.sections.map((s,i)=>{let image=String(form.get('section-image-'+i) || s.image);if(image&&!/^(https?:\/\/|\/)/.test(image))image=process.env.NEXT_PUBLIC_SUPABASE_URL+'/storage/v1/object/public/course-assets/'+image;return {...s,image};});const result=await save({action:'publish',config:{...config,sections},note});if(result)onSaved(result.config);}
 const options=report?.options || [];
 const values=(key:'campaign'|'adset'|'creative')=>Array.from(new Set(options.filter(o=>(!filters.campaign||o.campaign===filters.campaign)&&(!filters.adset||key==='adset'||o.adset===filters.adset)).map(o=>o[key]))).filter(Boolean);
 function move(index:number,delta:number){setConfig(c=>{const sections=[...c.sections];[sections[index],sections[index+delta]]=[sections[index+delta],sections[index]];return {...c,sections};});}
 return <><nav className="landing-tabs" aria-label="랜딩 관리">{[['report','성과 분석'],['settings','랜딩·Pixel 설정'],['actuals','실측·광고 수치'],['versions','발행 이력']].map(([key,label])=><button key={key} className={'btn '+(tab===key?'dark':'')} onClick={()=>setTab(key)}>{label}</button>)}</nav>{message && <p className="notice" role="status">{message}</p>}
 {!initial.revision && <p className="notice">랜딩·Pixel 설정에서 대상 클래스와 참여 주소를 저장·발행하면 수집을 시작합니다.</p>}{initial.revision>0 && !initial.kakao_url && <p className="notice">카카오 오픈채팅 주소를 입력하면 캠페인 랜딩과 CTA 추적이 활성화됩니다.</p>}
 {tab==='settings' && <form onSubmit={publish} className="landing-panel"><h2>랜딩과 Meta Pixel</h2><p className="muted">조회 기간과 무관하게 상시 수집합니다. 선택한 무료클래스에만 적용됩니다.</p><div className="landing-form-grid"><label className="check-row"><input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/>랜딩 추적 사용</label><label className="check-row"><input type="checkbox" checked={config.pixel_enabled} onChange={e=>setConfig({...config,pixel_enabled:e.target.checked})}/>Meta Pixel 사용 · PageView / CompleteRegistration</label><Field label="카카오 오픈채팅 주소"><input type="url" placeholder="https://open.kakao.com/o/..." value={config.kakao_url} onChange={e=>setConfig({...config,kakao_url:e.target.value})}/></Field><Field label="Meta Pixel ID"><input inputMode="numeric" maxLength={30} value={config.pixel_id} onChange={e=>setConfig({...config,pixel_id:e.target.value})}/></Field><Field label="CTA 버튼 문구"><input required maxLength={100} value={config.cta_label} onChange={e=>setConfig({...config,cta_label:e.target.value})}/></Field><div className="landing-date-pair"><Field label="기본 조회 시작 (KST)"><input type="date" required value={config.campaign_start} onChange={e=>setConfig({...config,campaign_start:e.target.value})}/></Field><Field label="기본 조회 종료 (KST)"><input type="date" required value={config.campaign_end} onChange={e=>setConfig({...config,campaign_end:e.target.value})}/></Field></div></div><p className="notice">세 버튼 모두 CompleteRegistration으로 전송합니다. 위치는 content_name, 광고세트는 content_category로 구분됩니다. Meta 이벤트 설정 도구로 버튼 이벤트를 중복 등록하지 마세요.</p>
 <h3>판정 기준</h3><div className="landing-form-grid">{thresholds.map(([key,label,min,max])=><Field key={key} label={label}><input type="number" min={min} max={max} step={['min_sessions','min_clicks'].includes(key)?1:0.1} required={key!=='cta_rate_min'} value={config.thresholds[key]??''} onChange={e=>setConfig({...config,thresholds:{...config.thresholds,[key]:e.target.value===''?null:Number(e.target.value)}})}/></Field>)}</div>
 <h3>랜딩 섹션</h3><label className="check-row"><input type="checkbox" checked={config.custom_sections} onChange={e=>setConfig({...config,custom_sections:e.target.checked})}/>아래 섹션 구성 사용</label><p className="muted">기본은 상품 상세 이미지를 사용합니다. 섹션별 내용을 등록하면 순서와 도달률을 개별 관리할 수 있습니다. 긴 이미지는 화면 높이의 절반이 보일 때 도달로 측정합니다.</p><div className="landing-section-order">{sectionOrder(config).join(' → ')}</div>
 {config.sections.map((s,i)=><fieldset className="landing-section-editor" key={i}><legend>섹션 {i+1}</legend><div className="landing-toolbar"><button type="button" className="btn" disabled={i===0} aria-label={'섹션 '+(i+1)+' 위로'} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button type="button" className="btn" disabled={i===config.sections.length-1} aria-label={'섹션 '+(i+1)+' 아래로'} onClick={()=>move(i,1)}><ArrowDown size={16}/></button><button type="button" className="btn" onClick={()=>setConfig({...config,sections:config.sections.filter((_,n)=>n!==i)})}><Trash2 size={16}/>삭제</button></div><div className="landing-form-grid"><Field label="고유 섹션 ID"><input required pattern="[a-zA-Z0-9_-]{1,60}" value={s.id} onChange={e=>setConfig({...config,sections:config.sections.map((v,n)=>n===i?{...v,id:e.target.value}:v)})}/></Field><Field label="제목"><input maxLength={160} value={s.title} onChange={e=>setConfig({...config,sections:config.sections.map((v,n)=>n===i?{...v,title:e.target.value}:v)})}/></Field></div><Field label="본문"><textarea rows={5} maxLength={20000} value={s.body} onChange={e=>setConfig({...config,sections:config.sections.map((v,n)=>n===i?{...v,body:e.target.value}:v)})}/></Field><Field label="섹션 이미지"><UploadField key={i+':'+s.id+':'+s.image} name={'section-image-'+i} value={s.image} image optimize disabled={pending} onChange={image=>setConfig(c=>({...c,sections:c.sections.map((v,n)=>n===i?{...v,image}:v)}))}/></Field></fieldset>)}
 <button type="button" className="btn" disabled={config.sections.length>=60} onClick={()=>setConfig({...config,sections:[...config.sections,{id:'section-'+crypto.randomUUID().slice(0,8),title:'',body:'',image:''}]})}><Plus size={16}/>섹션 추가</button><Field label="발행 변경 메모"><textarea required maxLength={500} value={note} placeholder="예: hero 카피 교체 / 커리큘럼 순서 이동" onChange={e=>setNote(e.target.value)}/></Field><p className="muted">저장·발행 시 상품의 현재 제목·소개·이미지와 섹션 구성을 함께 기록합니다. 상품 내용 수정 후 이곳에서 다시 발행하면 새 버전으로 비교할 수 있습니다.</p><button className="btn primary" disabled={pending}>{pending?'발행 중…':'저장 & 발행'}</button></form>}
 {tab==='report' && initial.revision>0 && <><div className="landing-filter-grid"><Field label="시작일 (KST)"><input type="date" value={filters.start} onChange={e=>setFilters({...filters,start:e.target.value})}/></Field><Field label="종료일 (KST)"><input type="date" value={filters.end} onChange={e=>setFilters({...filters,end:e.target.value})}/></Field><Field label="유입"><select value={filters.traffic} onChange={e=>setFilters({...filters,traffic:e.target.value})}><option value="">전체</option><option value="meta">Meta 광고</option><option value="direct">직접 유입</option><option value="other">기타 참조</option></select></Field><Field label="캠페인"><select value={filters.campaign} onChange={e=>setFilters({...filters,campaign:e.target.value,adset:'',creative:''})}><option value="">전체 캠페인</option>{Array.from(new Set(options.map(o=>o.campaign))).filter(Boolean).map(v=><option key={v} value={v}>{decodeLabel(v)}</option>)}</select></Field><Field label="광고세트"><select value={filters.adset} onChange={e=>setFilters({...filters,adset:e.target.value,creative:''})}><option value="">전체 광고세트</option>{values('adset').map(v=><option key={v} value={v}>{decodeLabel(v)}</option>)}</select></Field><Field label="소재"><select value={filters.creative} onChange={e=>setFilters({...filters,creative:e.target.value})}><option value="">전체 소재</option>{values('creative').map(v=><option key={v} value={v}>{decodeLabel(v)}</option>)}</select></Field><button className="btn" onClick={()=>setReload(n=>n+1)}><RefreshCw size={16}/>조회</button></div>{reportError?<p role="alert" className="notice">{reportError}</p>:reportLoading?<p role="status">성과 집계를 불러오고 있습니다.</p>:report && <LandingDashboard report={report} traffic={filters.traffic} filtered={!!(filters.campaign||filters.adset||filters.creative||filters.traffic)} />}</>}
 {tab==='actuals' && initial.revision>0 && <ActualForms report={report} id={course.id} pending={pending} save={save}/>}
 {tab==='versions' && <div className="landing-panel"><h2>발행 이력</h2><p className="muted">방문 당시 버전으로 비교합니다. 메모 수정은 구성 버전을 변경하지 않습니다.</p>{report?.snapshots.map(s=><form className="landing-version" key={s.layout_ver} onSubmit={e=>{e.preventDefault();void save({action:'note',landing_id:course.id,version:s.layout_ver,note:new FormData(e.currentTarget).get('note')});}}><h3>v{s.layout_ver} · {new Date(s.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</h3><p>{s.sections.join(' → ')}</p><Field label={'v'+s.layout_ver+' 변경 메모'}><input name="note" defaultValue={s.note} maxLength={500}/></Field><button className="btn" disabled={pending}>메모 저장</button></form>)}</div>}
 </>;
}
function ActualForms({report,id,pending,save}:{report:Report|null;id:string;pending:boolean;save:(b:Record<string,unknown>)=>Promise<unknown>}) {
 const [day,setDay]=useState(kstDate()),[meta,setMeta]=useState({day:kstDate(),campaign:'',adset:'',creative:'',impressions:0,link_clicks:0,spend:0});const [actual,setActual]=useState<Report['actuals'][number]|null>(null),[actualReady,setActualReady]=useState(''),[actualError,setActualError]=useState(''),[actualReload,setActualReload]=useState(0);
 useEffect(()=>{const controller=new AbortController();fetch('/api/landing/admin?'+new URLSearchParams({landing:id,actual_day:day}),{signal:controller.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw Error(v.error);setActual(v.actual);setActualReady(day);setActualError('');}).catch(e=>{if(e.name!=='AbortError'){setActualReady('');setActualError(e.message);}});return()=>controller.abort();},[id,day,actualReload]);
 return <div className="landing-actuals"><form className="landing-panel" key={day+':'+JSON.stringify(actual)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const values:Record<string,unknown>={day};for(const key of ['joins','exits','live_peak','payments'])values[key]=f.get(key)===''?null:Number(f.get(key));void save({action:'actuals',landing_id:id,values}).then(result=>{if(result)setActualReload(n=>n+1);});}}><h2>카카오·라이브·결제 실측</h2><Field label="기준일 (KST)"><input type="date" value={day} required onChange={e=>setDay(e.target.value)}/></Field><div className="landing-form-grid">{[['joins','카카오 누적 입장 인원'],['exits','당일 퇴장 인원'],['live_peak','라이브 최대 동시시청'],['payments','당일 결제 건수']].map(([key,label])=><Field key={key} label={label}><input name={key} type="number" min={0} max={100000000} step={1} defaultValue={actual?.[key]??''}/></Field>)}</div><p className="muted">미확인 값은 비워 두세요. 누적 입장은 마지막 입력값, 퇴장·결제는 기간 합계, 동시시청은 기간 최댓값으로 계산합니다.</p><p className="notice" role="status">{actualError || (actualReady!==day?'해당 날짜의 실측을 불러오는 중입니다.':'해당 날짜의 저장된 값을 수정할 수 있습니다.')}</p><button className="btn primary" disabled={pending||actualReady!==day}>실측 저장</button></form>
 <form className="landing-panel" onSubmit={e=>{e.preventDefault();void save({action:'meta',landing_id:id,values:meta});}}><h2>Meta 광고 실적</h2><p className="muted">광고 관리자 수치를 소재별·날짜별로 입력합니다. 같은 날짜와 소재를 저장하면 수정됩니다. 캠페인·광고세트·소재명은 UTM과 동일하게 입력하세요.</p><div className="landing-form-grid"><Field label="기준일 (KST)"><input type="date" value={meta.day} required onChange={e=>setMeta({...meta,day:e.target.value})}/></Field>{(['campaign','adset','creative'] as const).map((key,i)=><Field key={key} label={['캠페인명','광고세트명','소재명'][i]}><input required maxLength={250} value={meta[key]} onChange={e=>setMeta({...meta,[key]:e.target.value})}/></Field>)}{(['impressions','link_clicks','spend'] as const).map((key,i)=><Field key={key} label={['노출수','링크클릭 수','광고비 (원)'][i]}><input required type="number" min={0} step={1} value={meta[key]} onChange={e=>setMeta({...meta,[key]:Number(e.target.value)})}/></Field>)}</div><button className="btn primary" disabled={pending}>광고 실적 저장</button></form>
 <div className="landing-panel landing-table"><h3>저장된 광고 실적</h3><p className="muted">성과 분석에서 선택한 기간의 기록입니다.</p><table><thead><tr><th>날짜</th><th>캠페인 / 세트 / 소재</th><th>노출</th><th>링크클릭</th><th>수정</th></tr></thead><tbody>{report?.meta.map((m,i)=><tr key={i}><td>{m.day}</td><td>{[m.campaign,m.adset,m.creative].map(decodeLabel).join(' / ')}</td><td>{m.impressions.toLocaleString()}</td><td>{m.link_clicks.toLocaleString()}</td><td><button className="btn" onClick={()=>setMeta({...m,campaign:decodeLabel(m.campaign),adset:decodeLabel(m.adset),creative:decodeLabel(m.creative)})}>불러오기</button></td></tr>)}</tbody></table></div></div>;
}
