'use client';

import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { Download, RefreshCw, RotateCcw, Save } from 'lucide-react';
import { PERFORMANCE_PRESETS, campaignRange, displayDimension, presetRange, previousRange, type DashboardReport, type PerformanceCampaign, type PerformanceCourse, type PerformancePreset, type PerformanceRow } from '@/lib/landing-performance';
import { PerformanceDashboard } from './performance-dashboard';

type Filters = { utm_campaign:string[];ad_type:string[];adset:string[];creative:string[];device:string[];layout:string[] };
const emptyFilters: Filters = { utm_campaign:[],ad_type:[],adset:[],creative:[],device:[],layout:[] };
const labels: Record<string,string> = { today:'오늘',yesterday:'어제','7d':'7일','14d':'14일',campaign:'캠페인 전체' };
const queryFilters = (query: URLSearchParams, filters: Filters) => Object.entries(filters).forEach(([key,values])=>values.forEach(value=>query.append(key,value)));
async function responseJson(response: Response) { const value=await response.json(); if(!response.ok) throw Error(value.error||'요청에 실패했습니다.'); return value; }

export function LandingAdmin() {
  const [courses,setCourses]=useState<PerformanceCourse[]>([]),[courseId,setCourseId]=useState(''),[campaignId,setCampaignId]=useState('');
  const [preset,setPreset]=useState<PerformancePreset>('7d'),[start,setStart]=useState(''),[end,setEnd]=useState('');
  const [compare,setCompare]=useState(false),[compareStart,setCompareStart]=useState(''),[compareEnd,setCompareEnd]=useState('');
  const [filters,setFilters]=useState<Filters>(emptyFilters),[reload,setReload]=useState(0),[pending,setPending]=useState(false);
  const [list,setList]=useState({loading:true,error:'',canManage:false}),[result,setResult]=useState<{key:string;report?:DashboardReport;error?:string}>({key:''});
  const [message,setMessage]=useState('');
  const pendingRef=useRef(false);
  const course=courses.find(value=>value.id===courseId),campaign=course?.campaigns.find(value=>value.id===campaignId);

  useEffect(()=>{const controller=new AbortController();fetch('/api/landing/performance',{cache:'no-store',signal:controller.signal}).then(responseJson).then(value=>{
    if(controller.signal.aborted)return; const items:PerformanceCourse[]=value.courses||[],url=new URLSearchParams(location.search),requestedCourse=url.get('course'),requestedCampaign=url.get('campaign');
    const nextCourse=items.find(item=>item.id===requestedCourse)||items.find(item=>item.status==='published'&&item.tracking==='active')||items[0];
    const nextCampaign=nextCourse?.campaigns.find(item=>item.id===requestedCampaign)||nextCourse?.campaigns[0];
    setCourses(items);setCourseId(nextCourse?.id||'');setCampaignId(nextCampaign?.id||'');setList({loading:false,error:'',canManage:Boolean(value.can_manage_campaign)});
    if(nextCampaign){const urlStart=url.get('start'),urlEnd=url.get('end'),urlPreset=(url.get('preset')||'7d') as PerformancePreset;const range=campaignRange(urlStart&&urlEnd?{startDay:urlStart,endDay:urlEnd}:presetRange(urlPreset,nextCampaign),nextCampaign);setPreset(urlPreset);setStart(range.startDay);setEnd(range.endDay);const enabled=url.get('compare')==='1';setCompare(enabled);if(enabled){const previous=url.get('compare_start')&&url.get('compare_end')?{startDay:url.get('compare_start')!,endDay:url.get('compare_end')!}:previousRange(range.startDay,range.endDay);setCompareStart(previous.startDay);setCompareEnd(previous.endDay);}}
  }).catch(error=>{if(!controller.signal.aborted)setList({loading:false,error:error.message,canManage:false});});return()=>controller.abort();},[reload]);

  const query=useMemo(()=>{if(!courseId||!campaignId||!start||!end)return '';const value=new URLSearchParams({landing:courseId,campaign:campaignId,start,end});if(compare){value.set('compare_start',compareStart);value.set('compare_end',compareEnd);}queryFilters(value,filters);return value.toString();},[courseId,campaignId,start,end,compare,compareStart,compareEnd,filters]);
  const requestKey=query+':'+reload;
  useEffect(()=>{if(!query)return;const controller=new AbortController();fetch('/api/landing/performance?'+query,{cache:'no-store',signal:controller.signal}).then(responseJson).then(value=>{if(!controller.signal.aborted)setResult({key:requestKey,report:value});}).catch(error=>{if(!controller.signal.aborted)setResult({key:requestKey,error:error.message});});return()=>controller.abort();},[query,requestKey]);
  useEffect(()=>{if(!courseId||!campaignId||!start||!end)return;const url=new URL(location.href);url.search='';url.searchParams.set('course',courseId);url.searchParams.set('campaign',campaignId);url.searchParams.set('preset',preset);url.searchParams.set('start',start);url.searchParams.set('end',end);if(compare){url.searchParams.set('compare','1');url.searchParams.set('compare_start',compareStart);url.searchParams.set('compare_end',compareEnd);}queryFilters(url.searchParams,filters);history.replaceState(null,'',url);},[courseId,campaignId,preset,start,end,compare,compareStart,compareEnd,filters]);

  function chooseCourse(id:string){setCourseId(id);const next=courses.find(value=>value.id===id)?.campaigns[0];setCampaignId(next?.id||'');if(next){const range=campaignRange(presetRange('7d',next),next);setStart(range.startDay);setEnd(range.endDay);}setFilters(emptyFilters);}
  function chooseCampaign(id:string){setCampaignId(id);const next=course?.campaigns.find(value=>value.id===id);if(next){const range=campaignRange(presetRange(preset,next),next);setStart(range.startDay);setEnd(range.endDay);}setFilters(emptyFilters);}
  function choosePreset(value:PerformancePreset){if(!campaign)return;const range=campaignRange(presetRange(value,campaign),campaign);setPreset(value);setStart(range.startDay);setEnd(range.endDay);if(compare){const previous=previousRange(range.startDay,range.endDay);setCompareStart(previous.startDay);setCompareEnd(previous.endDay);}}
  function toggleCompare(value:boolean){setCompare(value);if(value&&start&&end){const previous=previousRange(start,end);setCompareStart(previous.startDay);setCompareEnd(previous.endDay);}}
  function comparisonPreset(days:1|7|14){if(!campaign)return;const value=days===1?'today':`${days}d` as '7d'|'14d',range=campaignRange(presetRange(value,campaign),campaign),previous=previousRange(range.startDay,range.endDay);setPreset('custom');setStart(range.startDay);setEnd(range.endDay);setCompare(true);setCompareStart(previous.startDay);setCompareEnd(previous.endDay);}
  function selectFilter(key:keyof Filters,event:React.ChangeEvent<HTMLSelectElement>){setFilters(previous=>({...previous,[key]:Array.from(event.target.selectedOptions).map(option=>option.value)}));}
  async function post(body:Record<string,unknown>,success:string){if(pendingRef.current)return;pendingRef.current=true;setPending(true);setMessage('');try{await responseJson(await fetch('/api/landing/performance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));setMessage(success);setReload(value=>value+1);}catch(error){setMessage((error as Error).message);}finally{pendingRef.current=false;setPending(false);}}
  async function classify(row:PerformanceRow,value:string){await post({action:'classification',campaign_id:campaignId,adset:row.adset,creative:row.creative,ad_type:value},'광고 유형을 저장했습니다.');}
  const fresh=result.key===requestKey,report=fresh?result.report:undefined,error=list.error||(fresh?result.error:'');
  return <div className="landing-admin">
    <div className="toolbar landing-dashboard-toolbar"><div className="landing-class-control"><label htmlFor="landing-course">무료클래스</label><select id="landing-course" value={courseId} onChange={event=>chooseCourse(event.target.value)} disabled={!courses.length}>{!courses.length&&<option value="">등록된 무료클래스 없음</option>}{courses.map(item=><option value={item.id} key={item.id}>{item.title}{item.status==='published'?'':' · 미공개'}</option>)}</select></div><div><label htmlFor="landing-campaign">캠페인</label><select id="landing-campaign" value={campaignId} onChange={event=>chooseCampaign(event.target.value)} disabled={!course?.campaigns.length}>{!course?.campaigns.length&&<option value="">등록된 캠페인 없음</option>}{course?.campaigns.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></div><span className="spacer"/><button type="button" className="btn" onClick={()=>setReload(value=>value+1)}><RefreshCw size={16}/>새로고침</button></div>
    {campaign&&<><div className="tabs landing-periods" role="group" aria-label="조회 기간">{PERFORMANCE_PRESETS.map(value=><button type="button" key={value} className={`tab ${preset===value?'active':''}`} onClick={()=>choosePreset(value)}>{labels[value]}</button>)}<label>시작일<input type="date" min={campaign.start_day} max={campaign.end_day} value={start} onChange={event=>{setPreset('custom');setStart(event.target.value);}}/></label><label>종료일<input type="date" min={campaign.start_day} max={campaign.end_day} value={end} onChange={event=>{setPreset('custom');setEnd(event.target.value);}}/></label></div>
      <section className="panel landing-compare"><label className="check-row"><input type="checkbox" checked={compare} onChange={event=>toggleCompare(event.target.checked)}/>비교 모드</label>{compare&&<><div className="row"><button type="button" className="btn small" onClick={()=>comparisonPreset(1)}>어제 → 오늘</button><button type="button" className="btn small" onClick={()=>comparisonPreset(7)}>직전 7일 → 최근 7일</button><button type="button" className="btn small" onClick={()=>comparisonPreset(14)}>직전 14일 → 최근 14일</button></div><div className="landing-date-pair"><label>A · 예전 기간<input type="date" value={compareStart} onChange={event=>setCompareStart(event.target.value)}/></label><label>A 종료<input type="date" value={compareEnd} onChange={event=>setCompareEnd(event.target.value)}/></label><p className="meta">직접 맞추기 · B {start} — {end}</p></div></>}</section></>}
    {report&&<FilterPanel report={report} filters={filters} onChange={selectFilter} onReset={()=>setFilters(emptyFilters)} exportUrl={`/api/landing/performance/export?${query}`}/>}
    {message&&<p className="notice neutral" role="status">{message}</p>}
    {error?<div className="empty" role="alert"><h3>성과 데이터를 불러오지 못했습니다.</h3><p>{error}</p></div>:list.loading||(!fresh&&campaignId)?<div className="empty" role="status"><p>실제 성과 데이터를 불러오고 있습니다.</p></div>:!campaign?<div className="empty"><h3>등록된 캠페인이 없습니다.</h3><p>무료클래스에 연결된 캠페인 설정이 필요합니다.</p></div>:report&&<PerformanceDashboard report={report} compare={compare} onClassify={classify}/>}
    {campaign&&report&&<div className="two-col landing-operations"><ActualForm campaign={campaign} pending={pending} onSave={(values)=>post({action:'actual',campaign_id:campaign.id,values},'일별 실측값을 저장했습니다.')}/><CampaignForm campaign={campaign} canManage={list.canManage} pending={pending} onSave={(values)=>post({action:'campaign',campaign_id:campaign.id,values},'캠페인 설정을 저장했습니다.')} onSync={async()=>{if(pendingRef.current)return;pendingRef.current=true;setPending(true);setMessage('');try{const value=await responseJson(await fetch('/api/landing/performance/meta',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({campaign_id:campaign.id})}));setMessage(`Meta ${value.rows}행을 동기화했습니다.`);setReload(v=>v+1);}catch(e){setMessage((e as Error).message);}finally{pendingRef.current=false;setPending(false);}}}/></div>}
  </div>;
}

function FilterPanel({report,filters,onChange,onReset,exportUrl}:{report:DashboardReport;filters:Filters;onChange:(key:keyof Filters,event:React.ChangeEvent<HTMLSelectElement>)=>void;onReset:()=>void;exportUrl:string}){const options=report.options;const configs:[keyof Filters,string,(string|number)[]][]=[['utm_campaign','캠페인',options.campaigns],['ad_type','광고 유형',['cold','retarget','unclassified']],['adset','광고세트',options.adsets],['creative','소재',options.creatives],['device','기기',options.devices],['layout','레이아웃 버전',options.layouts]];return <section className="panel"><div className="panel-head"><h2>다중 필터</h2><div className="row"><button type="button" className="btn" onClick={onReset}><RotateCcw size={15}/>초기화</button><a className="btn primary" href={exportUrl}><Download size={15}/>CSV 내보내기</a></div></div><div className="landing-filter-grid">{configs.map(([key,label,values])=><label key={key}>{label}<select multiple value={filters[key]} onChange={event=>onChange(key,event)}>{values.map(value=><option key={value} value={value}>{key==='ad_type'?value==='cold'?'콜드':value==='retarget'?'리타겟':'미분류':displayDimension(String(value))}</option>)}</select></label>)}</div><p className="meta">Ctrl 또는 Command 키를 누른 채 여러 값을 선택할 수 있습니다.</p></section>}
function ActualForm({campaign,pending,onSave}:{campaign:PerformanceCampaign;pending:boolean;onSave:(value:Record<string,unknown>)=>void}){function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),value:Record<string,unknown>={day:form.get('day'),clear:form.getAll('clear')};for(const key of ['kakao_members','new_payments','existing_payments','memo']){const field=form.get(key);if(field!==null&&field!=='')value[key]=field;}onSave(value);}return <form className="panel" onSubmit={submit}><h2>일별 실측 입력</h2><p className="meta">빈칸은 기존값을 유지합니다. 0은 실제 0으로 저장되며, 삭제는 필드별 초기화를 선택합니다.</p><label className="field">날짜<input name="day" type="date" min={campaign.start_day} max={campaign.end_day} required disabled={pending}/></label>{[['kakao_members','자정 기준 카카오톡방 현재 인원'],['new_payments','신규 고객 결제 건수'],['existing_payments','기존 고객 결제 건수']].map(([name,label])=><div className="landing-reset-field" key={name}><label className="field">{label}<input name={name} type="number" min="0" inputMode="numeric" disabled={pending}/></label><label className="check-row"><input type="checkbox" name="clear" value={name} disabled={pending}/>초기화</label></div>)}<div className="landing-reset-field"><label className="field">메모<textarea name="memo" maxLength={1000} disabled={pending}/></label><label className="check-row"><input type="checkbox" name="clear" value="memo" disabled={pending}/>초기화</label></div><button className="btn primary" disabled={pending}><Save size={16}/>{pending?'저장 중':'부분 저장'}</button></form>}
function CampaignForm({campaign,canManage,pending,onSave,onSync}:{campaign:PerformanceCampaign;canManage:boolean;pending:boolean;onSave:(value:Record<string,unknown>)=>void;onSync:()=>void}){function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();onSave(Object.fromEntries(new FormData(event.currentTarget)));}return <form className="panel" onSubmit={submit}><div className="panel-head"><h2>캠페인 설정</h2><span className={`badge ${campaign.meta_sync_status==='success'?'green':campaign.meta_sync_status==='failed'?'red':'amber'}`}>{campaign.meta_sync_status}</span></div><fieldset disabled={!canManage||pending}><label className="field">캠페인명<input name="name" defaultValue={campaign.name} required/></label><label className="field">UTM campaign<input name="utm_campaign" defaultValue={campaign.utm_campaign} required/></label><div className="landing-date-pair"><label>시작일<input name="start_day" type="date" defaultValue={campaign.start_day} required/></label><label>종료일<input name="end_day" type="date" defaultValue={campaign.end_day} required/></label></div><label className="field">라이브 최대 동시시청<input name="live_peak" type="number" min="0" defaultValue={campaign.live_peak??''}/></label><div className="landing-date-pair"><label>신규 고객 가격<input name="new_customer_price" type="number" min="0" defaultValue={campaign.new_customer_price}/></label><label>기존 고객 가격<input name="existing_customer_price" type="number" min="0" defaultValue={campaign.existing_customer_price}/></label></div><label className="field">Meta 광고계정 ID · 공통<input value={campaign.meta_ad_account_id||''} readOnly aria-readonly="true"/><small className="meta">모든 무료클래스 캠페인에 자동 적용됩니다.</small></label><label className="field">Meta 캠페인 ID<input name="meta_campaign_id" inputMode="numeric" placeholder="광고 세팅 후 캠페인 ID 입력" defaultValue={campaign.meta_campaign_id||''}/></label><div className="row"><button className="btn primary" disabled={pending}><Save size={16}/>설정 저장</button><button type="button" className="btn" disabled={pending||!campaign.meta_campaign_id} onClick={onSync}><RefreshCw size={16}/>Meta 재동기화</button></div></fieldset>{!canManage&&<p className="meta">캠페인·Meta 연결 설정은 관리자만 변경할 수 있습니다.</p>}{campaign.meta_last_synced_at&&<p className="meta">마지막 동기화 {new Date(campaign.meta_last_synced_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} KST</p>}{campaign.meta_sync_error&&<p className="notice amber">{campaign.meta_sync_error}</p>}</form>}
