'use client';
import { useState, type ReactNode } from 'react';
import { decodeLabel, kstDate, type LandingConfig } from '@/lib/landing';
type Dimensions = { campaign:string; adset:string; creative:string; traffic:string };
export type Group = Dimensions & { layout_ver:number; sessions:number; clicks:number; converted:number; alive:number; bounced:number; completed_no_click:number; avg_depth:number; top_exit:string };
type SectionStat = Dimensions & {layout_ver:number;section:string;reached:number;dwell_ms:number};
type Snapshot = {layout_ver:number; sections:string[]; created_at:string; note:string};
type Daily = {day:string;layout_ver:number;sessions:number;clicks:number;converted:number;bounced:number};
export type MetaRow = {day:string;campaign:string;adset:string;creative:string;impressions:number;link_clicks:number;spend:number};
export type Report = {config:LandingConfig;groups:Group[];sections:SectionStat[];daily:Daily[];ctas:{layout_ver:number;position:string;clicks:number;alive:number;avg_scroll:number}[];cta_sections?:{layout_ver:number;context:string;clicks:number}[];environment:{layout_ver:number;device:string;browser:string;in_app:boolean;returning:boolean;sessions:number;clicks:number;converted:number;alive:number}[];options:Dimensions[];snapshots:Snapshot[];actuals:({day:string}&Record<string,number|null|string>)[];meta:MetaRow[];last_event_at:string|null};
const n=(value:number|null|undefined)=>value==null?'—':Number(value).toLocaleString('ko-KR',{maximumFractionDigits:1});
export const pct=(value:number,total:number)=>total>0?(value/total*100).toFixed(1)+'%':'—';
const sum=<T,>(rows:T[],key:keyof T)=>rows.reduce((total,row)=>total+Number(row[key]||0),0);
const label=(s:string)=>decodeLabel(s)||'미지정';
const identity=(r:{campaign:string;adset:string;creative:string})=>JSON.stringify([r.campaign,r.adset,r.creative].map(decodeLabel));
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="landing-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;}
function Card({title,children}:{title:string;children:ReactNode}){return <section className="landing-panel"><h2>{title}</h2>{children}</section>;}
export function LandingDashboard({report:r,filtered,traffic=''}:{report:Report;filtered:boolean;traffic?:string}) {
 const versions=r.snapshots.filter(v=>r.groups.some(g=>g.layout_ver===v.layout_ver));
 const [left,setLeft]=useState(0),[right,setRight]=useState(0);
 const a=r.snapshots.find(v=>v.layout_ver===left)||r.snapshots.at(-2),b=r.snapshots.find(v=>v.layout_ver===right)||r.snapshots.at(-1);
 const sessions=sum(r.groups,'sessions'),converted=sum(r.groups,'converted'),clicks=sum(r.groups,'clicks'),metaSessions=sum(r.groups.filter(g=>g.traffic==='meta'),'sessions');
 const metaApplicable=!traffic || traffic==='meta';
 const impressions=sum(r.meta,'impressions'),linkClicks=metaApplicable?sum(r.meta,'link_clicks'):0;
 const joins=r.actuals.filter(a=>a.joins!==null).at(-1)?.joins;
 const payments=r.actuals.some(a=>a.payments!==null)?sum(r.actuals,'payments'):null;
 const live=r.actuals.some(a=>a.live_peak!==null)?Math.max(...r.actuals.map(a=>Number(a.live_peak||0))):null;
 const funnel:[string,number|null][]=[['노출',metaApplicable&&r.meta.length?impressions:null],['링크클릭',metaApplicable&&r.meta.length?linkClicks:null],['세션',sessions],['CTA 클릭 세션',converted],['카카오 누적 입장',filtered?null:joins==null?null:Number(joins)],['라이브 최대 동시시청',filtered?null:live],['결제',filtered?null:payments]];
 const gap=linkClicks>0?Math.max(0,(linkClicks-metaSessions)/linkClicks*100):null;
 return <div className="landing-report"><Card title="전체 퍼널"><div className="landing-funnel">{funnel.map(([name,value],i)=><div key={name}><span>{name}</span><strong>{n(value)}</strong><small>{i>0&&value!=null&&funnel[i-1][1]!=null?pct(value,funnel[i-1][1]!):'—'}</small></div>)}</div><p className="muted">CTA 클릭 {n(clicks)}회 · 클릭 세션 {n(converted)}회. 클릭률은 중복 클릭을 제외한 세션 기준입니다. 누적 입장·최대 동시시청의 단계 비율은 참고값입니다.</p>{filtered && <p className="muted">카카오 이후 실측은 캠페인·소재·유입별로 나눌 수 없어 전체 조회에서만 표시합니다.</p>}{versions.length>1 && <p className="notice">조회 기간에 {versions.length}개 구성이 있습니다. 아래 성과와 섹션 지표는 버전별로 나눠 표시합니다. 전체 퍼널의 세션은 버전별 관측 합계로, 버전을 걸쳐 재접속하면 중복될 수 있습니다.</p>}</Card>
 <div className="landing-stats"><div><span>Meta 클릭 → 세션 갭</span><strong>{gap==null?'—':gap.toFixed(1)+'%'}</strong><small>광고 유입 {n(metaSessions)} / 링크클릭 {n(linkClicks)}</small></div><div><span>이동 실패 의심률</span><strong>{pct(sum(r.groups,'alive'),clicks)}</strong><small>실제 카카오 입장 실패 확정값은 아닙니다.</small></div><div><span>무터치 이탈률</span><strong>{pct(sum(r.groups,'bounced'),sessions)}</strong></div><div><span>완주 후 미클릭</span><strong>{n(sum(r.groups,'completed_no_click'))}회</strong><small>전체 세션의 {pct(sum(r.groups,'completed_no_click'),sessions)}</small></div></div>
 {gap!==null&&gap>r.config.thresholds.gap_percent && <p className="notice landing-warning">링크클릭 대비 세션 갭이 기준 {r.config.thresholds.gap_percent}%를 넘습니다. 로딩 속도·추적 차단·중복 광고 클릭을 확인해 주세요.</p>}
 {!sessions && <p className="notice">선택한 기간에 수집된 방문이 없습니다. 랜딩 설정과 조회 기간을 확인해 주세요. 테스트 모드 방문은 집계되지 않습니다.</p>}
 <Card title="유입 구분"><Table headers={['유입','세션','클릭 세션','클릭률']}>{[['meta','Meta 광고'],['direct','직접 유입'],['other','기타 참조']].map(([traffic,name])=>{const g=r.groups.filter(g=>g.traffic===traffic);return <tr key={traffic}><td>{name}</td><td>{n(sum(g,'sessions'))}</td><td>{n(sum(g,'converted'))}</td><td>{pct(sum(g,'converted'),sum(g,'sessions'))}</td></tr>;})}</Table></Card>
 {versions.map(v=><VersionReport key={v.layout_ver} snapshot={v} report={r}/>)}
 {r.snapshots.length>1 && a && b && <Card title="구성 버전 비교"><div className="landing-toolbar"><label>이전 버전<select value={a.layout_ver} onChange={e=>setLeft(Number(e.target.value))}>{r.snapshots.map(v=><option key={v.layout_ver} value={v.layout_ver}>v{v.layout_ver} · {v.note}</option>)}</select></label><label>비교 버전<select value={b.layout_ver} onChange={e=>setRight(Number(e.target.value))}>{r.snapshots.map(v=><option key={v.layout_ver} value={v.layout_ver}>v{v.layout_ver} · {v.note}</option>)}</select></label></div><p className="muted">상단의 캠페인·광고세트·소재 필터가 두 버전에 동일하게 적용됩니다. 위치 변경은 도달률에 영향을 줍니다.</p><Table headers={['섹션','순서','v'+a.layout_ver+' 도달 / 이탈','v'+b.layout_ver+' 도달 / 이탈','도달 변화']}>{Array.from(new Set([...a.sections,...b.sections])).map(section=>{const x=sectionMetrics(r,a,section),y=sectionMetrics(r,b,section);return <tr key={section}><td>{section}</td><td>{a.sections.indexOf(section)+1||'—'} → {b.sections.indexOf(section)+1||'—'}</td><td>{x?pct(x.reached,x.total)+' / '+pct(x.drop,x.total):'—'}</td><td>{y?pct(y.reached,y.total)+' / '+pct(y.drop,y.total):'—'}</td><td>{x&&y&&x.total&&y.total?((y.reached/y.total-x.reached/x.total)*100).toFixed(1)+'%p':'—'}</td></tr>;})}</Table></Card>}
 <Card title="일자별 추이"><p className="muted">점선은 발행 시점입니다. 세션과 비율의 축을 구분하며, 아래 표에서 버전별 정확한 값을 확인할 수 있습니다.</p><Trend report={r}/><Table headers={['날짜 (KST)','버전','세션','클릭률','무터치 이탈률']}>{r.daily.map(d=><tr key={d.day+':'+d.layout_ver}><td>{d.day}</td><td>v{d.layout_ver}</td><td>{n(d.sessions)}</td><td>{pct(d.converted,d.sessions)}</td><td>{pct(d.bounced,d.sessions)}</td></tr>)}</Table></Card>
 <p className="muted">마지막 수집: {r.last_event_at?new Date(r.last_event_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'아직 없음'} · Meta 광고 수치는 수동 입력 기준입니다.</p>
 </div>;
}
function sectionMetrics(r:Report,v:Snapshot,section:string){const index=v.sections.indexOf(section);if(index<0)return null;const stats=r.sections.filter(s=>s.layout_ver===v.layout_ver),rows=stats.filter(s=>s.section===section),reached=sum(rows,'reached'),total=sum(r.groups.filter(g=>g.layout_ver===v.layout_ver),'sessions'),previous=index===0?total:sum(stats.filter(s=>s.section===v.sections[index-1]),'reached');return {reached,total,drop:Math.max(0,previous-reached),dwell:reached?rows.reduce((n,s)=>n+s.dwell_ms*s.reached,0)/reached/1000:0};}
function VersionReport({snapshot:v,report:r}:{snapshot:Snapshot;report:Report}){
 const groups=r.groups.filter(g=>g.layout_ver===v.layout_ver),stats=r.sections.filter(s=>s.layout_ver===v.layout_ver),total=sum(groups,'sessions');
 const sets=Array.from(new Set(groups.map(g=>JSON.stringify([g.campaign,g.adset]))));
 const threshold=r.config.thresholds;
 const creatives=[...groups].sort((a,b)=>(b.converted/b.sessions)-(a.converted/a.sessions));
 const winners=creatives.filter(g=>g.traffic==='meta'&&g.creative&&g.sessions>=threshold.min_sessions&&g.converted>=threshold.min_clicks).slice(0,3);
 const versionDates=new Set(r.daily.filter(d=>d.layout_ver===v.layout_ver).map(d=>d.day));
 const metaFor=(g:Group)=>g.traffic==='meta'?r.meta.filter(m=>identity(m)===identity(g)&&versionDates.has(m.day)):[];
 function verdict(g:Group){if(g.sessions<threshold.min_sessions)return '표본 부족 · 보류';const m=metaFor(g),ctr=sum(m,'impressions')?sum(m,'link_clicks')/sum(m,'impressions')*100:null,rate=g.converted/g.sessions*100;if(threshold.cta_rate_min!==null&&ctr!==null){if(ctr>=threshold.meta_ctr_min&&rate<threshold.cta_rate_min)return '랜딩 문제 의심';if(ctr<threshold.meta_ctr_min&&rate>=threshold.cta_rate_min)return '소재 문제 의심';}return winners.includes(g)?'위너 후보':threshold.cta_rate_min===null?'기준 설정 후 판정':rate<threshold.cta_rate_min?'클릭률 점검':'유지';}
 return <div className="landing-version-report"><div className="landing-version-heading"><strong>v{v.layout_ver}</strong><div><h2>{v.note||'랜딩 구성'}</h2><p>{new Date(v.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} 발행 · {n(total)} 세션</p></div></div>
 <Card title="광고세트별 요약"><Table headers={['캠페인 / 광고세트','세션','클릭 세션','클릭률','무터치 이탈률','평균 도달 순서']}>{sets.map(key=>{const [campaign,adset]=JSON.parse(key),rows=groups.filter(g=>g.campaign===campaign&&g.adset===adset),count=sum(rows,'sessions');return <tr key={key}><td>{label(campaign)} / {label(adset)}</td><td>{n(count)}</td><td>{n(sum(rows,'converted'))}</td><td>{pct(sum(rows,'converted'),count)}</td><td>{pct(sum(rows,'bounced'),count)}</td><td>{n(rows.reduce((n,g)=>n+g.avg_depth*g.sessions,0)/count)}</td></tr>;})}</Table></Card>
 <Card title="소재별 성과"><p className="muted">위너 후보는 최소 표본·클릭 세션 기준을 통과한 클릭률 상위 3개입니다. 광고 CTR은 이 버전이 관측된 날짜의 수기 지표로, 같은 날 버전이 바뀌었다면 참고값입니다.</p><Table headers={['캠페인 / 광고세트 / 소재','세션','클릭 세션','클릭률','최다 이탈 섹션','Meta CTR','판정']}>{creatives.map((g,i)=>{const m=metaFor(g);return <tr key={i} className={g.sessions<threshold.min_sessions?'landing-muted-row':''}><td>{[g.campaign,g.adset,g.creative].map(label).join(' / ')}</td><td>{n(g.sessions)}</td><td>{n(g.converted)}</td><td>{pct(g.converted,g.sessions)}</td><td>{g.top_exit}</td><td>{pct(sum(m,'link_clicks'),sum(m,'impressions'))}</td><td><span className={'landing-verdict '+(verdict(g).includes('의심')?'warning':'')}>{verdict(g)}</span></td></tr>;})}</Table></Card>
 <Card title="소재 × 섹션 도달률"><p className="muted">동일한 페이지에서도 소재가 데려온 고객의 기대가 다르면 이탈 구간이 달라집니다. 특정 소재만 이탈하면 소재 문구와 랜딩 내용의 연결을 확인하세요.</p><Table headers={['캠페인 / 세트 / 소재',...v.sections]}>{creatives.map((g,i)=><tr key={i}><td>{[g.campaign,g.adset,g.creative].map(label).join(' / ')}</td>{v.sections.map(section=>{const reached=sum(stats.filter(s=>s.section===section&&s.campaign===g.campaign&&s.adset===g.adset&&s.creative===g.creative&&s.traffic===g.traffic),'reached'),rate=reached/g.sessions;return <td key={section} style={{background:`rgba(205,22,42,${Math.min(0.55,rate*0.5)})`}}>{pct(reached,g.sessions)}</td>;})}</tr>)}</Table></Card>
 <Card title="섹션 도달과 이탈"><Table headers={['섹션','도달 세션','도달률','직전 구간 대비 이탈률','평균 체류']}>{v.sections.map(section=>{const s=sectionMetrics(r,v,section)!;return <tr key={section}><td>{section}</td><td>{n(s.reached)}</td><td>{pct(s.reached,total)}</td><td>{pct(s.drop,total)}</td><td>{n(s.dwell)}초</td></tr>;})}</Table><p className="muted">이탈률 = (직전 섹션 도달 − 현재 섹션 도달) / 전체 세션. 순서 건너뛰기로 음수가 되면 0으로 표시합니다.</p></Card>
 <Card title="CTA 위치별"><Table headers={['위치','클릭수','비중','평균 스크롤','이동 실패 의심률']}>{r.ctas.filter(c=>c.layout_ver===v.layout_ver).map(c=><tr key={c.position}><td>{c.position}</td><td>{n(c.clicks)}</td><td>{pct(c.clicks,sum(groups,'clicks'))}</td><td>{n(c.avg_scroll)}%</td><td>{pct(c.alive,c.clicks)}</td></tr>)}</Table>{!!r.cta_sections?.length&&<Table headers={['CTA / 클릭 당시 섹션','클릭수']}>{r.cta_sections.filter(c=>c.layout_ver===v.layout_ver).map(c=><tr key={c.context}><td>{c.context}</td><td>{n(c.clicks)}</td></tr>)}</Table>}</Card>
 <Card title="기기·브라우저·재방문"><Table headers={['기기','브라우저','방문','세션','클릭률','이동 실패 의심률']}>{r.environment.filter(e=>e.layout_ver===v.layout_ver).map((e,i)=><tr key={i}><td>{e.device}</td><td>{e.browser}{e.in_app?' · 인앱':''}</td><td>{e.returning?'재방문':'신규'}</td><td>{n(e.sessions)}</td><td>{pct(e.converted,e.sessions)}</td><td>{pct(e.alive,e.clicks)}</td></tr>)}</Table><p className="muted">클릭 후에도 페이지가 계속 보이는 상태를 의심 지표로 측정합니다. 카카오 입장 여부를 직접 확인하는 지표는 아닙니다.</p></Card>
 </div>;
}
function Trend({report:r}:{report:Report}){
 const days=Array.from(new Set(r.daily.map(d=>d.day))).sort();if(!days.length)return null;
 const count=Math.max(1,days.length-1),x=(i:number)=>45+i/count*690;
 const daily=days.map(day=>{const rows=r.daily.filter(d=>d.day===day);return {sessions:sum(rows,'sessions'),converted:sum(rows,'converted'),bounced:sum(rows,'bounced')};});
 const max=Math.max(1,...daily.map(d=>d.sessions));
 return <div className="landing-trend"><svg viewBox="0 0 780 330" role="img" aria-label="세션, CTA 클릭률, 무터치 이탈률과 발행일 추이"><text x="12" y="16">세션 (최대 {max})</text><text x="12" y="174">비율 (0–100%)</text>{[30,145,190,290].map(y=><line key={y} x1="45" x2="735" y1={y} y2={y} stroke="#d5d7dc"/>)}{r.snapshots.map(v=>{const i=days.indexOf(kstDate(v.created_at));return i<0?null:<g key={v.layout_ver}><line x1={x(i)} x2={x(i)} y1="25" y2="290" stroke="#777" strokeDasharray="4 4"/><text x={x(i)+3} y={42+(v.layout_ver%3)*14} fontSize="10">v{v.layout_ver}</text></g>;})}<polyline fill="none" stroke="#191a1e" strokeWidth="2.5" points={daily.map((d,i)=>`${x(i)},${145-d.sessions/max*100}`).join(' ')}/><polyline fill="none" stroke="#cd162a" strokeWidth="2.5" points={daily.map((d,i)=>`${x(i)},${290-(d.sessions?d.converted/d.sessions:0)*100}`).join(' ')}/><polyline fill="none" stroke="#888d97" strokeWidth="2" points={daily.map((d,i)=>`${x(i)},${290-(d.sessions?d.bounced/d.sessions:0)*100}`).join(' ')}/>{days.map((day,i)=>i===0||i===days.length-1||i%Math.ceil(days.length/7)===0?<text key={day} x={x(i)} y="312" textAnchor="middle" fontSize="11">{day.substring(5)}</text>:null)}</svg><p><span style={{color:'#191a1e'}}>● 세션</span>　<span style={{color:'#cd162a'}}>● CTA 클릭률</span>　<span style={{color:'#888d97'}}>● 무터치 이탈률</span></p></div>;
}
