import Link from "next/link";
import { redirect } from "next/navigation";
import { AlertTriangle, ArrowRight, CheckCircle2, ChevronDown, Compass, CreditCard, Filter, MousePointerClick, Route, Users } from "lucide-react";
import { AdminPageTitle, AdminShell } from "../../components/admin-shell";
import { createAdminClient } from "@/lib/supabase/admin";
import { getAdminUser } from "@/lib/server-auth";

export const dynamic = "force-dynamic";

type JourneyEvent = { session_id:string; user_id:string|null; event_name:string; path:string; target_path:string|null; element_label:string|null; metadata:unknown; occurred_at:string };
type Session = { id:string; events:JourneyEvent[]; sourceKey:string; source:string; medium:string; campaign:string; landing:string; articles:string[]; articleRead:boolean; classViewed:boolean; ctaClicked:boolean; checkoutViewed:boolean; completed:boolean; assisted:boolean; startedAt:string; latestAt:string; convertedAt:string };
type SearchQuery = { period?:string; source?:string; campaign?:string; outcome?:string };

const sourceLabels:Record<string,string>={instagram:"인스타그램","instagram.com":"인스타그램",google:"구글","google.com":"구글",naver:"네이버","naver.com":"네이버",crm:"CRM 메시지",kakao:"카카오",youtube:"유튜브",direct:"직접 유입"};
const eventLabels:Record<string,string>={page_view:"페이지 조회",article_view:"블로그 조회",article_click:"블로그 클릭",class_view:"클래스 상세",application_click:"신청 버튼 클릭",checkout_view:"결제 페이지 진입",order_complete:"결제 완료"};
const pct=(value:number,total:number)=>total?`${(value/total*100).toFixed(1)}%`:"0.0%";
const pctNumber=(value:number,total:number)=>total?Math.min(100,value/total*100):0;
const elapsed=(start:string,end:string)=>{const minutes=Math.max(0,Math.round((new Date(end).getTime()-new Date(start).getTime())/60000));return minutes<60?`${minutes}분`:`${Math.floor(minutes/60)}시간 ${minutes%60}분`;};
const metadata=(value:unknown)=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};

function attribution(items:JourneyEvent[]){const attributed=items.find((event)=>metadata(event.metadata).source)||items[0];const values=metadata(attributed.metadata);const rawSource=String(values.source||"direct").toLowerCase().replace(/^www\./,"");const sourceKey=rawSource||"direct";return{sourceKey,source:sourceLabels[sourceKey]||sourceKey,medium:String(values.medium||(sourceKey==="direct"?"none":"unknown")),campaign:String(values.campaign||"캠페인 없음")};}
function cleanPath(value:string){return value.split("?")[0]||"/";}
function pathLabel(value:string){const path=cleanPath(value);if(path==="/")return "메인";if(path==="/articles")return "블로그 목록";if(path.startsWith("/articles/"))return `블로그 · ${decodeURIComponent(path.split("/")[2]||"")}`;if(path.startsWith("/classes/"))return `클래스 · ${decodeURIComponent(path.split("/")[2]||"")}`;if(path.startsWith("/checkout"))return "결제 페이지";if(path.startsWith("/order-complete"))return "결제 완료";return path;}
function buildSessions(events:JourneyEvent[]){const grouped=new Map<string,JourneyEvent[]>();events.forEach((event)=>grouped.set(event.session_id,[...(grouped.get(event.session_id)||[]),event]));return [...grouped.entries()].map(([id,rawItems]):Session=>{const items=[...rawItems].sort((a,b)=>a.occurred_at.localeCompare(b.occurred_at));const first=items[0];const last=items[items.length-1];const conversion=[...items].reverse().find((event)=>["order_complete","checkout_view","application_click"].includes(event.event_name));const articles=[...new Set(items.filter((event)=>event.event_name==="article_view").map((event)=>cleanPath(event.path)))];const source=attribution(items);return{id,events:items,...source,landing:first.path,articles,articleRead:articles.length>0,classViewed:items.some((event)=>event.event_name==="class_view"),ctaClicked:items.some((event)=>event.event_name==="application_click"),checkoutViewed:items.some((event)=>event.event_name==="checkout_view"),completed:items.some((event)=>event.event_name==="order_complete"),assisted:Boolean(conversion)&&items.some((event)=>event.event_name==="article_view"&&new Date(event.occurred_at)<=new Date(conversion!.occurred_at)),startedAt:first.occurred_at,latestAt:last.occurred_at,convertedAt:conversion?.occurred_at||""};}).sort((a,b)=>b.startedAt.localeCompare(a.startedAt));}
function delta(current:number,previous:number){if(!previous)return current?"신규 데이터":"이전 기간 데이터 없음";const change=(current-previous)/previous*100;return `${change>=0?"+":""}${change.toFixed(1)}% vs 이전 기간`;}
function outcomeLabel(session:Session){if(session.completed)return "결제 완료";if(session.checkoutViewed)return "결제 진입";if(session.ctaClicked)return "신청 클릭";return "미전환";}

export default async function JourneyAnalyticsPage({searchParams}:{searchParams:Promise<SearchQuery>}){
  const operator=await getAdminUser();if(!operator)redirect("/admin?notice=permission_required");
  const query=await searchParams;const days=[7,30,90].includes(Number(query.period))?Number(query.period):30;
  const {data,error}=await createAdminClient().rpc("get_customer_journey_events",{p_days:Math.min(days*2,180)});
  const allSessions=buildSessions(error?[]:(data||[]) as JourneyEvent[]);
  // This force-dynamic server page needs one stable boundary per request.
  // eslint-disable-next-line react-hooks/purity
  const now=Date.now();const currentStart=now-days*86400000;const previousStart=now-days*2*86400000;
  const sessions=allSessions.filter((session)=>new Date(session.latestAt).getTime()>=currentStart);const previous=allSessions.filter((session)=>{const time=new Date(session.latestAt).getTime();return time>=previousStart&&time<currentStart;});
  const sources=[...new Set(sessions.map((session)=>session.sourceKey))].sort();const campaigns=[...new Set(sessions.map((session)=>session.campaign))].sort();
  const selectedSource=sources.includes(query.source||"")?query.source||"":"";const selectedCampaign=campaigns.includes(query.campaign||"")?query.campaign||"":"";const selectedOutcome=["completed","checkout","cta","none"].includes(query.outcome||"")?query.outcome||"":"";
  const matchesFilters=(session:Session)=>{if(selectedSource&&session.sourceKey!==selectedSource)return false;if(selectedCampaign&&session.campaign!==selectedCampaign)return false;if(selectedOutcome==="completed"&&!session.completed)return false;if(selectedOutcome==="checkout"&&(!session.checkoutViewed||session.completed))return false;if(selectedOutcome==="cta"&&(!session.ctaClicked||session.checkoutViewed||session.completed))return false;if(selectedOutcome==="none"&&(session.ctaClicked||session.checkoutViewed||session.completed))return false;return true;};
  const filtered=sessions.filter(matchesFilters);const previousFiltered=previous.filter(matchesFilters);
  const articleReaders=filtered.filter((session)=>session.articleRead);const ctaSessions=filtered.filter((session)=>session.ctaClicked);const checkoutSessions=filtered.filter((session)=>session.checkoutViewed);const completed=filtered.filter((session)=>session.completed);const assistedCta=ctaSessions.filter((session)=>session.assisted);const immediateCta=ctaSessions.filter((session)=>!session.assisted);const assistedRate=pct(assistedCta.length,articleReaders.length);const immediateRate=pct(immediateCta.length,filtered.filter((session)=>!session.articleRead).length);
  const campaignRows=[...new Set(filtered.map((session)=>`${session.sourceKey}\u0000${session.medium}\u0000${session.campaign}`))].map((key)=>{const [sourceKey,medium,campaign]=key.split("\u0000");const items=filtered.filter((session)=>session.sourceKey===sourceKey&&session.medium===medium&&session.campaign===campaign);return{key,source:items[0]?.source||sourceKey,medium,campaign,sessions:items.length,articles:items.filter((session)=>session.articleRead).length,cta:items.filter((session)=>session.ctaClicked).length,checkout:items.filter((session)=>session.checkoutViewed).length,completed:items.filter((session)=>session.completed).length};}).sort((a,b)=>b.sessions-a.sessions||b.cta-a.cta);
  // 아티클·클래스 상세은 선택 경로라 선형 퍼널에 넣으면 단계 통과율이 100%를 넘는다.
  // 모든 구매 흐름에 공통인 단계만 퍼널로 계산하고 콘텐츠 경유는 별도 비교한다.
  const funnel=[{label:"유입",value:filtered.length,icon:Users},{label:"신청 버튼",value:ctaSessions.length,icon:MousePointerClick},{label:"결제 진입",value:checkoutSessions.filter((session)=>session.ctaClicked).length,icon:CreditCard},{label:"결제 완료",value:completed.filter((session)=>session.ctaClicked&&session.checkoutViewed).length,icon:CheckCircle2}];

  return <AdminShell active="journey">
    <AdminPageTitle eyebrow="CUSTOMER JOURNEY" title="행동·전환 분석" description="어디서 들어와 무엇을 보고, 어느 단계에서 신청과 결제로 이어졌는지 확인합니다." action={<form className="journey-filter" aria-label="행동 분석 필터"><label>분석 기간<select name="period" defaultValue={String(days)}><option value="7">최근 7일</option><option value="30">최근 30일</option><option value="90">최근 90일</option></select></label><label>유입 채널<select name="source" defaultValue={selectedSource}><option value="">전체 채널</option>{sources.map((source)=><option value={source} key={source}>{sourceLabels[source]||source}</option>)}</select></label><label>캠페인<select name="campaign" defaultValue={selectedCampaign}><option value="">전체 캠페인</option>{campaigns.map((campaign)=><option value={campaign} key={campaign}>{campaign}</option>)}</select></label><label>결과<select name="outcome" defaultValue={selectedOutcome}><option value="">전체 결과</option><option value="completed">결제 완료</option><option value="checkout">결제 진입 후 이탈</option><option value="cta">신청 클릭 후 이탈</option><option value="none">미전환</option></select></label><button><Filter/> 적용</button><Link href={`/admin/journey?period=${days}`}>초기화</Link></form>}/>
    {error&&<p className="admin-save-error">행동 데이터를 불러오지 못했습니다: {error.message}</p>}
    <p className="journey-data-scope"><CheckCircle2/> 현재 사이트에서 실제 수집되는 페이지 조회, 블로그·클래스 조회, 신청 클릭, 결제 진입, 결제 완료 이벤트만 표시합니다. 모든 수치는 위 필터에 함께 적용됩니다.</p>
    <section className="journey-kpis"><article><Users/><span>유입 세션<strong>{filtered.length}개</strong><small>{delta(filtered.length,previousFiltered.length)}</small></span></article><article><MousePointerClick/><span>신청 버튼 클릭<strong>{ctaSessions.length}개</strong><small>클릭률 {pct(ctaSessions.length,filtered.length)}</small></span></article><article><CreditCard/><span>결제 페이지 진입<strong>{checkoutSessions.length}개</strong><small>클릭 대비 {pct(checkoutSessions.length,ctaSessions.length)}</small></span></article><article><CheckCircle2/><span>결제 완료<strong>{completed.length}개</strong><small>세션 결제율 {pct(completed.length,filtered.length)}</small></span></article></section>
    <p className="journey-definition"><AlertTriangle/> ‘신청 버튼 클릭’은 구매가 아닙니다. 실제 전환은 결제 완료 이벤트를 기준으로 확인하세요.</p>
    <section className="admin-panel journey-funnel"><header><div><Route/><span><strong>구매 전환 퍼널</strong><small>실제 기록된 공통 구매 단계만 순서대로 계산합니다.</small></span></div><em>필터 결과 {filtered.length}세션</em></header><div>{funnel.map((stage,index)=>{const previousStage=index?funnel[index-1].value:filtered.length;const Icon=stage.icon;return <article key={stage.label} className={index===funnel.length-1?"complete":""}><span><Icon/> STEP {index+1}</span><strong>{stage.value}<small>세션</small></strong><p>{stage.label}</p><i><b style={{width:`${pctNumber(stage.value,filtered.length)}%`}}/></i><em>{index?`이전 단계의 ${pct(stage.value,previousStage)}`:"필터 유입 전체"}</em></article>;})}</div></section>
    <section className="journey-comparison"><article><span>블로그 없이 신청 클릭</span><strong>{immediateCta.length}개</strong><p>비열람 세션의 클릭률 <b>{immediateRate}</b></p><i><b style={{width:`${pctNumber(immediateCta.length,Math.max(ctaSessions.length,1))}%`}}/></i></article><ArrowRight/><article className="assisted"><span>블로그 경유 후 신청 클릭</span><strong>{assistedCta.length}개</strong><p>블로그 열람 세션의 클릭률 <b>{assistedRate}</b></p><i><b style={{width:`${pctNumber(assistedCta.length,Math.max(ctaSessions.length,1))}%`}}/></i></article></section>
    <section className="admin-panel journey-campaigns"><header><div><Compass/><span><strong>유입별 성과</strong><small>실제 수집된 UTM source · medium · campaign 기준</small></span></div><em>{campaignRows.length}개 유입 조합</em></header><div className="journey-campaign-head"><span>유입 / 캠페인</span><span>세션</span><span>블로그</span><span>신청 클릭</span><span>결제 진입</span><span>결제 완료</span><span>완료율</span></div>{campaignRows.map((row)=><article key={row.key}><div><strong>{row.source}</strong><small>{row.medium} · {row.campaign}</small></div><span>{row.sessions}</span><span>{row.articles}</span><span>{row.cta}</span><span>{row.checkout}</span><b>{row.completed}</b><em>{pct(row.completed,row.sessions)}</em></article>)}{!campaignRows.length&&<p className="journey-empty">선택한 조건의 유입 데이터가 없습니다.</p>}</section>
    <section className="admin-panel journey-recent"><header><div><Route/><span><strong>개별 고객 여정</strong><small>행을 펼치면 실제 페이지 이동과 핵심 전환 행동을 확인할 수 있습니다.</small></span></div><em>{filtered.length}개 / 전체 {sessions.length}개</em></header><div className="journey-recent-head"><span>유입·캠페인</span><span>첫 화면</span><span>탐색</span><span>결과</span><span>소요시간</span><span>상세</span></div>{filtered.slice(0,50).map((session)=><details key={session.id}><summary><div><strong>{session.source}</strong><small>{session.medium} · {session.campaign}</small></div><span>{pathLabel(session.landing)}</span><span>{session.articles.length?`블로그 ${session.articles.length}개`:session.classViewed?"클래스 상세":"단일 화면"}</span><b className={session.completed?"completed":session.ctaClicked||session.checkoutViewed?"intent":""}>{outcomeLabel(session)}</b><span>{session.convertedAt?elapsed(session.startedAt,session.convertedAt):"—"}</span><ChevronDown/></summary><div className="journey-event-flow">{session.events.filter((event)=>event.event_name!=="click").map((event,index)=><article key={`${event.occurred_at}-${index}`}><time>{new Intl.DateTimeFormat("ko-KR",{month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(event.occurred_at))}</time><i>{index+1}</i><span><strong>{eventLabels[event.event_name]||event.event_name}</strong><small>{pathLabel(event.target_path||event.path)}{event.element_label?` · ${event.element_label}`:""}</small></span></article>)}</div></details>)}{!filtered.length&&<p className="journey-empty">선택한 조건에 해당하는 고객 여정이 없습니다.</p>}</section>
  </AdminShell>;
}
