import { redirect } from "next/navigation";
import { ArrowRight, BookOpen, Compass, MousePointerClick, Route, ShoppingBag, Users } from "lucide-react";
import { AdminPageTitle, AdminShell } from "../../components/admin-shell";
import { createAdminClient } from "@/lib/supabase/admin";
import { getAdminUser } from "@/lib/server-auth";

export const dynamic = "force-dynamic";

type JourneyEvent = { session_id:string; user_id:string|null; event_name:string; path:string; target_path:string|null; element_label:string|null; metadata:unknown; occurred_at:string };
type Session = { id:string; events:JourneyEvent[]; source:string; landing:string; articles:string[]; applied:boolean; completed:boolean; assisted:boolean; startedAt:string; convertedAt:string };
const label:Record<string,string>={instagram:"인스타그램",google:"구글",naver:"네이버",crm:"CRM 메시지",direct:"직접 유입"};
const pct=(value:number,total:number)=>total?`${(value/total*100).toFixed(1)}%`:"0.0%";
const elapsed=(start:string,end:string)=>{const minutes=Math.max(0,Math.round((new Date(end).getTime()-new Date(start).getTime())/60000));return minutes<60?`${minutes}분`:`${Math.floor(minutes/60)}시간 ${minutes%60}분`;};
function metadata(value:unknown){return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
function sourceName(event:JourneyEvent){const source=String(metadata(event.metadata).source||"direct").toLowerCase();return label[source]||source;}
function pathLabel(path:string){if(path==="/")return "메인";if(path==="/articles")return "아티클 목록";if(path.startsWith("/articles/"))return `아티클 · ${path.split("/")[2]}`;if(path.startsWith("/classes/"))return `클래스 · ${path.split("/")[2]}`;if(path.startsWith("/checkout"))return "수강 신청";return path;}

export default async function JourneyAnalyticsPage({searchParams}:{searchParams:Promise<{period?:string}>}){
  const operator=await getAdminUser();
  if(!operator)redirect("/admin?notice=permission_required");
  const query=await searchParams;const days=[7,30,90].includes(Number(query.period))?Number(query.period):30;
  const since=new Date(Date.now()-days*86400000).toISOString();
  const {data,error}=await createAdminClient().from("customer_journey_events").select("session_id,user_id,event_name,path,target_path,element_label,metadata,occurred_at").gte("occurred_at",since).order("occurred_at").limit(10000);
  const events=error?[]:(data||[]) as JourneyEvent[];
  const grouped=new Map<string,JourneyEvent[]>();events.forEach((event)=>grouped.set(event.session_id,[...(grouped.get(event.session_id)||[]),event]));
  const sessions:Session[]=[...grouped.entries()].map(([id,items])=>{const first=items[0];const application=items.find((event)=>event.event_name==="application_click"||event.event_name==="order_complete");const articles=[...new Set(items.filter((event)=>event.event_name==="article_view").map((event)=>event.path))];return{id,events:items,source:sourceName(first),landing:first.path,articles,applied:items.some((event)=>event.event_name==="application_click"),completed:items.some((event)=>event.event_name==="order_complete"),assisted:Boolean(application)&&items.some((event)=>event.event_name==="article_view"&&new Date(event.occurred_at)<=new Date(application!.occurred_at)),startedAt:first.occurred_at,convertedAt:application?.occurred_at||""};}).sort((a,b)=>b.startedAt.localeCompare(a.startedAt));
  const applied=sessions.filter((session)=>session.applied||session.completed);const assisted=applied.filter((session)=>session.assisted);const immediate=applied.filter((session)=>!session.assisted);const articleReaders=sessions.filter((session)=>session.articles.length>0);const averageArticles=assisted.length?assisted.reduce((sum,session)=>sum+session.articles.length,0)/assisted.length:0;
  const sources=[...new Set(sessions.map((session)=>session.source))].map((source)=>{const items=sessions.filter((session)=>session.source===source);const conversions=items.filter((session)=>session.applied||session.completed);return{source,sessions:items.length,conversions:conversions.length,assisted:conversions.filter((session)=>session.assisted).length};}).sort((a,b)=>b.sessions-a.sessions);
  const patterns=new Map<string,{sessions:number;conversions:number}>();sessions.forEach((session)=>{const steps=[pathLabel(session.landing),session.articles.length?`아티클 ${session.articles.length}개`:"",session.events.some((event)=>event.event_name==="class_view")?"클래스 상세":"",session.applied?"신청":""].filter(Boolean).join(" → ");const item=patterns.get(steps)||{sessions:0,conversions:0};item.sessions+=1;if(session.applied||session.completed)item.conversions+=1;patterns.set(steps,item);});
  const topPatterns=[...patterns.entries()].map(([path,value])=>({path,...value})).sort((a,b)=>b.sessions-a.sessions).slice(0,6);
  return <AdminShell active="journey"><AdminPageTitle eyebrow="CUSTOMER JOURNEY" title="행동·전환 분석" description="유입부터 아티클 탐색, 클래스 확인, 신청까지 세션별 고객 여정을 확인합니다." action={<form className="dashboard-period"><label>분석 기간<select name="period" defaultValue={String(days)}><option value="7">최근 7일</option><option value="30">최근 30일</option><option value="90">최근 90일</option></select></label><button>적용</button></form>}/>
  {error&&<p className="admin-save-error">행동 데이터를 불러오지 못했습니다: {error.message}</p>}
  <section className="journey-kpis"><article><Users/><span>유입 세션<strong>{sessions.length}개</strong><small>중복 방문은 세션 단위</small></span></article><article><BookOpen/><span>아티클 탐색<strong>{articleReaders.length}개</strong><small>{pct(articleReaders.length,sessions.length)}가 콘텐츠 확인</small></span></article><article><ShoppingBag/><span>클래스 신청<strong>{applied.length}개</strong><small>세션 전환율 {pct(applied.length,sessions.length)}</small></span></article><article><Route/><span>콘텐츠 경유 신청<strong>{assisted.length}개</strong><small>신청 전 평균 {averageArticles.toFixed(1)}개 열람</small></span></article></section>
  <section className="journey-comparison"><article><span>바로 신청</span><strong>{immediate.length}개</strong><p>유입 후 아티클 없이 클래스 신청</p><i><b style={{width:pct(immediate.length,Math.max(applied.length,1))}}/></i></article><ArrowRight/><article className="assisted"><span>콘텐츠 경유 신청</span><strong>{assisted.length}개</strong><p>아티클을 읽은 뒤 클래스 신청</p><i><b style={{width:pct(assisted.length,Math.max(applied.length,1))}}/></i></article></section>
  <div className="journey-grid"><section className="admin-panel journey-source"><header><div><Compass/><span><strong>유입 채널별 전환</strong><small>첫 방문의 UTM·리퍼러 기준</small></span></div></header><div className="journey-table-head"><span>유입</span><span>세션</span><span>신청</span><span>전환율</span><span>경유 신청</span></div>{sources.map((row)=><article key={row.source}><strong>{row.source}</strong><span>{row.sessions}</span><span>{row.conversions}</span><b>{pct(row.conversions,row.sessions)}</b><span>{row.assisted}</span></article>)}{!sources.length&&<p className="journey-empty">방문 데이터가 쌓이면 채널별 전환이 표시됩니다.</p>}</section>
  <section className="admin-panel journey-paths"><header><MousePointerClick/><span><strong>대표 고객 경로</strong><small>세션에서 중복 단계를 압축한 흐름</small></span></header>{topPatterns.map((item)=><article key={item.path}><p>{item.path}</p><span>{item.sessions}세션</span><b>{item.conversions}신청</b></article>)}{!topPatterns.length&&<p className="journey-empty">아직 분석할 경로가 없습니다.</p>}</section></div>
  <section className="admin-panel journey-recent"><header><div><Route/><span><strong>최근 고객 여정</strong><small>개인정보 없이 익명 세션 흐름만 표시합니다.</small></span></div><em>{sessions.length}개</em></header><div className="journey-recent-head"><span>유입·첫 화면</span><span>콘텐츠 탐색</span><span>클래스 행동</span><span>결과</span><span>소요시간</span></div>{sessions.slice(0,30).map((session)=><article key={session.id}><div><strong>{session.source}</strong><small>{pathLabel(session.landing)}</small></div><span>{session.articles.length?`${session.articles.length}개 아티클`:"바로 탐색"}</span><span>{session.events.some((event)=>event.event_name==="class_view")?"클래스 상세 확인":"상세 미확인"}</span><b className={session.applied||session.completed?"converted":""}>{session.completed?"결제 완료":session.applied?session.assisted?"경유 신청":"바로 신청":"미전환"}</b><span>{session.convertedAt?elapsed(session.startedAt,session.convertedAt):"—"}</span></article>)}</section>
  </AdminShell>;
}
