// 운영 확장 v3 · 모든 변경은 이 문서의 메모리 안에서만 시연됩니다.
const moreRoutes={products:['상품 관리','book','09-products.html'],'product-editor':['상품 등록·수정','edit','10-product-editor.html'],learning:['학습 콘텐츠 관리','book','11-learning-content.html'],'learning-editor':['학습 콘텐츠 편집','edit','12-learning-editor.html'],cohorts:['기수·회차 관리','calendar','13-cohorts.html'],customers:['회원 관리','users','14-customers.html'],tags:['고객 태그 관리','users','15-customer-tags.html'],coupons:['쿠폰 관리','grid','16-coupons.html'],'product-reviews':['상품 후기 관리','chat','17-product-reviews.html'],banners:['메인 배너 관리','grid','18-main-banners.html'],articles:['아티클 관리','edit','19-articles.html'],testimonials:['고객 후기 관리','chat','20-customer-stories.html'],orders:['주문 결제','grid','21-orders-payments.html'],seo:['검색코드 설정','settings','22-search-code.html']};
Object.assign(routes,moreRoutes);routes.missions[0]='미션 관리';
const navGroups=[['클래스 관리',['products','cohorts','learning','missions','members','reviews','questions']],['고객 관리',['customers','tags','coupons','product-reviews']],['콘텐츠 관리',['banners','articles','testimonials']],['매출 관리',['orders']],['마케팅 관리',['analytics','metrics','seo','settings']]];
nav=function(){const current=state.route==='product-editor'?'products':state.route==='learning-editor'?'learning':state.route;const nl=(r)=>`<a href="#${r}" class="nav-link ${current===r?'active':''}" ${current===r?'aria-current="page"':''}>${icon(routes[r][1])}${routes[r][0]}${r==='reviews'?`<span class="nav-count">${reviews.filter(x=>x.status==='pending').length}</span>`:''}</a>`;return `<aside class="sidebar" id="sidebar"><button type="button" class="btn ghost sidebar-close" data-action="menu" aria-label="관리자 메뉴 닫기">메뉴 닫기 ×</button><a class="brand" href="#overview"><span class="brand-mark">b</span><span>brandyaction<small>EDU / ADMIN</small></span></a><div class="workspace-label"><span class="square">B</span>클래스 운영 워크스페이스</div><nav aria-label="관리자 카테고리">${nl('overview')}${navGroups.map(([title,rs])=>`<details class="nav-group" ${rs.includes(current)||current==='overview'?'open':''}><summary>${title}</summary>${rs.map(nl).join('')}</details>`).join('')}</nav><div class="side-footer"><span class="design-tag">Brand system · 22개 화면</span></div><div class="profile"><span class="avatar">R</span><div><b style="font-size:var(--type-small)">리키</b><div class="meta">운영 관리자 · 시안 모드</div></div></div></aside>`};
const ov2=views.overview;views.overview=()=>ov2().replace(scope(),`<div class="category-strip">${navGroups.map(([t,rs])=>`<a href="#${rs[0]}">${icon(routes[rs[0]][1],20)}<h3>${t}</h3><p>${rs.length}개 메뉴</p></a>`).join('')}</div>`);
const ux={learnWeek:1,learnQuery:'',learnStatus:'all',lessonId:1,lessonTab:'body',lessonDirty:false,productId:'p1',productTab:'basic',productStatus:'all',productType:'all',productQuery:'',missionProduct:'p5',customerClass:'all',orderProduct:'all',orderFrom:'',orderTo:'',customerStatus:'all',customerQuery:'',tagMode:'all',couponStatus:'all',reviewStatus:'all',reviewProduct:'all',bannerStatus:'all',articleStatus:'all',storyStatus:'all',orderStatus:'all',orderQuery:'',seoTab:'seo',previewMode:'desktop'};
const formField=(label,input,hint='',wide=false)=>`<label class="field ${wide?'wide':''}">${label}${input}${hint?`<small>${hint}</small>`:''}</label>`;
const textInput=(key,value='',placeholder='',extra='')=>`<input type="text" data-field="${key}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${extra}>`;
const selectInput=(key,values,current,extra='')=>`<select data-field="${key}" ${extra}>${values.map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${v}</option>`).join('')}</select>`;
const textArea=(key,value='',rows=4,extra='')=>`<textarea data-field="${key}" rows="${rows}" ${extra}>${esc(value)}</textarea>`;
function uploadBox(id,label,accept,help){return `<div class="upload-box">${icon('download',23)}<p>${label}</p><label class="btn upload-label">파일 선택<input type="file" data-local-file="${id}" accept="${accept}" aria-label="${label}"></label><p class="meta">${help} · 선택한 파일은 서버에 전송되지 않습니다.</p></div><div id="file-${id}" class="mt8" aria-live="polite"></div>`}
const tinyFilter=(name,values,value)=>`<select data-filter="${name}" aria-label="목록 상태 필터">${values.map(v=>`<option value="${v}" ${v===value?'selected':''}>${v==='all'?'전체':v}</option>`).join('')}</select>`;
const extSearch=(key,value,placeholder)=>`<div class="search">${icon('search')}<input type="search" data-ux-search="${key}" value="${esc(value)}" aria-label="${placeholder}" placeholder="${placeholder}"></div>`;
const demoFooter=(back,kind)=>`<div class="editor-savebar"><span class="meta" id="editor-dirty">미리보기 전용 · 실제 서비스에 반영되지 않습니다.</span>${link('목록으로',back)}${btn('임시저장 시연',`data-ops="draft" data-kind="${kind}"`)}${btn('공개 전 확인',`data-ops="publish" data-kind="${kind}"`,'primary')}</div>`;
function safeRich(source){const doc=new DOMParser().parseFromString(source,'text/html');const allowed=new Set(['P','H1','H2','H3','H4','UL','OL','LI','STRONG','EM','B','I','BR','BLOCKQUOTE','CODE','PRE']);function clean(node){if(node.nodeType===3)return esc(node.textContent);if(node.nodeType!==1)return '';if(['SCRIPT','STYLE','IFRAME','OBJECT','SVG','MATH','FORM','INPUT'].includes(node.tagName))return '';const body=[...node.childNodes].map(clean).join('');return allowed.has(node.tagName)?`<${node.tagName.toLowerCase()}>${body}</${node.tagName.toLowerCase()}>`:body;}return [...doc.body.childNodes].map(clean).join('');}

const learningTitles=['Claude란 무엇인가','모델 선택하기','대화 컨텍스트 작동 방식','Context Window 이해하기','주요 활용 사례 탐색','요금제 & 인터페이스 파악','1주차 복습','Role Prompting 실습','Context Stacking 연습','Chain-of-Thought Prompting','제약 조건 추가하기','Prompt Chaining 설계','고급 프롬프팅 조합','2주차 복습','Artifacts 입문','Artifact 프롬프팅 고도화','라이브 편집 & 정제','To-Do 앱 / 계산기 만들기','Skills 개념 & 첫 Skill 만들기','글쓰기 & 리서치 Skills','3주차 복습','Coworker 모드 실전','Connectors & 파일 분석','자동화 기초 (MCP 개념)','Claude Code 입문','파워 유저 시스템 설계','초보자 실수 10가지 점검','나만의 Skill 라이브러리 완성','실제 프로젝트 1개 완성하기','30일 총복습 & 다음 단계'];
const baseQuiz=[{q:'학습 내용을 업무에 적용하기 전에 가장 먼저 할 일은?',options:['우리 업무의 목표와 맥락 정리','아무 예시나 그대로 복사','모든 자동화부터 실행','결과를 검토하지 않고 게시'],answer:0,explanation:'목표와 맥락을 명확히 한 뒤 결과를 검토하는 순서로 진행합니다.'},{q:'생성한 결과를 검토할 때 중요한 것은?',options:['문장의 길이만 확인','실행 속도만 비교','사실 여부와 우리 기준의 일치','도구 이름을 많이 포함'],answer:2,explanation:'결과의 사실 여부와 업무 기준에 맞는지를 확인합니다.'},{q:'이번 학습을 마친 뒤 권장하는 행동은?',options:['전체 시스템을 한 번에 교체','다음 강의만 계속 시청','아무 기록도 남기지 않기','작은 업무에 적용하고 결과를 기록'],answer:3,explanation:'작은 실행과 기록을 통해 적용 범위를 늘립니다.'}];
const lessonData=learningTitles.map((title,i)=>({id:i+1,title,day:i+1,week:Math.floor(i/5)+1,tag:i<5?'기초':i<15?'활용':'실전',key:i<5?'basic':i<15?'practice':'advanced',minutes:5+i%4,published:i<15,intro:'오늘 배운 개념을 실제 업무에 연결해 보는 시간입니다. 도구를 아는 데서 끝내지 않고 작은 실행으로 이어갑니다.',content:'<h2>학습의 핵심</h2><p>내 업무의 목표와 맥락을 먼저 정리하고, 도구가 도와줄 부분을 구분합니다.</p><ul><li>지금 해결할 업무 한 가지 정하기</li><li>필요한 자료와 기준 준비하기</li><li>결과를 검토하고 실행 기록 남기기</li></ul>',tip:'처음부터 완벽한 결과를 기대하기보다, 작은 업무 하나를 끝내고 개선해 보세요.',quiz:JSON.parse(JSON.stringify(baseQuiz))}));
Object.assign(lessonData[0],{intro:'오늘은 Claude가 어떤 도구인지 이해하는 날입니다. 단순한 질문과 답변을 넘어, 어떤 업무를 함께할 수 있는지 살펴봅니다.',content:'<h2>Claude를 업무 파트너로 이해하기</h2><p>긴 글을 분석하고 구조적으로 글을 쓰는 작업을 예로 들어 봅니다. 작업의 목적과 배경, 원하는 결과 형식을 함께 전달하는 것이 중요합니다.</p><ul><li>업무의 목표와 맥락 전달하기</li><li>모호한 표현을 구체적인 지시로 바꾸기</li><li>생성 결과의 사실 여부와 품질 검토하기</li></ul><p>이 본문은 첨부된 학습 편집 화면을 설명하기 위한 예시 콘텐츠입니다.</p>',tip:'처음부터 완벽한 결과를 기대하기보다, 대화를 통해 원하는 방향을 구체화해 보세요.',quiz:[{q:'Claude가 가장 잘하는 영역으로 올바른 것은?',options:['긴 글 분석과 구조적 글쓰기','실시간 주식 정보 검색','모호한 질문을 알아서 해석하기','인터넷 실시간 뉴스 가져오기'],answer:0,explanation:'이 예시 수업에서는 긴 글 분석과 구조적인 글쓰기를 대표 활용으로 소개합니다.'},{q:'Claude 결과물 품질에 가장 큰 영향을 주는 것은?',options:['사용하는 기기 종류','질문의 길이','맥락의 품질과 지시사항 명확성','Claude를 사용하는 시간대'],answer:2,explanation:'결과에 필요한 맥락과 원하는 작업을 명확하게 전달합니다.'},{q:'Claude를 단순한 챗봇으로만 보지 않는 이유는?',options:['대화 기능이 없기 때문에','챗봇보다 이름이 길기 때문에','텍스트를 읽지 못하기 때문에','다양한 작업을 도울 수 있는 도구이기 때문에'],answer:3,explanation:'질문과 답변을 넘어 실제 작업의 맥락에서 활용할 수 있습니다.'}]});
const lesson=()=>lessonData.find(x=>x.id===ux.lessonId)||lessonData[0];
function learningList(){let rs=lessonData.filter(l=>(ux.learnWeek===0||l.week===ux.learnWeek)&&(!ux.learnQuery||l.title.includes(ux.learnQuery))&&(ux.learnStatus==='all'||ux.learnStatus==='공개'&&l.published||ux.learnStatus==='비공개'&&!l.published));return head('학습 콘텐츠 관리','일차별 학습 본문과 확인 퀴즈를 관리합니다.',btn(icon('plus')+' 학습 추가','data-ops="new-lesson"','primary'),'CLASS MANAGEMENT')+scope()+`<div class="metrics">${metric('전체 학습',lessonData.length+'<small>개</small>','6주 · 일차별 1개 학습')}${metric('공개',lessonData.filter(x=>x.published).length+'<small>개</small>','회원에게 공개되는 학습','highlight')}${metric('비공개',lessonData.filter(x=>!x.published).length+'<small>개</small>','작성·검토 후 공개')}${metric('확인 퀴즈',lessonData.reduce((s,l)=>s+l.quiz.length,0)+'<small>문항</small>','학습별 문항·정답·해설 관리')}</div><div class="learning-layout"><aside class="week-nav"><div class="week-nav-title">학습 구성</div>${[0,1,2,3,4,5,6].map(w=>`<button data-learn-week="${w}" class="${ux.learnWeek===w?'active':''}" aria-pressed="${ux.learnWeek===w}"><span>${w?w+'주차':'전체 학습'}</span><span class="meta">${w?lessonData.filter(l=>l.week===w).length:lessonData.length}</span></button>`).join('')}</aside><div><div class="toolbar" style="margin-top:0">${extSearch('learnQuery',ux.learnQuery,'학습 제목 검색')}<span class="spacer"></span>${tinyFilter('learnStatus',['all','공개','비공개'],ux.learnStatus)}</div><div class="lesson-list">${rs.length?rs.map(l=>`<article class="lesson-list-item"><span class="lesson-day">${l.day}</span><div><span class="learning-tag">Day ${l.day} · ${l.week}주차 &nbsp; ${esc(l.tag)} · ${l.minutes}분</span><button class="title-btn" data-lesson="${l.id}"><h3>${esc(l.title)}</h3></button><p>본문 + Tip · 확인 퀴즈 ${l.quiz.length}문항</p></div><div class="lesson-tools">${badge(l.published?'공개':'비공개',l.published?'green':'')}${btn('편집 '+icon('chevron',13),`data-lesson="${l.id}"`,'small')}</div></article>`).join(''):empty('조건에 맞는 학습이 없습니다.','주차·공개 상태 또는 검색어를 바꿔 보세요.')}</div><div class="meta mt16">${rs.length}개 표시 · 학습 본문과 퀴즈는 한 편집 화면에서 관리합니다.</div></div></div>`;}
function learningEditor(){const l=lesson();return head('학습 콘텐츠 편집',`Day ${l.day} · ${l.week}주차 / ${esc(l.title)}`,`${btn('학습자 미리보기','data-ops="lesson-preview"')}${badge(l.published?'공개 중':'비공개',l.published?'green':'')}`,'LEARNING EDITOR')+`<div class="ops-callout mb16">${esc(l.title)} <span class="muted">· 본문과 확인 퀴즈를 함께 편집합니다.</span></div><section class="panel"><div class="panel-head"><h2>기본 정보</h2><label class="review-switch"><input type="checkbox" data-lesson-field="published" ${l.published?'checked':''}> 공개</label></div><div class="section-pad form-grid">${formField('일차 (Day)',`<input type="number" min="1" value="${l.day}" data-lesson-field="day">`)}${formField('주차 (Week)',`<input type="number" min="1" max="6" value="${l.week}" data-lesson-field="week">`)}${formField('제목 <span class="required-mark">*</span>',`<input data-lesson-field="title" value="${esc(l.title)}" required>`,'',true)}${formField('태그 라벨',`<input data-lesson-field="tag" value="${esc(l.tag)}">`)}${formField('소요 시간 · 분',`<input type="number" min="1" value="${l.minutes}" data-lesson-field="minutes">`)}${formField('태그 내부 키',`<input data-lesson-field="key" value="${esc(l.key)}" spellcheck="false">`,'화면에 보이는 라벨과 시스템용 키를 구분합니다.',true)}</div></section><section class="panel mt24"><div class="panel-head"><h2>학습 본문</h2><span class="meta">HTML 형식 지원 · 안전한 태그만 미리보기</span></div><div class="section-pad lesson-body-grid"><div>${formField('도입 (Intro)',`<textarea rows="3" data-lesson-field="intro">${esc(l.intro)}</textarea>`)}${formField('학습 내용 (HTML)',`<textarea rows="12" class="code-editor" data-lesson-field="content" spellcheck="false">${esc(l.content)}</textarea>`,'제목·문단·목록·강조 표시 지원. 스크립트·외부 리소스는 실행하지 않습니다.')}${formField('Tip',`<textarea rows="3" data-lesson-field="tip">${esc(l.tip)}</textarea>`)}</div><aside class="preview-window"><div class="preview-window-top"><b>학습자 화면</b><span>본문 미리보기</span></div><div id="lesson-live-preview"><div class="safe-html-preview"><span class="badge">${esc(l.tag)} · ${l.minutes}분</span><h2>${esc(l.title)}</h2><p class="intro-preview">${esc(l.intro)}</p><div id="lesson-rich-content">${lessonPreviewMarkup(l)}</div><div class="tip-preview">${esc(l.tip)}</div></div></div></aside></div></section><section class="panel mt24"><div class="panel-head"><div><h2>확인 퀴즈 <span class="muted">${l.quiz.length}문항</span></h2><p>선택지 앞 원을 눌러 정답을 지정하고 해설을 작성합니다.</p></div>${btn(icon('plus')+' 문제 추가','data-ops="quiz-add"','small')}</div><div class="section-pad" id="quiz-editor">${quizEditor(l)}</div></section>${demoFooter('learning','lesson')}`;}
function lessonPreviewMarkup(l){return typeof DOMParser==='undefined'?esc(l.content):safeRich(l.content);}
function quizEditor(l){return l.quiz.map((q,i)=>`<article class="question-editor"><div class="question-title-row"><span>${i+1}.</span><input type="text" value="${esc(q.q)}" data-quiz-q="${i}" aria-label="${i+1}번 문제"><button type="button" class="btn iconbtn ghost danger" data-remove-quiz="${i}" aria-label="${i+1}번 문제 삭제">${icon('close',15)}</button></div>${q.options.map((o,j)=>`<div class="option-row ${q.answer===j?'correct':''}"><input type="radio" name="correct-${i}" value="${j}" data-answer-for="${i}" ${q.answer===j?'checked':''} aria-label="${i+1}번 문제 ${String.fromCharCode(65+j)} 정답 선택"><span class="option-letter">${String.fromCharCode(65+j)}</span><input type="text" value="${esc(o)}" data-option-q="${i}" data-option-i="${j}" aria-label="${i+1}번 문제 선택지 ${String.fromCharCode(65+j)}">${btn(icon('close',13),`data-remove-option="${i}:${j}" aria-label="선택지 ${String.fromCharCode(65+j)} 삭제" ${q.options.length<=2?'disabled':''}`,'iconbtn ghost small')}</div>`).join('')}<div class="q-actions">${btn('+ 선택지 추가',`data-add-option="${i}" ${q.options.length>=6?'disabled':''}`,'small ghost')}<span class="meta">정답: ${q.answer===null?'미지정':String.fromCharCode(65+q.answer)}</span></div>${formField('정답 해설',`<textarea rows="2" data-explanation="${i}">${esc(q.explanation)}</textarea>`)}</article>`).join('')||empty('퀴즈가 아직 없습니다.','문제 추가로 첫 번째 확인 퀴즈를 작성해 주세요.');}

const productData=[{id:'p1',name:'사업자를 위한 AI 마케팅 실전 과정',type:'유료 클래스',state:'판매 중',price:1490000,regular:1490000,cohort:'5기',resource:'구매자 전용',subtitle:'혼자 하던 마케팅을 실행 가능한 업무 시스템으로',detail:'<h2>AI를 일에 쓰는 4주</h2><p>고객·메시지·콘텐츠·반복 업무를 하나의 흐름으로 연결합니다.</p>',files:['AI_마케팅_워크북.pdf','업무_실행_계획표.xlsx'],slug:'ai-marketing',start:'2026-09-14',end:'2026-10-04'},{id:'p2',name:'AI 직원을 둔 일당백 1인 회사 만들기',type:'무료 클래스',state:'모집 예정',price:0,regular:0,cohort:'9월 무료 라이브',resource:'누구나 다운로드',subtitle:'도구를 배우는 데서 실제 일하는 구조로',detail:'<h2>나만의 AI 업무 시스템</h2><p>무료 라이브에서 내 업무의 시작점을 찾아보세요.</p>',files:['무료_업무_진단_체크리스트.pdf'],slug:'free-ai-live',start:'2026-09-14',end:'2026-09-28'},{id:'p3',name:'AI 업무 템플릿 팩',type:'디지털 자료',state:'판매 중',price:29000,regular:39000,cohort:'해당 없음',resource:'구매자 전용',subtitle:'진단·기획·실행을 돕는 업무 템플릿',detail:'<h2>바로 적용하는 업무 템플릿</h2>',files:['업무_템플릿_패키지.zip'],slug:'ai-template',start:'2026-09-01',end:'2026-12-31'},{id:'p4',name:'콘텐츠 실행 워크숍',type:'유료 클래스',state:'작성 중',price:390000,regular:390000,cohort:'미연결',resource:'구매자 전용',subtitle:'',detail:'',files:[],slug:'content-workshop',start:'',end:''}];
const product=()=>productData.find(p=>p.id===ux.productId)||productData[0];
function productList(){const rows=productData.filter(p=>(ux.productType==='all'||p.type===ux.productType)&&(ux.productStatus==='all'||p.state===ux.productStatus)&&(!ux.productQuery||p.name.includes(ux.productQuery)));return head('상품 관리','상품 정보·상세페이지·제공 자료·판매 조건을 한곳에서 관리합니다.',btn(icon('plus')+' 상품 등록','data-ops="new-product"','primary'),'CLASS MANAGEMENT')+`<div class="metrics">${metric('전체 상품',productData.length+'<small>개</small>','클래스 · 디지털 자료')}${metric('판매 중',productData.filter(p=>p.state==='판매 중').length+'<small>개</small>','실제 운영 데이터가 아닌 예시','highlight')}${metric('모집 예정',productData.filter(p=>p.state==='모집 예정').length+'<small>개</small>','모집 기간 지정')}${metric('작성 중',productData.filter(p=>p.state==='작성 중').length+'<small>개</small>','공개 전 필수 정보 확인')}</div><div class="panel"><div class="filter-row">${extSearch('productQuery',ux.productQuery,'상품명 검색')}<span class="spacer"></span>${filterSelect('productType','상품 유형',[['all','전체 유형'],['무료 클래스','무료 클래스'],['유료 클래스','유료 클래스'],['디지털 자료','디지털 자료']],ux.productType)}${tinyFilter('productStatus',['all','판매 중','모집 예정','작성 중','판매 종료'],ux.productStatus)}</div>${rows.length?table(['상품','유형','판매가','연결 기수','자료','판매 상태','관리'],rows.map((p,i)=>`<tr><td><div class="catalog-name"><div class="catalog-cover ${p.type==='무료 클래스'?'red-cover':p.type==='디지털 자료'?'gray-cover':''}">BRANDY<br>EDU</div><div><button data-product="${p.id}">${esc(p.name)}</button><p>${p.id.toUpperCase()} · /class/${esc(p.slug)}</p></div></div></td><td>${p.type}</td><td><b>${p.price?n(p.price)+'원':'무료'}</b></td><td>${esc(p.cohort)}</td><td>${p.files.length}개</td><td>${badge(p.state,p.state==='판매 중'?'green':p.state==='모집 예정'?'blue':'')}</td><td>${btn('수정',`data-product="${p.id}"`,'small')}</td></tr>`).join('')):empty('상품이 없습니다.','검색어 또는 판매 상태를 변경하세요.')}<div class="table-foot">${rows.length}개 상품 · 예시 상품</div></div><div class="mt24">${note('상품은 가격·판매·자료의 단위, 기수는 일정·정원·수강생의 단위로 분리합니다. 상품을 수정해도 기존 주문 금액은 소급 변경하지 않는 설계입니다.')}</div>`;}
function productEditor(){const p=product();return head(ux.productId==='new'?'상품 등록':'상품 수정',esc(p.name),btn('고객 화면 미리보기','data-ops="product-preview"'),'PRODUCT EDITOR')+`<div class="editor-layout"><div class="editor-main"><section class="panel">${tabs([['basic','기본·판매'],['detail','상세페이지'],['resources','제공 자료'],['access','수강·권한'],['publish','공개·검색']],'productEditorTab',ux.productTab)}<div class="section-pad">${productForm(p)}</div></section>${demoFooter('products','product')}</div><aside class="editor-aside"><div class="side-preview"><span class="section-code">고객에게 보이는 상품</span><div class="preview-cover mt16"><p>BRANDYACTION EDU</p><h3>${esc(p.name)}</h3><p class="accent">${p.type}</p></div><div class="preview-meta"><b>${p.price?n(p.price)+'원':'무료'}</b>${p.regular>p.price?`<s>${n(p.regular)}원</s>`:''}</div><p class="meta mt8">${esc(p.subtitle||'상품 소개를 입력해 주세요.')}</p><div class="divider"></div><div class="setting-line"><span>상품 상태</span>${badge(p.state,p.state==='판매 중'?'green':'')}</div><div class="setting-line"><span>연결 기수</span><b>${esc(p.cohort)}</b></div><div class="setting-line"><span>제공 자료</span><b>${p.files.length}개</b></div>${link('기수·회차 관리','cohorts','full mt16')}</div></aside></div>`;}
function productForm(p){switch(ux.productTab){case 'basic':return `<h2 class="mb16">기본 정보</h2><div class="form-grid">${formField('상품명 <span class="required-mark">*</span>',textInput('product:name',p.name),'',true)}${formField('상품 유형',selectInput('product:type',['무료 클래스','유료 클래스','디지털 자료'],p.type))}${formField('판매 상태',selectInput('product:state',['작성 중','모집 예정','판매 중','판매 종료'],p.state))}${formField('상품 한 줄 소개',textInput('product:subtitle',p.subtitle),'',true)}${formField('정가 · 원',`<input data-field="product:regular" type="number" min="0" step="1" value="${p.regular}">`)}${formField('판매가 · 원',`<input data-field="product:price" type="number" min="0" step="1" value="${p.price}" ${p.type==='무료 클래스'?'readonly':''}>`,'무료 클래스는 0원으로 표시합니다.')}${formField('모집 시작 · KST',`<input type="date" data-field="product:start" value="${p.start}">`)}${formField('모집 마감 · KST',`<input type="date" data-field="product:end" value="${p.end}">`)}</div><h3 class="mt8">상품 썸네일</h3>${uploadBox('product-thumb','썸네일 이미지를 선택하세요.','image/png,image/jpeg,image/webp','권장 비율 16:9 · PNG/JPG/WebP')}<div class="mt16">${note('썸네일과 상세페이지 이미지는 별도로 관리합니다. 디지털 자료 상품은 수강 기수 연결 없이 판매할 수 있습니다.')}</div>`;
case 'detail':return `<div class="spread mb16"><h2>상세페이지 업로드</h2>${badge('초안 v2','outline')}</div><p style="font-size:var(--type-small)">HTML 파일을 업로드하거나 아래 본문을 편집합니다. 긴 이미지형 상세페이지도 등록할 수 있습니다.</p>${uploadBox('product-html','상세페이지 HTML 파일 선택','.html,.htm','HTML 소스 선택 후 안전한 본문만 미리보기')}${formField('상세 본문 · HTML',textArea('product:detail',p.detail,9,'class="code-editor"'),'외부 스크립트·이벤트·폼·링크 동작은 허용하지 않습니다.')}<div class="row">${btn('본문 미리보기','data-ops="detail-preview"','small')}<span class="meta">이미지·영상 등 외부 파일은 실제 개발 시 별도 연결</span></div>${uploadBox('product-detail-image','이미지형 상세페이지 선택','image/png,image/jpeg,image/webp','긴 이미지는 원본 비율 유지')}<div class="divider"></div><h3>업로드 이력</h3><div class="setting-line"><div><b>상세페이지 v2 · 초안</b><p>09.10 11:40 · 리키 · UI 예시</p></div>${badge('검토 대기','amber')}</div><div class="setting-line"><div><b>상세페이지 v1 · 현재 공개</b><p>09.07 14:20 · 리키 · UI 예시</p></div>${btn('이력 보기','data-demo="상세페이지 버전 비교·복원 전 확인 화면이 연결될 영역입니다. 실제 공개본은 변경하지 않습니다."','small')}</div>`;
case 'resources':return `<h2>제공 자료</h2><p class="mt8" style="font-size:var(--type-small)">다운로드 파일과 이용 대상을 지정합니다.</p>${p.files.map((f,i)=>`<div class="asset-row"><span class="file-icon">${f.split('.').pop().toUpperCase()}</span><div><b style="font-size:var(--type-small)">${esc(f)}</b><p>원본 파일 미연결 · ${esc(p.resource)}</p></div>${btn('설정',`data-resource-index="${i}"`,'small')}</div>`).join('')}${uploadBox('product-resource','PDF · 문서 · 템플릿 자료 추가','.pdf,.xlsx,.docx,.zip','목록·권한 UI 확인용')}${formField('기본 다운로드 권한',selectInput('product:resource',['누구나 다운로드','로그인 회원','신청 완료 회원','구매자 전용'],p.resource))}${note('무료 자료도 상세페이지에서 내려받을 수 있게 노출합니다. 공개 자료와 구매자 자료가 섞여 노출되지 않도록 파일별 권한을 둡니다.','warning')}`;
case 'access':return `<h2 class="mb16">수강·기수 연결</h2>${formField('연결 기수',selectInput('product:cohort',['1기','5기','4기','9월 무료 라이브','미연결','해당 없음'],p.cohort))}<div class="form-grid">${formField('수강 시작 기준',selectInput('product:accessStart',['기수 시작일','구매 즉시','관리자 승인 후'],p.accessStart||'기수 시작일'))}${formField('수강 기간',selectInput('product:accessPeriod',['기수 종료 후 90일','구매 후 1년','무제한'],p.accessPeriod||'기수 종료 후 90일'))}</div><h3 class="mt16">구매 후 제공 항목</h3><div class="checkbox-stack mt16"><label><input type="checkbox" checked>학습 콘텐츠·영상·퀴즈</label><label><input type="checkbox" checked>미션 제출 및 피드백</label><label><input type="checkbox" checked>등록된 구매자 전용 자료</label></div><div class="divider"></div>${note('환불 상태와 수강 권한은 함께 검토하되 별도로 표시합니다. 주문별 권한 회수 기준은 정책 확정 후 연결합니다.')}${link('주문·수강 권한 확인','orders','mt16')}`;
default:return `<h2 class="mb16">공개·검색 설정</h2>${formField('상품 주소 (slug)',textInput('product:slug',p.slug),'중복 주소와 기존 공유 링크에 미치는 영향은 실제 발행 전 검사합니다.')}${formField('검색 제목',textInput('product:seoTitle',p.seoTitle||p.name))}${formField('검색 설명',textArea('product:seoDescription',p.seoDescription||p.subtitle,3))}<div class="snippet"><div class="snippet-url">brandyaction-edu.com › class › ${esc(p.slug)}</div><h3>${esc(p.name)}</h3><p>${esc(p.subtitle||'검색 결과에 표시할 설명을 작성해 주세요.')}</p></div><div class="divider"></div><h3>공개 전 점검</h3><div class="checkbox-stack mt16"><label><input type="checkbox" data-publish-check>상품명·가격·모집 기간 확인</label><label><input type="checkbox" data-publish-check>상세페이지 PC·모바일 확인</label><label><input type="checkbox" data-publish-check>자료 다운로드 권한 확인</label><label><input type="checkbox" data-publish-check>기수·수강 기간 확인</label></div>`;}}

function cohortView(){return head('기수·회차 관리','상품의 판매 정보와 실제 교육 일정·정원을 구분해 운영합니다.',btn('+ 기수 등록','data-ops="cohort-editor"','primary'),'CLASS MANAGEMENT')+`<div class="panel">${table(['기수','연결 상품','기간','정원','운영 상태','관리'],[['4기','사업자를 위한 AI 마케팅 실전 과정','09.01–09.22','24 / 30','진행 중'],['5기','사업자를 위한 AI 마케팅 실전 과정','10.06–10.27','18 / 30','모집 중'],['9월 무료 라이브','AI 직원을 둔 일당백 1인 회사 만들기','09.28 21:00','정원 제한 없음','준비 중']].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${badge(r[4],r[4]==='진행 중'?'green':'blue')}</td><td>${btn('일정·설정',`data-cohort-name="${r[0]}"`,'small')}</td></tr>`).join(''))}<div class="table-foot">일정·인원은 운영 흐름 설명용 예시입니다.</div></div><div class="equal-col mt24">${panel('5기 회차 일정',table(['회차','일정 · KST','콘텐츠','공개'],['10.06','10.13','10.20','10.27'].map((d,i)=>`<tr><td>${i+1}회차</td><td>${d} 20:00</td><td>라이브 + 자료 + 미션</td><td>${badge('예약')}</td></tr>`).join('')),link('학습 관리','learning','small'))}${panel('수강 운영 연결',`<div class="panel-body"><div class="workflow-row"><span>상품 등록</span><span>기수·회차 연결</span><span class="active">학습·미션 공개</span></div><p class="mt16" style="font-size:var(--type-small)">회차 일정과 콘텐츠 공개 시점이 변경되면, 이미 등록된 수강생에게 미치는 영향을 먼저 확인합니다.</p><div class="row mt16">${link('회원 미션관리','members')}${link('상품 설정','product-editor')}</div></div>`)}</div>`;}

const customerData=members.map((m,i)=>({...m,email:`member${String(i+1).padStart(2,'0')}@example.com`,joined:'2026.09.0'+(i%9+1),status:i===8?'이용 제한':'정상',marketing:i%3===0,tags:i%3===0?['유료 수강생','4기']:i%3===1?['무료 1강 시청']:['무료 2강 시청','재수강 관심'],className:i%3===0?'AI 마케팅 실전 · 4기':'AI 온보딩 · 1기'}));
const tagsData=[{id:1,name:'무료 1강 시청',mode:'자동',rule:'무료 클래스 · 1강 시청률 ≥ 80%',state:'사용 중',color:'#4f6e96'},{id:2,name:'무료 2강 시청',mode:'자동',rule:'무료 클래스 · 2강 시청률 ≥ 80%',state:'사용 중',color:'#527e68'},{id:3,name:'유료 수강생',mode:'자동',rule:'유료 클래스 · 결제 완료',state:'사용 중',color:'#ac544c'},{id:4,name:'4기',mode:'수동',rule:'관리자가 직접 부여',state:'사용 중',color:'#77717f'},{id:5,name:'재수강 관심',mode:'수동',rule:'관리자가 직접 부여',state:'사용 중',color:'#97814c'}];
function customerList(){let rows=customerData.filter(c=>(ux.customerClass==='all'||c.className===ux.customerClass)&&(ux.customerStatus==='all'||c.status===ux.customerStatus)&&(!ux.customerQuery||(c.name+c.email+c.phone+c.tags.join(' ')).includes(ux.customerQuery)));return head('회원 관리','회원 정보·수강 권한·태그·구매 이력을 연결해서 확인합니다.',btn(icon('download')+' 명단 내보내기','data-demo="회원 명단 내보내기 UI입니다. 실제 개인정보는 내려받지 않습니다."'),'CUSTOMER MANAGEMENT')+`<div class="metrics">${metric('전체 회원','13<small>명</small>','목록은 합성한 예시 회원')}${metric('정상 회원','12<small>명</small>','회원 계정 상태')}${metric('이용 제한','1<small>명</small>','학습 승인 상태와 별개')}${metric('마케팅 수신 동의',customerData.filter(c=>c.marketing).length+'<small>명</small>','서비스 알림과 동의를 구분')}</div><div class="panel"><div class="filter-row">${extSearch('customerQuery',ux.customerQuery,'이름 · 이메일 · 연락처 · 태그 검색')}<span class="spacer"></span>${filterSelect('customerClass','클래스',[['all','전체 클래스'],...[...new Set(customerData.map(c=>c.className))].map(c=>[c,c])],ux.customerClass)}${tinyFilter('customerStatus',['all','정상','이용 제한'],ux.customerStatus)}</div>${rows.length?table(['회원','수강 중인 클래스','고객 태그','가입일','수신 동의','계정 상태','관리'],rows.map(c=>`<tr><td><div class="person"><span class="avatar">${c.name[0]}</span><div><button data-customer="${c.id}">${c.name}</button><small>${c.email}</small><small>${c.phone}</small></div></div></td><td>${c.className}</td><td>${c.tags.map(t=>`<span class="tag-chip">${t}</span>`).join('')}</td><td>${c.joined}</td><td>${c.marketing?'동의':'미동의'}</td><td>${badge(c.status,c.status==='정상'?'green':'amber')}</td><td>${btn('상세',`data-customer="${c.id}"`,'small')}</td></tr>`).join('')):empty('회원이 없습니다.','검색 조건을 확인하세요.')}<div class="table-foot">${rows.length}명 표시 · 개인정보는 필요한 범위로 제한</div></div><div class="row mt24">${link('회원 미션관리','members')}${link('고객 태그 설정','tags')}</div>`;}
function customerDrawer(id){const c=customerData.find(x=>x.id===id);showDialog('회원 관리 상세',`<div class="drawer-profile"><span class="avatar red">${c.name[0]}</span><div><h2>${c.name}</h2><p>${c.email}<br>${c.phone}</p></div></div><div class="setting-line"><span>계정 상태</span>${badge(c.status,c.status==='정상'?'green':'amber')}</div><div class="setting-line"><span>마케팅 수신 동의</span><b>${c.marketing?'동의':'미동의'}</b></div><div class="setting-line"><span>가입일</span><b>${c.joined}</b></div><h3 class="mt24">수강 권한</h3><div class="asset-row"><span class="square">C</span><div><b>${c.className}</b><p>기수 기간 + 복습 기간 · UI 예시</p></div>${badge('수강 중','green')}</div><h3 class="mt24">고객 태그</h3><div class="row wrap mt8">${c.tags.map(t=>`<span class="tag-chip">${t}</span>`).join('')}</div>${btn('태그 편집',`data-customer-tags="${c.id}"`,'small mt8')}<h3 class="mt24">구매 내역</h3>${orderData.filter(o=>o.customer===c.id).map(o=>`<div class="setting-line"><div><b>${o.number}</b><p>${o.product}</p></div>${btn('주문 보기',`data-order="${o.id}"`,'small')}</div>`).join('')||`<p class="meta mt8">이 시안에 연결된 주문 예시가 없습니다.</p>`}<div class="divider"></div>${note('수신 미동의 회원에게 마케팅 발송을 허용하는 UI를 제공하지 않습니다. 교육 운영 알림은 별도 정책과 권한을 적용합니다.')}<label class="field mt16">내부 메모<textarea rows="3" placeholder="계정·권한 변경 사유 등 운영 메모"></textarea></label>`,btn('이용 상태 변경',`data-customer-status="${c.id}"`)+btn('미션 진행 보기',`data-member="${c.id}"`,'primary'),true);}
function tagsView(){let rows=tagsData.filter(t=>ux.tagMode==='all'||t.mode===ux.tagMode);return head('고객 태그 관리','고객의 수강·구매 행동과 수동 분류를 구분합니다.',btn('+ 태그 만들기','data-tag-edit="new"','primary'),'CUSTOMER MANAGEMENT')+tabs([['all','전체 태그',5],['자동','자동 태그',3],['수동','수동 태그',2]],'tagMode',ux.tagMode)+`<div class="panel">${table(['태그','분류','부여 조건','회원 수','상태','관리'],rows.map(t=>`<tr><td><b><span class="tag-marker" style="--tag-color:${t.color}"></span> ${t.name}</b></td><td>${badge(t.mode,t.mode==='자동'?'blue':'')}</td><td>${t.rule}</td><td>${customerData.filter(c=>c.tags.includes(t.name)).length}명</td><td>${badge(t.state,'green')}</td><td>${btn('조건·설정',`data-tag-edit="${t.id}"`,'small')}</td></tr>`).join(''))}</div><div class="equal-col mt24">${panel('자동 태그 적용 흐름',`<div class="panel-body"><div class="workflow-row"><span>로그인 회원의 행동</span><span>태그 조건 확인</span><span class="active">태그 부여</span></div><p class="mt16" style="font-size:var(--type-small)">무료 1강·2강 시청, 상품 결제 같은 확인 가능한 회원 행동을 기준으로 분류합니다.</p></div>`)}${panel('조건 변경 시 영향',`<div class="panel-body"><h3>기존 회원 적용 범위부터 확인</h3><p class="mt8" style="font-size:var(--type-small)">신규 행동부터 적용할지, 기존 기록을 다시 평가할지 선택합니다. 수동 태그를 자동으로 덮어쓰지 않습니다.</p><p class="privacy-note mt16">익명 랜딩 세션을 회원 태그에 임의로 연결하지 않습니다. OS CRM 연계는 추후 개발 범위입니다.</p></div>`)}</div>`;}
const couponData=[{id:1,name:'첫 구매 웰컴 쿠폰',code:'WELCOME10',type:'정률',value:10,cap:150000,min:100000,target:'신규 회원',products:'유료 클래스',period:'09.10–09.30',used:2,total:100,status:'발급 중'},{id:2,name:'기존 수강생 재수강',code:'RETURN500',type:'정액',value:500000,cap:500000,min:1490000,target:'재수강 관심 태그',products:'AI 마케팅 실전 과정',period:'09.14–10.04',used:1,total:30,status:'발급 예정'},{id:3,name:'템플릿 출시 기념',code:'TEMPLATE5',type:'정액',value:5000,cap:5000,min:29000,target:'전체 회원',products:'디지털 자료',period:'09.01–09.07',used:8,total:50,status:'종료'}];
function couponsView(){let rows=couponData.filter(c=>ux.couponStatus==='all'||c.status===ux.couponStatus);return head('쿠폰 관리','할인 금액·기간·수량·대상을 명확하게 제한합니다.',btn('+ 쿠폰 만들기','data-coupon="new"','primary'),'CUSTOMER MANAGEMENT')+`<div class="metrics">${metric('전체 쿠폰','3<small>개</small>')}${metric('발급 중','1<small>개</small>','현재 기간 내 발급','highlight')}${metric('발급 예정','1<small>개</small>')}${metric('사용 횟수','11<small>회</small>','기간 전체 예시 합계')}</div><div class="panel"><div class="filter-row"><b style="font-size:var(--type-small)">쿠폰 목록</b><span class="spacer"></span>${tinyFilter('couponStatus',['all','발급 중','발급 예정','종료'],ux.couponStatus)}</div>${table(['쿠폰','혜택','적용 대상','사용 / 수량','유효기간','상태','관리'],rows.map(c=>`<tr><td><b>${c.name}</b><p class="mono">${c.code}</p></td><td>${c.type==='정률'?c.value+'%':n(c.value)+'원'}<p>최소 ${n(c.min)}원</p></td><td>${c.target}<p>${c.products}</p></td><td>${c.used} / ${c.total}</td><td>${c.period}</td><td>${badge(c.status,c.status==='발급 중'?'green':c.status==='발급 예정'?'blue':'')}</td><td>${btn('설정',`data-coupon="${c.id}"`,'small')}</td></tr>`).join(''))}<div class="table-foot">사용 이력과 발급 이력은 별도 확인하는 설계입니다.</div></div><div class="mt24">${note('주문당 쿠폰 1개를 기본안으로 잡았습니다. 환불 시 쿠폰 복구, 부분 환불의 할인 배분은 정책 확정 후 연결합니다.')}</div>`;}
const productReviewData=[{id:1,customer:1,productId:'p1',product:'AI 마케팅 실전 과정',rating:5,body:'반복 업무를 정리하고 실제 실행 순서까지 잡을 수 있었습니다.',status:'게시 중',featured:true},{id:2,customer:3,productId:'p1',product:'AI 마케팅 실전 과정',rating:4,body:'실습 과정을 따라가며 제 업무에 맞는 기준을 만들었습니다.',status:'게시 대기',featured:false},{id:3,customer:11,productId:'p3',product:'AI 업무 템플릿 팩',rating:5,body:'업무를 한 장으로 정리하는 데 도움이 되었습니다.',status:'게시 중',featured:false}];
function productReviewsView(){let rs=productReviewData.filter(r=>(ux.reviewProduct==='all'||r.productId===ux.reviewProduct)&&(ux.reviewStatus==='all'||r.status===ux.reviewStatus));return head('상품 후기 관리','구매 상품에 연결된 수강 후기를 검토하고 노출을 관리합니다.',link('홈페이지 고객 후기','testimonials'),'CUSTOMER MANAGEMENT')+`<div class="ops-callout mb16">상품 후기 <span class="muted">→ 해당 상품 상세페이지에 표시</span> · 고객 후기 <span class="muted">→ 별도로 선정한 홈페이지 사례</span></div><div class="panel"><div class="filter-row"><b style="font-size:var(--type-small)">구매·수강 후기</b><span class="spacer"></span>${filterSelect('reviewProduct','상품',productOptions(true),ux.reviewProduct)}${tinyFilter('reviewStatus',['all','게시 대기','게시 중','숨김'],ux.reviewStatus)}</div>${rs.length?table(['작성자 · 상품','평점·후기','게시 상태','상품 대표 노출','관리'],rs.map(r=>`<tr><td><b>${customerData[r.customer-1].name}</b><p>${r.product}</p><p>구매 연결 · 예시</p></td><td class="quote-cell"><span class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</span><p>${r.body}</p></td><td>${badge(r.status,r.status==='게시 중'?'green':r.status==='게시 대기'?'amber':'')}</td><td><label class="review-switch"><input type="checkbox" data-feature-review="${r.id}" ${r.featured?'checked':''} ${r.status!=='게시 중'?'disabled':''}>대표 노출</label></td><td>${btn('검토',`data-product-review="${r.id}"`,'small')}</td></tr>`).join('')):empty('조건에 맞는 상품 후기가 없습니다.','선택한 상품과 게시 상태를 확인하거나 전체 상품을 선택하세요.')}<div class="table-foot"><span>${rs.length}건 표시</span><span>대표 노출은 게시 중인 후기만 선택할 수 있습니다.</span></div></div><div class="mt24">${note('후기 원문은 관리자 검토 화면에서 임의로 고치지 않습니다. 노출 변경과 운영자 답변을 분리하고 변경 사유를 기록합니다.')}</div>`;}

const bannerData=[{id:1,name:'9월 무료 라이브 모집',copy:'AI 직원을 둔\n일당백 1인 회사 만들기',placement:'메인 최상단',link:'/class/free-ai-live',target:'무료 클래스 상세',start:'2026-09-14T09:00',end:'2026-09-28T18:00',status:'예약',color:'rust'},{id:2,name:'AI 마케팅 실전 과정',copy:'AI를 써보는 것에서,\n일에 쓰는 것으로.',placement:'메인 최상단',link:'/class/ai-marketing',target:'유료 과정 상세',start:'2026-09-01T09:00',end:'2026-09-30T23:59',status:'게시 중',color:''},{id:3,name:'무료 워크시트 안내',copy:'내 업무에 바로 쓰는\n무료 실습 자료',placement:'메인 중단',link:'/class/free-ai-live#resources',target:'무료 자료 영역',start:'',end:'',status:'비공개',color:'gray'}];
function bannersView(){let rs=bannerData.filter(b=>ux.bannerStatus==='all'||b.status===ux.bannerStatus);return head('메인 배너 관리','PC·모바일 이미지와 연결 페이지·노출 기간을 함께 관리합니다.',btn('+ 배너 등록','data-banner="new"','primary'),'CONTENT MANAGEMENT')+`<div class="panel"><div class="filter-row"><b style="font-size:var(--type-small)">메인 배너</b><span class="spacer"></span>${tinyFilter('bannerStatus',['all','게시 중','예약','비공개'],ux.bannerStatus)}</div>${table(['순서','배너','위치·연결','노출 기간 · KST','상태','관리'],rs.map((b,i)=>`<tr><td><div class="row"><span>${i+1}</span>${btn('↑',`data-banner-move="${b.id}" aria-label="${b.name} 위로 이동" ${i===0?'disabled':''}`,'small')}</div></td><td><div class="catalog-name"><div class="asset-preview ${b.color}">${esc(b.copy).replace('\n','<br>')}</div><div><b>${b.name}</b><p>PC·모바일 별도 이미지</p></div></div></td><td>${b.placement}<p>${b.target}</p></td><td>${b.start?b.start.replace('T',' ')+'<br>'+b.end.replace('T',' '):'미설정'}</td><td>${badge(b.status,b.status==='게시 중'?'green':b.status==='예약'?'blue':'')}</td><td>${btn('수정',`data-banner="${b.id}"`,'small')}</td></tr>`).join(''))}<div class="table-foot">여러 배너가 같은 기간에 설정되면 위 순서로 노출 · UI 예시</div></div><div class="equal-col mt24">${panel('배너 노출 기준',`<div class="panel-body"><div class="checkbox-stack"><label><input type="checkbox" checked>모바일 이미지가 없으면 발행 전 경고</label><label><input type="checkbox" checked>필수 대체 텍스트 확인</label><label><input type="checkbox" checked>연결된 상품의 공개·모집 상태 확인</label></div><p class="meta mt16">추가한 파일은 업로드 미리보기만 진행하며 서버에 저장하지 않습니다.</p></div>`)}${panel('연결 페이지 확인',`<div class="panel-body"><h3>배너 이미지와 CTA가 같은 목적지로</h3><p class="mt8" style="font-size:var(--type-small)">배너 노출과 클릭 이후 상품의 모집 상태가 어긋나지 않도록 확인 단계를 둡니다.</p>${link('상품 관리','products','mt16')}</div>`)}</div>`;}
const articleData=[{id:1,title:'AI를 도입하기 전에, 먼저 정리할 업무 세 가지',category:'업무 인사이트',author:'리키',slug:'before-ai-workflow',status:'게시 중',featured:true,body:'<h2>먼저 업무의 기준을 정리하세요.</h2><p>반복되는 업무와 직접 판단해야 하는 일을 구분하는 것부터 시작합니다.</p>'},{id:2,title:'마케팅 업무를 하나의 흐름으로 연결하는 법',category:'마케팅',author:'리키',slug:'marketing-workflow',status:'예약',featured:false,body:'<h2>콘텐츠 이전에 고객의 문제</h2><p>고객이 무엇을 해결하고 싶은지부터 살펴보세요.</p>'},{id:3,title:'실행 기록이 다음 콘텐츠가 되는 과정',category:'실행 기록',author:'운영팀',slug:'execution-story',status:'초안',featured:false,body:'<p>여기에 아티클 초안을 작성합니다.</p>'}];
function articlesView(){let rs=articleData.filter(a=>ux.articleStatus==='all'||a.status===ux.articleStatus);return head('아티클 관리','글의 편집·대표 이미지·검색 정보·게시 시점을 관리합니다.',btn('+ 아티클 작성','data-article="new"','primary'),'CONTENT MANAGEMENT')+`<div class="panel"><div class="filter-row"><b style="font-size:var(--type-small)">아티클 목록</b><span class="spacer"></span>${tinyFilter('articleStatus',['all','게시 중','예약','초안'],ux.articleStatus)}</div>${table(['아티클','카테고리','작성자','게시·수정일','노출','상태','관리'],rs.map(a=>`<tr><td><b>${a.title}</b><p>/articles/${a.slug}</p></td><td>${a.category}</td><td>${a.author}</td><td>${a.status==='초안'?'작성 중':'09.10 · 예시'}</td><td>${a.featured?badge('메인 대표','red'):'일반'}</td><td>${badge(a.status,a.status==='게시 중'?'green':a.status==='예약'?'blue':'')}</td><td>${btn('편집',`data-article="${a.id}"`,'small')}</td></tr>`).join(''))}</div><div class="mt24">${note('본문 편집과 검색 제목·설명을 한 화면에서 관리합니다. 미리보기 확인 후 게시하고, 기존 URL 변경은 별도 확인이 필요합니다.')}</div>`;}
const storyData=[{id:1,title:'혼자 하던 마케팅, 실행 순서가 생겼습니다.',name:'김○○',kind:'텍스트',source:'상품 후기 #1',consent:true,featured:true,status:'게시 중',body:'매주 어떤 일을 먼저 해야 할지 기준이 생겼고, 실제 실행한 내용을 바탕으로 콘텐츠를 만들게 되었습니다.'},{id:2,title:'AI 업무 환경을 직접 만든 4주',name:'박○○',kind:'영상',source:'수강생 인터뷰',consent:false,featured:false,status:'동의 확인',body:'과정 참여 전후의 경험을 담은 인터뷰 영상 예시입니다.'},{id:3,title:'작은 실행을 반복하는 방법',name:'최○○',kind:'텍스트',source:'직접 등록',consent:true,featured:false,status:'초안',body:'업무를 작게 나누고 매일 실행한 과정을 기록했습니다.'}];
function testimonialsView(){let rs=storyData.filter(s=>ux.storyStatus==='all'||s.status===ux.storyStatus);return head('고객 후기 관리','홈페이지에 노출할 고객 사례를 별도로 선정하고 동의를 확인합니다.',btn('+ 고객 후기 등록','data-story="new"','primary'),'CONTENT MANAGEMENT')+`<div class="ops-callout mb16">상품 후기의 원문·평점은 유지하고, 홈페이지 노출용 사례만 이 메뉴에서 편집합니다.</div><div class="panel"><div class="filter-row"><b style="font-size:var(--type-small)">홈페이지 고객 사례</b><span class="spacer"></span>${tinyFilter('storyStatus',['all','게시 중','동의 확인','초안'],ux.storyStatus)}</div>${table(['고객 사례','고객·형식','원본 출처','노출 동의','메인 대표','게시 상태','관리'],rs.map(s=>`<tr><td class="quote-cell"><b>${s.title}</b><p>${s.body}</p></td><td>${s.name}<p>${s.kind}</p></td><td>${s.source}</td><td>${badge(s.consent?'확인 완료':'확인 필요',s.consent?'green':'amber')}</td><td><input type="checkbox" data-feature-story="${s.id}" ${s.featured?'checked':''} ${!s.consent||s.status!=='게시 중'?'disabled':''} aria-label="${s.name} 후기 메인 대표 노출"></td><td>${badge(s.status,s.status==='게시 중'?'green':'')}</td><td>${btn('편집',`data-story="${s.id}"`,'small')}</td></tr>`).join(''))}</div><div class="mt24">${note('고객 이름·사진·영상·인용문 노출 동의를 확인한 사례만 게시하는 설계입니다. 이 시안의 후기는 실제 성과 주장이나 고객 증언이 아닙니다.','warning')}</div>`;}

const orderData=[{id:1,number:'BA-260910-001',customer:1,product:'AI 마케팅 실전 과정 · 5기',gross:1490000,discount:0,paid:1490000,refunded:0,payment:'결제 완료',refund:'환불 요청',access:'수강 가능',method:'카드',date:'2026.09.10 09:42'},{id:2,number:'BA-260909-002',customer:3,product:'AI 마케팅 실전 과정 · 5기',gross:1490000,discount:500000,paid:990000,refunded:0,payment:'결제 완료',refund:'없음',access:'수강 가능',method:'카드',date:'2026.09.09 18:20'},{id:3,number:'BA-260908-003',customer:11,product:'AI 업무 템플릿 팩',gross:29000,discount:0,paid:29000,refunded:29000,payment:'결제 완료',refund:'환불 완료',access:'이용 종료',method:'간편결제',date:'2026.09.08 14:10'},{id:4,number:'BA-260910-004',customer:9,product:'AI 마케팅 실전 과정 · 5기',gross:1490000,discount:0,paid:0,refunded:0,payment:'입금 대기',refund:'없음',access:'권한 미부여',method:'가상계좌',date:'2026.09.10 11:31'},{id:5,number:'BA-260910-005',customer:10,product:'콘텐츠 실행 워크숍',gross:390000,discount:0,paid:0,refunded:0,payment:'결제 실패',refund:'없음',access:'권한 미부여',method:'카드',date:'2026.09.10 11:54'}];
function ordersView(){let rs=filteredOrders();const paid=rs.reduce((s,o)=>s+o.paid,0),refunded=rs.reduce((s,o)=>s+o.refunded,0);return head('주문 결제','주문일 기준으로 기간과 상품을 선택해 결제·환불·수강 권한을 확인합니다.',btn(icon('download')+' 내보내기','data-demo="주문 내역 내보내기 UI입니다. 실제 거래 데이터는 내려받지 않습니다."'),'SALES MANAGEMENT')+orderDateControls()+`<div class="metrics">${metric('결제 완료액',n(paid)+'<small>원</small>','조회 조건에 맞는 주문 합계')}${metric('환불 완료액',n(refunded)+'<small>원</small>','환불 요청 금액은 제외')}${metric('순결제액',n(paid-refunded)+'<small>원</small>','결제 완료 − 환불 완료','highlight')}${metric('환불 요청',rs.filter(o=>o.refund==='환불 요청').length+'<small>건</small>','조회 조건 기준')}</div><div class="panel"><div class="filter-row">${extSearch('orderQuery',ux.orderQuery,'주문번호 · 회원명 · 상품명 검색')}<span class="spacer"></span>${filterSelect('orderProduct','상품',productOptions(true),ux.orderProduct)}${tinyFilter('orderStatus',['all','결제 완료','입금 대기','결제 실패','환불 요청','환불 완료'],ux.orderStatus)}</div>${rs.length?table(['주문','회원','결제액','결제 상태','환불 상태','수강 권한','관리'],rs.map(o=>`<tr><td><b>${o.number}</b><p>${o.product}</p><p>${o.date}</p></td><td><button class="btn ghost small" data-customer="${o.customer}">${customerData[o.customer-1].name}</button></td><td><b>${n(o.paid)}원</b><p>${o.method}${o.discount?' · 쿠폰 적용':''}</p></td><td>${badge(o.payment,o.payment==='결제 완료'?'green':o.payment==='결제 실패'?'red':'amber')}</td><td>${badge(o.refund,o.refund==='환불 요청'?'amber':'')}</td><td>${o.access}</td><td>${btn('상세',`data-order="${o.id}"`,'small')}</td></tr>`).join('')):empty('해당 주문이 없습니다.','주문번호나 상태 조건을 확인하세요.')}<div class="table-foot">${rs.length}건 표시 · 정산·회계 매출은 결제액과 별도</div></div>`;}
function orderDrawer(id){const o=orderData.find(x=>x.id===id);showDialog('주문 상세',`<h2>${o.number}</h2><p class="meta mt8">${o.date} · ${customerData[o.customer-1].name}</p><div class="row wrap mt16">${badge(o.payment,o.payment==='결제 완료'?'green':'amber')}${badge(o.refund)}${badge(o.access)}</div><div class="divider"></div><h3>${o.product}</h3><div class="order-money mt16"><span>상품 금액</span><b>${n(o.gross)}원</b></div><div class="order-money"><span>쿠폰 할인</span><b>−${n(o.discount)}원</b></div><div class="order-money"><span>결제 완료</span><b>${n(o.paid)}원</b></div><div class="order-money"><span>환불 완료</span><b>−${n(o.refunded)}원</b></div><div class="order-money total"><span>남은 결제액</span><b>${n(o.paid-o.refunded)}원</b></div><div class="divider"></div><h3>처리 이력</h3><div class="order-history"><div><b>주문 생성</b><p>${o.date}</p></div><div><b>${o.payment}</b><p>${o.method} · PG 거래번호: 시안에서 미노출</p></div>${o.refund!=='없음'?`<div><b>${o.refund}</b><p>사유·처리자·권한 변경 결과 함께 기록</p></div>`:''}</div><h3 class="mt24">수강 권한</h3><div class="setting-line"><span>${o.access}</span>${btn('권한 이력','data-demo="주문에 따른 권한 부여·회수 이력 UI입니다. 실제 권한은 변경하지 않습니다."','small')}</div>${note('결제 실패·입금 대기는 수강 권한을 부여하지 않습니다. 환불 완료와 권한 회수 결과도 각각 확인하는 설계입니다.')}`,btn('영수증','data-demo="영수증은 결제 연동 후 연결합니다. 이 시안에서는 발급하지 않습니다."')+btn('환불 검토',`data-refund="${o.id}" ${o.paid<=o.refunded?'disabled':''}`,'danger'),true);}

const codeEntries=[{name:'Meta 픽셀',type:'관리형 연동',location:'페이지 전체',status:'설정 대기',owner:'픽셀·이벤트 설정에서 관리'},{name:'GA4 측정',type:'관리형 연동',location:'페이지 전체',status:'설정 대기',owner:'측정 ID 등록 후 연결'},{name:'사이트 소유 확인',type:'검증 메타 태그',location:'Head',status:'초안',owner:'검색엔진 소유 확인용'}];
function seoView(){return head('검색코드 설정','검색 노출 정보와 측정·인증 코드를 안전하게 관리합니다.',btn('변경 이력','data-ops="code-history"'),'MARKETING MANAGEMENT')+tabs([['seo','검색·공유 정보'],['verification','사이트 소유 확인'],['codes','측정·추가 코드']],'seoTab',ux.seoTab)+(ux.seoTab==='seo'?`<div class="editor-layout"><section class="panel"><div class="section-pad"><h2 class="mb16">사이트 기본 검색 정보</h2>${formField('사이트 제목',textInput('seo:title','브랜디액션 에듀 | 배움에서 실행으로'))}${formField('검색 설명',textArea('seo:description','AI와 마케팅을 내 업무에 적용하는 실전 교육. 무료 클래스부터 기수별 실행 과정까지 만나보세요.',3))}${formField('사이트 대표 주소',textInput('seo:canonical','https://brandyaction-edu.com'))}<fieldset class="search-visibility"><legend>검색 노출</legend><div class="visibility-options"><label class="visibility-card"><input type="radio" name="robots" value="index" checked><span><b>검색 결과 노출 허용</b><small>검색엔진이 사이트를 검색 결과에 표시할 수 있습니다.</small></span></label><label class="visibility-card"><input type="radio" name="robots" value="noindex"><span><b>검색 결과 노출 차단</b><small>적용 전 사이트 전체의 검색 유입 영향을 확인하세요.</small></span></label></div></fieldset>${uploadBox('site-og','검색·공유 대표 이미지','image/png,image/jpeg,image/webp','권장 1200×630 · 개별 상품 설정이 있으면 우선 적용')}${btn('저장 전 확인','data-ops="seo-save"','primary')}</div></section><aside class="editor-aside"><div class="side-preview"><h3 class="mb16">검색 결과 미리보기</h3><div class="snippet"><span class="snippet-url">brandyaction-edu.com</span><h3 id="seo-title-preview">브랜디액션 에듀 | 배움에서 실행으로</h3><p id="seo-description-preview">AI와 마케팅을 내 업무에 적용하는 실전 교육. 무료 클래스부터 기수별 실행 과정까지 만나보세요.</p></div><div class="divider"></div><p class="meta">검색엔진이 실제 표시 문구를 다르게 선택할 수 있습니다. 결과 형태의 예시입니다.</p></div></aside></div>`:ux.seoTab==='verification'?panel('사이트 소유 확인',`<div class="panel-body"><div class="form-grid">${formField('Google Search Console',textInput('verify:google','','인증 메타 태그의 content 값만 입력'))}${formField('네이버 서치어드바이저',textInput('verify:naver','','인증 메타 태그의 content 값만 입력'))}</div>${note('전체 스크립트가 아닌 인증 값만 받습니다. 관리자 화면은 인증 정보 입력만 담당하며 소유 확인 완료 여부는 별도로 확인합니다.')}${btn('인증 값 확인','data-ops="verification-save"','primary mt16')}</div>`,badge('미연결','outline')):`<div class="stack">${panel('측정·인증 코드 목록',table(['항목','유형','삽입 위치','상태','관리'],codeEntries.map((c,i)=>`<tr><td><b>${c.name}</b><p>${c.owner}</p></td><td>${c.type}</td><td>${c.location}</td><td>${badge(c.status,'amber')}</td><td>${i===0?btn('픽셀 설정','data-ops="pixel-settings"','small'):btn('설정',`data-code-entry="${i}"`,'small')}</td></tr>`).join('')),btn('+ 추가 코드','data-ops="custom-code"','small'))}${note('메타 픽셀은 기존 ‘픽셀·이벤트’ 설정을 단일 원본으로 사용합니다. 추가 코드에 같은 픽셀을 중복 등록하지 않습니다.','warning')}${panel('추가 코드 적용 절차',`<div class="panel-body"><div class="workflow-row"><span>초안 등록</span><span>위치·중복·권한 검토</span><span>테스트 환경 확인</span><span class="active">운영 적용 승인</span></div><p class="mt16" style="font-size:var(--type-small)">코드 입력 내용을 관리자 화면이나 이 HTML에서 실행하지 않습니다. 검토·발행·이전 버전 되돌리기를 별도 단계로 둡니다.</p></div>`)}</div>`);}

Object.assign(views,{products:productList,'product-editor':productEditor,learning:learningList,'learning-editor':learningEditor,cohorts:cohortView,customers:customerList,tags:tagsView,coupons:couponsView,'product-reviews':productReviewsView,banners:bannersView,articles:articlesView,testimonials:testimonialsView,orders:ordersView,seo:seoView});

// 입력·검토 모달. 실제 회원·상품·거래 데이터에는 쓰지 않습니다.
const modalActions=(kind)=>btn('취소','data-action="close-dialog"')+btn('입력 내용 확인',`data-confirm-ops="${kind}"`,'primary');
const formNotice=()=>note('디자인 검토용 입력 화면입니다. 저장·발행·메시지 발송·결제 처리는 실행되지 않습니다.');
function cohortEditor(name='') {showDialog(name?'기수 일정·설정':'기수 등록',`<div class="form-grid">${formField('기수명 *',textInput('cohort:name',name,'예: AI 마케팅 실전 과정 · 6기','required'))}${formField('연결 상품',selectInput('cohort:product',productData.map(p=>p.name),productData[0].name))}${formField('시작일 · KST','<input type="date" data-field="cohort:start" value="2026-10-06" required>')}${formField('종료일 · KST','<input type="date" data-field="cohort:end" value="2026-10-27" required>')}${formField('정원','<input type="number" data-field="cohort:capacity" min="1" value="30" required>')}${formField('운영 상태',selectInput('cohort:status',['준비 중','모집 중','진행 중','종료'],'준비 중'))}</div><h3 class="mt16">일정 변경 적용 범위</h3><label class="checkline"><input type="checkbox" required>기존 수강생의 공개 일정·복습 기간 영향 확인</label>${formField('변경 사유',textArea('cohort:reason','','2','placeholder="기존 기수 수정 시 이유를 남깁니다."'))}${formNotice()}`,modalActions('cohort'),true);}
function tagEditor(id){const t=tagsData.find(t=>t.id===+id)||{name:'',mode:'수동',rule:'관리자가 직접 부여'};showDialog('고객 태그 설정',`${formField('태그명 *',textInput('tag:name',t.name,'예: 무료 1강 시청','required'))}<div class="form-grid">${formField('부여 방식',selectInput('tag:mode',['자동','수동'],t.mode))}${formField('사용 상태',selectInput('tag:status',['사용 중','중지'],'사용 중'))}</div><div class="rule-builder"><h3>자동 태그 조건</h3><div class="form-grid mt16">${formField('조건 행동',selectInput('tag:event',['무료 1강 시청','무료 2강 시청','상품 결제 완료'],'무료 1강 시청'))}${formField('기준 시청률 · %','<input type="number" min="1" max="100" value="80" data-field="tag:threshold">')}</div><p class="meta">수동 태그는 행동 조건을 적용하지 않습니다.</p></div><h3 class="mt24">변경 적용 범위</h3><label class="checkline"><input type="radio" name="tag-scope" value="future" checked>앞으로 발생하는 행동부터 적용</label><label class="checkline"><input type="radio" name="tag-scope" value="existing">기존 회원 기록도 재평가 · 대상 검토 필요</label>${note('조건 미리보기에는 로그인 회원의 확인 가능한 행동만 사용합니다. 수동 태그와 익명 랜딩 방문 기록은 자동 병합하지 않습니다.','warning')}${formNotice()}`,btn('대상 미리보기','data-ops="tag-sample"')+modalActions('tag'),true);}
function customerTags(id){const c=customerData.find(c=>c.id===id);showDialog('회원 태그 편집',`<h3>${c.name}</h3><p class="meta mt8">자동 태그는 행동 조건에서 관리하고, 수동 태그만 직접 편집합니다.</p><div class="checkbox-stack mt16">${tagsData.map(t=>`<label><input type="checkbox" data-field="member-tag:${t.id}" ${c.tags.includes(t.name)?'checked':''} ${t.mode==='자동'?'disabled':''}>${t.name} ${badge(t.mode)}</label>`).join('')}</div>${formField('변경 사유',textArea('member-tag:reason','','3','placeholder="직접 분류한 이유를 기록하세요."'))}${formNotice()}`,modalActions('member-tag'));}
function customerStatus(id){const c=customerData.find(c=>c.id===id);showDialog('회원 이용 상태 변경',`<h3>${c.name}</h3><div class="mt16">${formField('변경 상태',selectInput('member-state:status',['정상','이용 제한'],c.status))}${formField('변경 사유 *',textArea('member-state:reason','',3,'required'))}</div>${note('계정 이용 제한은 주문 환불이나 미션 보완 요청과 다릅니다. 변경 대상과 접근 제한 범위를 별도로 확인합니다.','warning')}<label class="checkline"><input type="checkbox" required>회원·사유·수강 접근 영향 확인</label>${formNotice()}`,modalActions('member-state'));}
function couponEditor(id){const c=couponData.find(c=>c.id===+id)||{name:'',code:'',type:'정률',value:10,cap:50000,min:100000,target:'전체 회원',products:'유료 클래스',total:100};showDialog('쿠폰 등록·설정',`<div class="coupon-preview"><span>BRANDYACTION BENEFIT</span><strong id="coupon-benefit">${c.type==='정률'?c.value+'%':n(c.value)+'원'} 할인</strong><span>적용 가능 여부를 발급 전에 확인하세요.</span></div><div class="form-grid mt24">${formField('쿠폰명 *',textInput('coupon:name',c.name,'운영용 이름','required'))}${formField('쿠폰 코드 *',textInput('coupon:code',c.code,'영문 대문자·숫자','required pattern="[A-Z0-9_-]+"'))}${formField('할인 방식',selectInput('coupon:type',['정률','정액'],c.type))}${formField('할인 수치 *',`<input type="number" min="1" data-field="coupon:value" value="${c.value}" required>`)}${formField('최대 할인액 · 원',`<input type="number" min="1" data-field="coupon:cap" value="${c.cap}" required>`)}${formField('최소 주문 금액 · 원',`<input type="number" min="0" data-field="coupon:min" value="${c.min}" required>`)}${formField('발급 대상',selectInput('coupon:target',['전체 회원','신규 회원','재수강 관심 태그'],c.target))}${formField('적용 상품',selectInput('coupon:products',['유료 클래스','AI 마케팅 실전 과정','디지털 자료'],c.products))}${formField('시작일 · KST','<input type="date" data-field="coupon:start" value="2026-09-14" required>')}${formField('종료일 · KST','<input type="date" data-field="coupon:end" value="2026-09-30" required>')}${formField('총 발급 수량',`<input type="number" min="1" data-field="coupon:total" value="${c.total}" required>`)}${formField('회원당 발급 횟수','<input type="number" min="1" data-field="coupon:limit" value="1" required>')}</div><div class="checkbox-stack"><label><input type="checkbox" checked disabled>주문당 쿠폰 1개 · 중복 할인 불가</label><label><input type="checkbox" checked disabled>무료 상품 적용 제외</label></div>${note('발급 후에는 이미 사용한 주문의 할인 금액을 소급 변경하지 않습니다. 전액·부분 환불 시 쿠폰 복구 정책은 별도 확정이 필요합니다.','warning')}${formNotice()}`,btn('할인 미리 계산','data-ops="coupon-calculate"')+modalActions('coupon'),true);}
function productReviewEditor(id){const r=productReviewData.find(r=>r.id===id);showDialog('상품 후기 검토',`<div class="spread"><b>${customerData[r.customer-1].name}</b><span class="stars">${'★'.repeat(r.rating)}</span></div><p class="meta mt8">${r.product} · 구매 연결 예시</p><div class="answer-copy mt16">${r.body}</div><p class="meta mt8">작성자 원문 · 관리자 임의 수정 불가</p><div class="mt24">${formField('게시 상태',selectInput('review:status',['게시 대기','게시 중','숨김'],r.status))}${formField('노출 변경 사유 *',textArea('review:reason','',3,'required placeholder="숨김·게시 여부의 판단 근거"'))}${formField('운영자 답변',textArea('review:reply','',4,'placeholder="원문과 분리된 공개 답변"'))}</div>${formNotice()}`,modalActions('review'),true);}
function bannerEditor(id){const b=bannerData.find(b=>b.id===+id)||{name:'',copy:'',link:'',start:'',end:'',placement:'메인 최상단',status:'비공개'};showDialog('메인 배너 등록·수정',`<div class="banner-preview">${esc(b.copy||'배너 카피 미리보기').replace('\n','<br>')}</div><div class="form-grid mt24">${formField('배너명 *',textInput('banner:name',b.name,'운영용 이름','required'))}${formField('노출 위치',selectInput('banner:placement',['메인 최상단','메인 중단'],b.placement))}${formField('배너 카피',textArea('banner:copy',b.copy,2),'',true)}</div>${uploadBox('banner-pc','PC 배너 이미지','image/png,image/jpeg,image/webp','권장 1920×640 · 비율 3:1')}${uploadBox('banner-mobile','모바일 배너 이미지','image/png,image/jpeg,image/webp','권장 750×900 · 핵심 문구 안전 영역 확인')}${formField('이미지 대체 텍스트 *',textInput('banner:alt',b.copy.replace('\n',' '),'배너의 핵심 메시지','required'))}${formField('연결 주소 *',textInput('banner:link',b.link,'/class/상품주소 또는 https://...','required'))}<div class="form-grid">${formField('노출 시작 · KST',`<input type="datetime-local" data-field="banner:start" value="${b.start}">`)}${formField('노출 종료 · KST',`<input type="datetime-local" data-field="banner:end" value="${b.end}">`)}${formField('상태',selectInput('banner:status',['비공개','예약','게시 중'],b.status))}${formField('열기 방식',selectInput('banner:target',['같은 창','새 창'],'같은 창'))}</div><label class="checkline"><input type="checkbox" required>PC·모바일 이미지와 대상 상품의 공개 상태 확인</label>${formNotice()}`,modalActions('banner'),true);}
function articleEditor(id){const a=articleData.find(a=>a.id===+id)||{title:'',category:'업무 인사이트',author:'운영팀',slug:'',status:'초안',body:''};showDialog('아티클 편집',`${formField('제목 *',textInput('article:title',a.title,'아티클 제목','required'))}<div class="form-grid">${formField('카테고리',selectInput('article:category',['업무 인사이트','마케팅','실행 기록'],a.category))}${formField('작성자',textInput('article:author',a.author))}</div>${uploadBox('article-cover','대표 이미지 등록','image/png,image/jpeg,image/webp','목록·공유 카드용 대표 이미지')}${formField('본문 · HTML',textArea('article:body',a.body,8,'class="code-editor" required'))}${btn('본문 미리보기','data-ops="article-preview"','small')}${formField('URL 주소 (slug) *',textInput('article:slug',a.slug,'영문 소문자·숫자·하이픈','required pattern="[a-z0-9-]+"'))}${formField('검색 제목',textInput('article:seoTitle',a.title))}${formField('검색 설명',textArea('article:seoDescription','',2))}<div class="form-grid">${formField('게시 상태',selectInput('article:status',['초안','예약','게시 중'],a.status))}${formField('예약 시각 · KST','<input type="datetime-local" data-field="article:schedule">')}</div><label class="checkline"><input type="checkbox" data-field="article:featured" ${a.featured?'checked':''}>메인 대표 아티클 노출</label>${formNotice()}`,modalActions('article'),true);}
function storyEditor(id){const s=storyData.find(s=>s.id===+id)||{title:'',name:'',source:'직접 등록',kind:'텍스트',body:'',consent:false,status:'초안'};showDialog('홈페이지 고객 후기 편집',`${formField('사례 제목 *',textInput('story:title',s.title,'고객 경험이 드러나는 제목','required'))}<div class="form-grid">${formField('노출 이름 *',textInput('story:name',s.name,'예: 김○○','required'))}${formField('형식',selectInput('story:kind',['텍스트','영상'],s.kind))}</div>${formField('원본 출처 *',textInput('story:source',s.source,'상품 후기 번호 / 인터뷰 등','required'))}${formField('인용 내용 *',textArea('story:body',s.body,5,'required'))}${uploadBox('story-cover','고객 사례 대표 이미지','image/png,image/jpeg,image/webp','고객 노출 동의 확인 후 사용')}${formField('영상 주소',textInput('story:video','','https://... · URL 입력만, 시안에서 재생하지 않음'))}<label class="checkline"><input type="checkbox" data-field="story:consent" ${s.consent?'checked':''}>이름·사진·영상·인용문 노출 동의 확인</label>${formField('동의 확인 기록',textInput('story:consentRef','','동의 일자 / 증빙 문서 식별자'))}${formField('게시 상태',selectInput('story:status',['초안','동의 확인','게시 중'],s.status))}${note('동의 미확인 사례는 게시·대표 노출을 막는 설계입니다. 원본 상품 후기의 평점이나 원문은 여기서 바꾸지 않습니다.','warning')}${formNotice()}`,modalActions('story'),true);}
function refundEditor(id){const o=orderData.find(o=>o.id===id),max=o.paid-o.refunded;showDialog('환불 검토 · 실행 없음',`<h3>${o.number}</h3><p class="meta mt8">${customerData[o.customer-1].name} · ${o.product}</p><div class="order-money total mt16"><span>남은 결제액</span><b>${n(max)}원</b></div>${formField('검토 환불액 · 원 *',`<input type="number" min="1" max="${max}" step="1" value="${max}" data-field="refund:amount" required>`)}${formField('환불 사유 *',textArea('refund:reason','',3,'required'))}${formField('수강 권한 처리안',selectInput('refund:access',['전액 환불 완료 후 권한 회수','부분 환불 · 남은 권한 별도 확인'],'전액 환불 완료 후 권한 회수'))}${formField('쿠폰 처리안',selectInput('refund:coupon',['적용 쿠폰 없음','복구 대상 확인','미복구 · 사유 기록'],o.discount?'복구 대상 확인':'적용 쿠폰 없음'))}<label class="checkline"><input type="checkbox" required>환불액·수강 권한·쿠폰 처리 영향을 확인했습니다.</label>${note('PG 환불은 실행하지 않습니다. 요청 → 승인 → PG 처리 결과 → 권한 반영 결과를 분리하고 중복 환불을 막아야 합니다.','warning')}`,modalActions('refund'),true);}
function codeEditor(kind='custom'){showDialog(kind==='ga4'?'GA4 측정 설정':'추가 코드 초안',kind==='ga4'?`${formField('GA4 측정 ID *',textInput('code:measurement','','G-XXXXXXXXXX','required pattern="G-[A-Z0-9]+"'))}${note('형식 검토용입니다. GA4 수집·네트워크 요청은 발생하지 않습니다.')}`:`${formField('코드 이름 *',textInput('code:name','','용도를 알 수 있는 이름','required'))}<div class="form-grid">${formField('삽입 위치',selectInput('code:position',['Head','Body 시작','Body 끝'],'Head'))}${formField('적용 범위',selectInput('code:scope',['전체 페이지','랜딩페이지만','상품 상세페이지만'],'랜딩페이지만'))}</div>${formField('코드 원문 *',textArea('code:source','',8,'class="code-editor" spellcheck="false" required placeholder="검토할 코드 입력 · 실행되지 않습니다."'))}${formField('등록 목적·책임자 *',textInput('code:reason','','측정 목적 / 운영 책임자','required'))}<label class="checkline"><input type="checkbox" required>기존 픽셀 중복·개인정보 전송·적용 권한 확인</label>${note('입력한 코드는 텍스트로만 취급합니다. 운영 적용은 검토·테스트·권한 승인 이후 별도 개발 단계입니다.','warning')}`,modalActions('code'),true);}

let lessonSnapshot=null;
const localAssets=new Map();
function dirtyLesson(){ux.lessonDirty=true;const el=$('#editor-dirty');if(el)el.textContent='변경 사항 있음 · 이 시안 안에서만 유지됩니다.';}
function refreshQuiz(){const el=$('#quiz-editor');if(el)el.innerHTML=quizEditor(lesson());dirtyLesson();}
function refreshLessonPreview(){const l=lesson(),el=$('#lesson-live-preview');if(el)el.innerHTML=`<div class="safe-html-preview"><span class="badge">${esc(l.tag)} · ${l.minutes}분</span><h2>${esc(l.title)}</h2><p>${esc(l.intro)}</p><div id="lesson-rich-content">${safeRich(l.content)}</div><div class="tip-preview">${esc(l.tip)}</div></div>`;}
function openLesson(id){ux.lessonId=id;lessonSnapshot=JSON.stringify(lesson());ux.lessonDirty=false;go('learning-editor');}
function newLesson(){const id=Math.max(...lessonData.map(l=>l.id))+1;lessonData.push({id,title:'새 학습',day:id,week:ux.learnWeek||1,tag:'기초',key:'basic',minutes:5,published:false,intro:'',content:'',tip:'',quiz:[]});openLesson(id);dirtyLesson();}
function newProduct(){const id='new';let p=productData.find(p=>p.id===id);if(!p){p={id,name:'',type:'유료 클래스',state:'작성 중',price:0,regular:0,cohort:'미연결',resource:'구매자 전용',subtitle:'',detail:'',files:[],slug:'',start:'',end:''};productData.push(p);}ux.productId=id;ux.productTab='basic';go('product-editor');}
function validLesson(){const l=lesson();if(!l.title.trim()||!l.content.trim()){toast('제목과 학습 본문을 입력해 주세요.');return false;}if(!Number.isInteger(l.day)||l.day<1||!Number.isInteger(l.week)||l.week<1||l.week>6||l.minutes<1){toast('일차·주차(1–6)·소요 시간을 확인해 주세요.');return false;}if(lessonData.some(x=>x.id!==l.id&&x.day===l.day)){toast('같은 일차에 등록된 학습이 있습니다. 일차를 조정해 주세요.');return false;}if(l.quiz.some(q=>!q.q.trim()||q.options.some(o=>!o.trim())||q.answer===null||q.answer<0||q.answer>=q.options.length||!q.explanation.trim())){toast('모든 퀴즈의 질문·선택지·정답·해설을 확인해 주세요.');return false;}return true;}
function validProduct(){const p=product();if(!p.name.trim()||!p.detail.trim()||!p.slug.trim()){toast('상품명·상세페이지·상품 주소를 입력해 주세요.');return false;}if(p.price<0||p.regular<p.price||!Number.isInteger(p.price)||!Number.isInteger(p.regular)){toast('판매가·정가를 0원 이상의 정수로 확인해 주세요.');return false;}if(p.type==='무료 클래스'&&p.price!==0){toast('무료 클래스 판매가는 0원이어야 합니다.');return false;}if(!p.start||!p.end||p.start>p.end){toast('모집 시작일과 마감일을 확인해 주세요.');return false;}if(!/^[a-z0-9-]+$/.test(p.slug)||productData.some(x=>x.id!==p.id&&x.slug===p.slug)){toast('상품 주소는 중복되지 않는 영문 소문자·숫자·하이픈으로 입력하세요.');return false;}if(p.type!=='디지털 자료'&&['미연결','해당 없음'].includes(p.cohort)){toast('클래스에 연결할 기수를 선택해 주세요.');return false;}return true;}
function publishPreview(kind){if(kind==='lesson'&&!validLesson()||kind==='product'&&!validProduct())return;const p=kind==='lesson'?lesson():product();showDialog('공개 전 확인',`<h3>${esc(p.title||p.name)}</h3><div class="setting-line"><span>예정 상태</span><b>${kind==='lesson'?(p.published?'공개':'비공개'):esc(p.state)}</b></div>${kind==='lesson'?`<div class="setting-line"><span>학습·퀴즈</span><b>Day ${p.day} · ${p.quiz.length}문항</b></div>`:`<div class="setting-line"><span>판매가·자료</span><b>${n(p.price)}원 · ${p.files.length}개</b></div><div class="setting-line"><span>자료 기본 권한</span><b>${esc(p.resource)}</b></div>`}<label class="checkline"><input type="checkbox" id="final-publish-check">내용·노출 대상·기존 수강생 영향 확인</label>${formNotice()}`,btn('계속 편집','data-action="close-dialog"')+btn('확인 완료 시연',`data-finish-publish="${kind}"`,'primary'));}
function opsFormValues(){return Object.fromEntries($$('#dialog [data-field]').map(el=>[el.dataset.field,el.type==='checkbox'?el.checked:el.value]));}
function validateModal(kind){const els=$$('#dialog input, #dialog textarea, #dialog select');for(const el of els){if(!el.checkValidity()){el.reportValidity();return false;}}const v=opsFormValues(),start=v[kind+':start'],end=v[kind+':end'];if(start&&end&&start>end){toast('시작 시점은 종료 시점보다 빨라야 합니다.');return false;}if(kind==='coupon'&&v['coupon:type']==='정률'&&+v['coupon:value']>100){toast('정률 할인은 1–100%로 입력해 주세요.');return false;}if(kind==='banner'&&v['banner:status']==='예약'&&(!start||!end)){toast('예약 배너의 시작·종료 시점을 입력해 주세요.');return false;}if(kind==='banner'&&!/^(\/[^/]|https:\/\/)/.test(v['banner:link'])){toast('내부 경로나 https 주소를 입력해 주세요.');return false;}if(kind==='article'&&v['article:status']==='예약'&&!v['article:schedule']){toast('예약 게시 시각을 지정해 주세요.');return false;}if(kind==='story'&&v['story:status']==='게시 중'&&(!v['story:consent']||!v['story:consentRef'].trim())){toast('게시 전에 노출 동의와 확인 기록을 입력해 주세요.');return false;}return true;}
function confirmOps(kind){if(!validateModal(kind))return;const v=opsFormValues();showDialog('입력 내용 검토 완료',`<div class="notice neutral">필수 항목과 기본 조건을 확인했습니다. 실제 저장·발행·발급·환불·권한 변경은 실행하지 않았습니다.</div><div class="mt24">${Object.entries(v).filter(([k,val])=>val!==''&&!['body','source','detail'].includes(k.split(':')[1])).slice(0,8).map(([k,val])=>`<div class="setting-line"><span class="meta">${esc(k)}</span><b>${esc(String(val))}</b></div>`).join('')}</div><p class="meta mt16">운영 적용 시 변경 전후 값·처리자·시각을 이력으로 남기는 설계입니다.</p>`,btn('목록 확인','data-action="close-dialog"','primary'));}
const opsActions={
 'new-lesson':newLesson,'new-product':newProduct,'cohort-editor':()=>cohortEditor(),
 'quiz-add':()=>{lesson().quiz.push({q:'',options:['',''],answer:null,explanation:''});refreshQuiz();},
 'lesson-preview':()=>{const l=lesson();showDialog('학습자 미리보기',`<div class="safe-html-preview"><span class="badge">Day ${l.day} · ${esc(l.tag)}</span><h2>${esc(l.title)}</h2><p>${esc(l.intro)}</p>${safeRich(l.content)}<div class="tip-preview">${esc(l.tip)}</div><h3>확인 퀴즈 ${l.quiz.length}문항</h3>${l.quiz.map((q,i)=>`<div class="question-editor"><b>${i+1}. ${esc(q.q)}</b>${q.options.map((o,j)=>`<label class="checkline"><input type="radio" name="preview-answer-${i}">${esc(o)}</label>`).join('')}</div>`).join('')}</div>`,btn('편집으로','data-action="close-dialog"','primary'),true);},
 'detail-preview':()=>showDialog('상세 본문 미리보기',`<div class="safe-html-preview">${safeRich(product().detail)}</div>`,btn('닫기','data-action="close-dialog"','primary'),true),
 'product-preview':()=>{const p=product();showDialog('고객 화면 미리보기',`<div class="preview-cover"><p>BRANDYACTION EDU</p><h2>${esc(p.name)}</h2></div><div class="spread mt24"><h2>${p.price?n(p.price)+'원':'무료'}</h2>${btn(p.price?'수강 신청하기':'무료 수강 신청하기','data-demo="신청 CTA 디자인 예시입니다. 실제 신청·결제를 진행하지 않습니다."','primary')}</div>${p.type==='무료 클래스'?'<p class="meta mt8">별도 구매 옵션 없이 신청 CTA를 바로 표시합니다.</p>':''}<div class="safe-html-preview mt24">${safeRich(p.detail)}</div><h3 class="mt24">무료·제공 자료</h3>${p.files.map(f=>`<div class="asset-row"><span class="file-icon">FILE</span><div><b>${esc(f)}</b><p>${esc(p.resource)}</p></div>${btn('다운로드','data-demo="자료 다운로드 위치·권한 UI입니다. 원본 자료는 연결되지 않았습니다."','small')}</div>`).join('')||'<p class="meta mt8">등록된 자료가 없습니다.</p>'}`,btn('편집으로','data-action="close-dialog"','primary'),true);},
 'draft':b=>{if(b.dataset.kind==='lesson'){ux.lessonDirty=false;lessonSnapshot=JSON.stringify(lesson());}const el=$('#editor-dirty');if(el)el.textContent='시안 안에 임시 반영됨 · 새로고침하면 초기화됩니다.';toast('입력 내용을 이 열린 HTML 안에서만 유지합니다. 실제 저장하지 않았습니다.');},
 'publish':b=>publishPreview(b.dataset.kind),
 'tag-sample':()=>toast('대상 검토 UI: 자동 조건·적용 기간·기존 태그 유지 여부를 확인합니다. 실제 회원 행동을 조회하지 않습니다.'),
 'coupon-calculate':()=>{if(!validateModal('coupon'))return;const v=opsFormValues(),amount=1490000,discount=amount<+v['coupon:min']?0:Math.min(amount,v['coupon:type']==='정률'?Math.min(Math.floor(amount*+v['coupon:value']/100),+v['coupon:cap']):+v['coupon:value']);toast(`예시 주문 ${n(amount)}원 기준 할인 ${n(discount)}원 / 예상 결제 ${n(amount-discount)}원 · 대상 조건은 별도 검토`);},
 'article-preview':()=>{const value=$('[data-field="article:body"]').value;const target=$('#article-inline-preview')||document.createElement('div');target.id='article-inline-preview';target.className='safe-html-preview mt16';target.innerHTML=safeRich(value);if(!target.isConnected)$('#dialog .dialog-body').append(target);target.scrollIntoView({block:'nearest'});},
 'code-history':()=>showDialog('검색·코드 변경 이력',`<div class="order-history"><div><b>v3 · 검토 중</b><p>검색 정보·인증 코드·관리형 측정 분리 · UI 예시</p></div><div><b>v2 · 이전 기준</b><p>픽셀·이벤트 단일 설정 화면 · UI 예시</p></div></div>${note('운영 적용·검토자·변경 전후·이전 버전 복원 전 확인을 기록할 영역입니다.')}`,btn('닫기','data-action="close-dialog"','primary')),
 'seo-save':()=>{const title=$('[data-field="seo:title"]').value.trim(),description=$('[data-field="seo:description"]').value.trim(),url=$('[data-field="seo:canonical"]').value;if(!title||!description||!/^https:\/\//.test(url)){toast('제목·설명·https 대표 주소를 확인해 주세요.');return;}showDialog('검색 정보 변경 확인',`<div class="snippet"><h3>${esc(title)}</h3><p>${esc(description)}</p></div>${note('검색 노출 차단을 선택했다면 운영 사이트 전체에 미치는 영향을 먼저 검토하세요. 이 시안은 메타 태그를 발행하지 않습니다.','warning')}`,btn('확인','data-action="close-dialog"','primary'));},
 'verification-save':()=>{const vals=$$('[data-field^="verify:"]').map(t=>t.value.trim());if(!vals.some(Boolean)||vals.some(v=>/[<>]/.test(v))){toast('태그 전체가 아닌 인증 content 값만 입력해 주세요.');return;}toast('인증 값 입력 형태를 확인했습니다. 실제 소유 확인은 진행하지 않았습니다.');},
 'custom-code':()=>codeEditor(),'pixel-settings':()=>{state.settingsTab='tracking';go('settings');}
};

// 상품·클래스·주문 조회 조건 (정적 예시 데이터에만 적용)
productData.push({id:'p5',name:'AI 온보딩 챌린지',type:'유료 클래스',state:'판매 중',price:99000,regular:99000,cohort:'1기',resource:'구매자 전용',subtitle:'30일 동안 만드는 AI 업무 습관',detail:'<h2>AI 업무의 시작</h2><p>기존 미션 관리의 1기 예시와 연결된 상품입니다.</p>',files:[],slug:'ai-onboarding',start:'2026-09-01',end:'2026-09-30'});
const filterSelect=(key,label,options,value)=>`<label class="select-filter"><span>${esc(label)}</span><select data-filter="${key}" aria-label="${esc(label)} 선택">${options.map(([id,name])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`;
const productOptions=(all=false)=>[...(all?[['all','전체 상품']]:[]),...productData.map(p=>[p.id,p.name])];
function filteredOrders(){return orderData.filter(o=>{const date=o.date.slice(0,10).replaceAll('.','-');const productId=({1:'p1',2:'p1',3:'p3',4:'p1',5:'p4'})[o.id];return (ux.orderProduct==='all'||productId===ux.orderProduct)&&(!ux.orderFrom||date>=ux.orderFrom)&&(!ux.orderTo||date<=ux.orderTo)&&(ux.orderStatus==='all'||o.payment===ux.orderStatus||o.refund===ux.orderStatus)&&(!ux.orderQuery||(o.number+customerData[o.customer-1].name+o.product).includes(ux.orderQuery));});}
function orderDateControls(){return `<section class="order-date-panel" aria-label="주문 날짜 조회"><div class="date-range"><label class="select-filter"><span>주문일 시작 · KST</span><input type="date" id="order-from" value="${ux.orderFrom}" aria-label="주문일 시작"></label><span class="date-separator">–</span><label class="select-filter"><span>주문일 종료 · KST</span><input type="date" id="order-to" value="${ux.orderTo}" aria-label="주문일 종료"></label>${btn('조회','data-ops="order-date-search"','primary')}${btn('전체 기간','data-ops="order-date-reset"')}</div><p class="meta mt8">적용 기간: ${ux.orderFrom||'전체 시작일'} ~ ${ux.orderTo||'전체 종료일'} · 주문일 기준, 종료일 포함 · 예시 데이터</p><p id="order-date-error" class="field-error" role="alert" hidden></p></section>`;}
function missionProductScope(){const p=productData.find(p=>p.id===ux.missionProduct);return `<div class="scope product-scope">${filterSelect('missionProduct','상품',productOptions(),ux.missionProduct)}<div><div class="scope-title">${esc(p?.name||'상품을 선택하세요.')}</div><p>${ux.missionProduct==='p5'?'1기 · 6주 · 30개 미션 · 예시 수강생 13명':'선택한 상품의 연결 현황'}</p></div><span class="spacer"></span>${badge(ux.missionProduct==='p5'?'진행 중':'연결 데이터 없음',ux.missionProduct==='p5'?'green':'outline')}</div>`;}
for(const route of ['members','reviews','missions']){const original=views[route];views[route]=()=>ux.missionProduct==='p5'?original().replace(scope(),missionProductScope()):head(routes[route][0],'선택한 상품의 학습 운영 현황을 확인합니다.')+missionProductScope()+panel('상품별 운영 현황',empty('연결된 예시 데이터가 없습니다.','AI 온보딩 챌린지를 선택하면 기존 회원·제출물·미션 예시를 확인할 수 있습니다.'));}
opsActions['order-date-search']=()=>{const a=$('#order-from').value,b=$('#order-to').value;if(a&&b&&a>b){const el=$('#order-date-error');el.textContent='시작일은 종료일보다 늦을 수 없습니다.';el.hidden=false;return;}ux.orderFrom=a;ux.orderTo=b;refresh();};
opsActions['order-date-reset']=()=>{ux.orderFrom='';ux.orderTo='';refresh();};

// EXTENSION EVENTS
document.addEventListener('click',e=>{
 const b=e.target.closest('button,a');if(!b||b.disabled)return;
 const d=b.dataset;let handle=null;
 if(d.ops&&opsActions[d.ops])handle=()=>opsActions[d.ops](b);
 if(d.learnWeek!==undefined)handle=()=>{ux.learnWeek=+d.learnWeek;refresh();};
 if(d.lesson)handle=()=>openLesson(+d.lesson);
 if(d.product)handle=()=>{ux.productId=d.product;ux.productTab='basic';go('product-editor');};
 const xt={productEditorTab:'productTab',tagMode:'tagMode',seoTab:'seoTab'};
 if(xt[d.tab])handle=()=>{ux[xt[d.tab]]=d.value;refresh();};
 if(d.tab==='missionTab'&&d.value==='learning')handle=()=>go('learning');
 if(d.editLearning)handle=()=>d.editLearning==='new'?newLesson():openLesson(+d.editLearning);
 if(d.removeQuiz!==undefined)handle=()=>showDialog('퀴즈 삭제 확인',`<p>${+d.removeQuiz+1}번 문제와 선택지를 편집본에서 제외합니다.</p>${note('기존 제출 답변과 정답 기준은 실제 개발에서 버전별 보존이 필요합니다.','warning')}`,btn('취소','data-action="close-dialog"')+btn('시안에서 제외',`data-confirm-remove-quiz="${d.removeQuiz}"`,'danger'));
 if(d.confirmRemoveQuiz!==undefined)handle=()=>{lesson().quiz.splice(+d.confirmRemoveQuiz,1);closeDialog();refreshQuiz();};
 if(d.addOption!==undefined)handle=()=>{lesson().quiz[+d.addOption].options.push('');refreshQuiz();};
 if(d.removeOption!==undefined)handle=()=>{const [i,j]=d.removeOption.split(':').map(Number),q=lesson().quiz[i];if(q.options.length<=2)return;q.options.splice(j,1);q.answer=q.answer===j?null:q.answer>j?q.answer-1:q.answer;refreshQuiz();};
 if(d.customer)handle=()=>customerDrawer(+d.customer);
 if(d.customerTags)handle=()=>customerTags(+d.customerTags);
 if(d.customerStatus)handle=()=>customerStatus(+d.customerStatus);
 if(d.tagEdit)handle=()=>tagEditor(d.tagEdit);
 if(d.coupon)handle=()=>couponEditor(d.coupon);
 if(d.productReview)handle=()=>productReviewEditor(+d.productReview);
 if(d.banner)handle=()=>bannerEditor(d.banner);
 if(d.bannerMove)handle=()=>{const i=bannerData.findIndex(x=>x.id===+d.bannerMove);if(i>0){[bannerData[i-1],bannerData[i]]=[bannerData[i],bannerData[i-1]];refresh();toast('시안에서 순서를 바꿨습니다. 실제 배너에는 반영하지 않았습니다.');}};
 if(d.article)handle=()=>articleEditor(d.article);
 if(d.story)handle=()=>storyEditor(d.story);
 if(d.order)handle=()=>orderDrawer(+d.order);
 if(d.refund)handle=()=>refundEditor(+d.refund);
 if(d.cohortName)handle=()=>cohortEditor(d.cohortName);
 if(d.codeEntry)handle=()=>{if(d.codeEntry==='1')codeEditor('ga4');else{ux.seoTab='verification';refresh();}};
 if(d.resourceIndex!==undefined)handle=()=>showDialog('자료 다운로드 설정',`<h3>${esc(product().files[+d.resourceIndex])}</h3>${formField('다운로드 권한',selectInput('file:permission',['누구나 다운로드','로그인 회원','신청 완료 회원','구매자 전용'],product().resource))}${formField('노출 이름',textInput('file:name',product().files[+d.resourceIndex]))}${formNotice()}`,modalActions('file'));
 if(d.confirmOps)handle=()=>confirmOps(d.confirmOps);
 if(d.finishPublish)handle=()=>{if(!$('#final-publish-check').checked){toast('공개 전 확인 항목에 체크해 주세요.');return;}if(d.finishPublish==='lesson'){ux.lessonDirty=false;lessonSnapshot=JSON.stringify(lesson());}closeDialog();toast('공개 전 검토를 완료했습니다. 실제 서비스에는 발행하지 않았습니다.');};
 if(handle){e.preventDefault();e.stopImmediatePropagation();handle();}
},true);
document.addEventListener('input',e=>{
 const t=e.target,d=t.dataset;
 if(d.uxSearch){ux[d.uxSearch]=t.value;const pos=t.selectionStart;refresh();const next=$(`[data-ux-search="${d.uxSearch}"]`);next?.focus();next?.setSelectionRange(pos,pos);}
 if(d.lessonField){if(!lessonSnapshot)lessonSnapshot=JSON.stringify(lesson());lesson()[d.lessonField]=t.type==='checkbox'?t.checked:t.type==='number'?Number(t.value):t.value;dirtyLesson();refreshLessonPreview();}
 if(d.quizQ!==undefined){lesson().quiz[+d.quizQ].q=t.value;dirtyLesson();}
 if(d.optionQ!==undefined){lesson().quiz[+d.optionQ].options[+d.optionI]=t.value;dirtyLesson();}
 if(d.explanation!==undefined){lesson().quiz[+d.explanation].explanation=t.value;dirtyLesson();}
 if(d.field?.startsWith('product:')){product()[d.field.split(':')[1]]=t.type==='number'?Number(t.value):t.value;const el=$('#editor-dirty');if(el)el.textContent='변경 사항 있음 · 시안 안에서만 유지됩니다.';}
 if(d.field==='seo:title')$('#seo-title-preview').textContent=t.value;
 if(d.field==='seo:description')$('#seo-description-preview').textContent=t.value;
 if(d.field==='coupon:value'||d.field==='coupon:type'){const v=opsFormValues();$('#coupon-benefit').textContent=(v['coupon:type']==='정률'?v['coupon:value']+'%':n(v['coupon:value'])+'원')+' 할인';}
});
document.addEventListener('change',async e=>{
 const t=e.target,d=t.dataset;
 if(d.filter){ux[d.filter]=t.value;if(d.filter==='missionProduct'){state.selected.clear();state.currentReview=null;state.memberSearch='';state.reviewSearch='';state.memberTab='all';state.reviewTab='pending';state.week=1;state.missionWeek=1;}refresh();}
 if(d.answerFor!==undefined){lesson().quiz[+d.answerFor].answer=+t.value;refreshQuiz();}
 if(d.featureReview){productReviewData.find(r=>r.id===+d.featureReview).featured=t.checked;toast('시안에서 대표 노출 선택만 바꿨습니다.');}
 if(d.featureStory){storyData.find(s=>s.id===+d.featureStory).featured=t.checked;toast('시안에서 대표 노출 선택만 바꿨습니다.');}
 if(d.field==='product:type'){if(t.value==='무료 클래스'){product().price=0;product().regular=0;}refresh();}
 if(d.localFile){const file=t.files[0];if(!file)return;const slot=$('#file-'+d.localFile);if(file.size>20*1024*1024){slot.textContent='이 시안에서는 20MB 이하 파일을 선택해 주세요.';return;}slot.innerHTML=`<div class="file-selected">${icon('check')}<span>${esc(file.name)} · ${n(file.size)} bytes · 로컬 선택 완료</span></div>`;
  if(d.localFile==='product-html'){if(!/\.html?$/i.test(file.name)){slot.textContent='HTML 파일을 선택해 주세요.';return;}const text=await file.text();product().detail=text;const field=$('[data-field="product:detail"]');if(field)field.value=text;toast('HTML 원문을 읽었습니다. 미리보기에서는 안전한 본문 태그만 표시합니다.');}
  else if(d.localFile==='product-resource'){product().files.push(file.name);toast('자료 파일명을 시안에 추가했습니다. 업로드·다운로드 서비스는 연결하지 않았습니다.');}
  else if(/^image\/(png|jpeg|webp)$/.test(file.type)){if(localAssets.has(d.localFile))URL.revokeObjectURL(localAssets.get(d.localFile));const url=URL.createObjectURL(file);localAssets.set(d.localFile,url);const img=document.createElement('img');img.src=url;img.alt=file.name;img.style.cssText='max-width:100%;max-height:240px;object-fit:contain;margin-top:12px;border-radius:8px';slot.append(img);}
 }
});
