import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const base=fs.readFileSync(new URL('./src/app.js',import.meta.url),'utf8');
const ops=fs.readFileSync(new URL('./src/operations.js',import.meta.url),'utf8');
const articleUpdate=['article-banner.js','articles-update.js'].map(f=>fs.readFileSync(new URL('./src/'+f,import.meta.url),'utf8')).join('\n');
const code=base+'\n'+ops+'\n'+articleUpdate;
new vm.Script(code);
const staticCode=base.slice(0,base.indexOf("document.addEventListener('click'"))+ops.slice(0,ops.indexOf('// EXTENSION EVENTS'))+articleUpdate.split('// ARTICLE ADMIN EVENTS')[0];
const context=vm.createContext({console,URL});
vm.runInContext(staticCode,context);
const run=s=>vm.runInContext(s,context);
const states=[['overview',{}],['members',{memberTab:'all'}],['members',{memberTab:'inactive',week:2}],['members',{memberTab:'pending',week:3}],['members',{memberTab:'today',week:6}],['reviews',{reviewTab:'pending'}],['reviews',{reviewTab:'returned'}],['reviews',{reviewTab:'approved'}],['reviews',{reviewTab:'all'}],['missions',{missionTab:'missions',missionWeek:1}],['missions',{missionTab:'missions',missionWeek:6}],['missions',{missionTab:'learning'}],['missions',{missionTab:'ongoing'}],['questions',{questionTab:'open'}],['questions',{questionTab:'done'}],['analytics',{analyticsTab:'ads',campaign:'cold'}],['analytics',{analyticsTab:'ads',campaign:'warm'}],['analytics',{analyticsTab:'sections'}],['analytics',{analyticsTab:'cta'}],['analytics',{analyticsTab:'trend'}],['metrics',{}],['settings',{settingsTab:'tracking'}],['settings',{settingsTab:'criteria'}],['settings',{settingsTab:'operations'}]];
const knownRoutes=run('Object.keys(routes)');
assert.equal(knownRoutes.length,22);
assert(run("navGroups.find(g=>g[0]==='마케팅 관리')[1].includes('settings')"));
for(const r of ['members','reviews','missions']){assert(run(`views['${r}']().includes('data-filter="missionProduct"')`));run("ux.missionProduct='p1'");assert(run(`views['${r}']().includes('연결된 예시 데이터가 없습니다.')`));run("ux.missionProduct='p5'");}
run("ux.productType='무료 클래스'");assert(run("productList().includes('data-product=\"p2\"')"));assert(!run("productList().includes('data-product=\"p1\"')"));run("ux.productType='all'");
run("ux.customerClass='AI 마케팅 실전 · 4기'");assert(run("customerList().includes('5명 표시')"));run("ux.customerClass='all'");
run("ux.orderFrom='2026-09-10';ux.orderTo='2026-09-10';ux.orderProduct='p1'");assert.equal(run('filteredOrders().map(o=>o.id).join()'),'1,4');assert.equal(run('filteredOrders().reduce((s,o)=>s+o.paid,0)'),1490000);assert(run("ordersView().includes('1,490,000')"));run("ux.orderProduct='p2'");assert.equal(run('filteredOrders().length'),0);assert(run("ordersView().includes('해당 주문이 없습니다.')"));run("ux.orderFrom='';ux.orderTo='';ux.orderProduct='all'");
assert(run("seoView().includes('class=\"search-visibility\"')"));
const defaultState=run('JSON.stringify(state)'),defaultUX=run('JSON.stringify(ux)');
const expansionStates=[...knownRoutes.filter(k=>!['overview','members','reviews','missions','questions','analytics','metrics','settings'].includes(k)).map(k=>[k,{}])];
for(const tab of ['basic','detail','resources','access','publish'])for(const id of ['p1','p2','p3'])expansionStates.push(['product-editor',{productTab:tab,productId:id}]);
for(const week of [0,1,2,3,4,5,6])expansionStates.push(['learning',{learnWeek:week}]);
for(const page of [['learning','learnStatus','非'],['products','productStatus','販売'],['customers','customerStatus','なし'],['product-reviews','reviewStatus','숨김'],['orders','orderStatus','なし']])expansionStates.push([page[0],{[page[1]]:page[2]}]);
for(const tab of ['seo','verification','codes'])expansionStates.push(['seo',{seoTab:tab}]);
for(const mode of ['all','자동','수동'])expansionStates.push(['tags',{tagMode:mode}]);
let extensionRendered=0;
for(const [route,config]of expansionStates){run(`Object.assign(state,${defaultState});state.selected=new Set();Object.assign(ux,${defaultUX},${JSON.stringify(config)});state.route=${JSON.stringify(route)}`);const html=run(`views[${JSON.stringify(route)}]()`);assert(html.includes('<h1'),'missing expansion heading '+route);assert(!html.includes('undefined'),'undefined expansion '+route);assert(!html.includes('NaN'),'invalid expansion metric '+route);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,'duplicate IDs '+route);for(const m of html.matchAll(/href="#([^"]+)"/g))assert(knownRoutes.includes(m[1]),'unknown expansion route '+m[1]);for(const m of html.matchAll(/data-ops="([^"]+)"/g))assert(run(`!!opsActions[${JSON.stringify(m[1])}]`),'unknown ops action '+m[1]);extensionRendered++;}
run(`Object.assign(ux,${defaultUX})`);
run('globalThis.captured=[];showDialog=(title,body,footer)=>captured.push({title,body,footer});toast=msg=>captured.push({message:msg})');
const modalCases=['cohortEditor()','cohortEditor("5기")','tagEditor(1)','tagEditor("new")','customerDrawer(1)','customerTags(1)','customerStatus(1)','couponEditor(1)','couponEditor("new")','productReviewEditor(1)','bannerEditor(1)','bannerEditor("new")','articleEditor(1)','articleEditor("new")','storyEditor(1)','storyEditor("new")','orderDrawer(1)','orderDrawer(3)','refundEditor(1)','codeEditor()','codeEditor("ga4")'];
for(const c of modalCases){run(c);const html=run('captured.at(-1).body+captured.at(-1).footer');assert(!html.includes('undefined'),'undefined modal '+c);assert(!html.includes('NaN'),'NaN modal '+c);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,'duplicate modal ID '+c);for(const m of html.matchAll(/data-ops="([^"]+)"/g))assert(run(`!!opsActions[${JSON.stringify(m[1])}]`));}
assert.equal(run('lessonData.length'),30);assert.equal(run('lessonData.reduce((s,l)=>s+l.quiz.length,0)'),90);assert.equal(run('lessonData.filter(l=>l.published).length'),15);
assert.equal(run('productData.filter(p=>p.type==="무료 클래스").every(p=>p.price===0)'),true);
assert.equal(run('orderData.reduce((s,o)=>s+o.paid,0)'),2509000);assert.equal(run('orderData.reduce((s,o)=>s+o.refunded,0)'),29000);
assert(run('orderData.every(o=>o.refunded<=o.paid && (o.payment!=="결제 완료" ? o.paid===0 && o.access==="권한 미부여" : true))'));
assert(run('storyData.every(s=>!s.featured||(s.consent&&s.status==="게시 중"))'));
assert.equal(run('validLesson()'),true);run('lesson().quiz[0].answer=null');assert.equal(run('validLesson()'),false);run('lesson().quiz[0].answer=0');
assert.equal(run('validProduct()'),true);run('product().price=-1');assert.equal(run('validProduct()'),false);run('product().price=1490000');
run('product().name="<img src=x onerror=evil()>";lesson().tag="<img src=x onerror=evil()>"');assert(!run('productList()').includes('<img src=x'));assert(!run('learningEditor()').includes('<img src=x'));run('product().name="사업자를 위한 AI 마케팅 실전 과정";lesson().tag="기초"');
run(`Object.assign(state,${defaultState});state.selected=new Set();Object.assign(ux,${defaultUX})`);
let controls=0;
for(const [route,config] of states){run(`Object.assign(state,${JSON.stringify(config)})`);const html=run(`views[${JSON.stringify(route)}]()`);assert(html.includes('<h1'),'missing heading '+route);assert(!html.includes('undefined'),'undefined content '+route);assert(!html.includes('NaN'),'invalid metric '+route);const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert(ids.length===new Set(ids).size,'duplicate IDs '+route);for(const m of html.matchAll(/href="#([^"]+)"/g))assert(knownRoutes.includes(m[1]),'unknown route '+m[1]);for(const m of html.matchAll(/data-action="([^"]+)"/g)){assert(run(`!!actions[${JSON.stringify(m[1])}]`)||m[1]==='select-all','missing action '+m[1]);controls++;}}
assert.equal(run('members.length'),13);
assert.equal(run('members.filter(m=>m.last>=3).length'),3);
assert.equal(run('members.filter(m=>m.active).length'),8);
assert.equal(run("reviews.filter(r=>r.status==='pending').length"),9);
assert.equal(run("reviews.filter(r=>r.status==='returned').length"),3);
assert.equal(run("reviews.filter(r=>r.status==='approved').length"),8);
assert(run('reviews.every(r=>members[r.member-1].cells[r.day-1]===r.status)'));
assert.equal(run('adData.cold.reduce((s,x)=>s+x[2],0)'),4800);
assert.equal(run('adData.cold.reduce((s,x)=>s+x[3],0)'),384);
assert.equal(run('adData.cold.reduce((s,x)=>s+x[4],0)'),160000);
assert.equal(run('adData.cold.reduce((s,x)=>s+x[5],0)'),5600);
assert.equal(run('adData.warm.reduce((s,x)=>s+x[2],0)'),1200);
assert.equal(run('adData.warm.reduce((s,x)=>s+x[3],0)'),180);
assert.equal(run('adData.warm.reduce((s,x)=>s+x[4],0)'),32000);
assert.equal(run('adData.warm.reduce((s,x)=>s+x[5],0)'),1400);
assert(!/\bfetch\s*\(|XMLHttpRequest|sendBeacon\s*\(|localStorage\.|sessionStorage\.|document\.cookie/.test(code),'external/persistent API forbidden');
const out=new URL('./dist/',import.meta.url);let count=0;
for(const file of fs.readdirSync(out).filter(x=>x.endsWith('.html'))){const html=fs.readFileSync(new URL(file,out),'utf8');assert(html.startsWith('<!doctype html>'));assert(html.includes("connect-src 'none'"));assert(!/<script[^>]+src=|<link[^>]+href=/.test(html),'external dependency');for(const m of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);count++;}
assert.equal(count,23);
run("articleUX.tab='banner';articleUX.member=false");let banner=run('views.articles()');assert(banner.includes('data-banner-key="title"'));assert.equal((banner.match(/data-lesson-key="url"/g)||[]).length,3);assert(banner.includes('회원가입하면 바로 시청'));
run('articleUX.member=true;articleUX.lesson=2');assert(run('views.articles()').includes('03 / 03'));run('bannerDraft.enabled=false');assert(run('views.articles()').includes('상단 무료강의 숨김'));run('bannerDraft.enabled=true');
run('articleEditor(4)');assert(run('captured.at(-1).body').includes('data-article-field="videoURL"'));assert(run('captured.at(-1).body').includes('영상 아티클'));run("articleUX.form.type='글'");assert(!run('articleEditingForm()').includes('data-article-field="videoURL"'));
assert(run("articleVideoURLValid('https://youtu.be/abcdefghijk')"));assert(!run("articleVideoURLValid('https://example.com/not-youtube')"));assert(!run("articleVideoURLValid('javascript:alert(1)')"));
run("articleUX.type='영상';articleUX.query='';ux.articleStatus='all'");assert.equal((run('articleTable()').match(/class="article-type-icon video"/g)||[]).length,2);
console.log(JSON.stringify({standaloneHTML:count,representativeScreens:knownRoutes.length,renderedTemplateStates:states.length+extensionRendered,editorDialogStates:modalCases.length,checkedLegacyActionBindings:controls,extensionActionsChecked:true,validationAndEscapingChecks:true,exampleTotalsConsistent:true,networkOrPersistentAPIs:0,browserVisualQA:'not performed — static design deliverable'},null,2));
