begin;
create table public.edu_question_answers (
 id uuid primary key default gen_random_uuid(),
 sequence bigint generated always as identity,
 question_id uuid not null references public.edu_questions(id) on delete cascade,
 actor_id uuid references public.profiles(id) on delete set null,
 author_name text not null,
 source text not null check(source in ('operator','legacy')),
 expected_head uuid,
 content text not null check(content ~ '[^[:space:]]'),
 created_at timestamptz not null default clock_timestamp()
);
create index edu_question_answer_page on public.edu_question_answers(question_id,sequence desc);
create index edu_question_answer_actor on public.edu_question_answers(actor_id);
alter table public.edu_question_answers enable row level security;
revoke all on public.edu_question_answers from public,anon,authenticated;
grant select,insert on public.edu_question_answers to service_role;
grant usage on sequence public.edu_question_answers_sequence_seq to service_role;
alter table public.edu_questions add column answer_head_id uuid references public.edu_question_answers(id) on delete set null,add column is_resolved boolean not null default false;
-- Preserve the existing answer exactly; no notice is generated by this backfill.
insert into public.edu_question_answers(question_id,author_name,source,content,created_at)
 select id,'운영자','legacy',answer,coalesce(updated_at,created_at) from public.edu_questions where answer ~ '[^[:space:]]' order by created_at,id;
update public.edu_questions q set answer_head_id=a.id from public.edu_question_answers a where a.question_id=q.id;

-- New question notifications stay intact. Answer notifications now follow each
-- immutable answer instead of treating the legacy scalar as the only answer.
drop trigger edu_question_push on public.edu_questions;
create trigger edu_question_push after insert on public.edu_questions for each row execute function edu_private.queue_learning_push();
create function edu_private.record_question_answer()
returns trigger language plpgsql security invoker set search_path='' as $$
declare q public.edu_questions%rowtype;
begin
 update public.edu_questions set answer=new.content,answer_head_id=new.id,status='answered',updated_at=now() where id=new.question_id returning * into q;
 perform edu_private.learning_notice(q.user_id,'answer',new.id::text,'[질문함 답변]'||E'\n\nQ. '||q.content||E'\n\nA. '||new.content,'/my/questions');
 return new;
end; $$;
create function edu_private.capture_legacy_question_answer()
returns trigger language plpgsql security invoker set search_path='' as $$
begin
 if new.answer is distinct from old.answer and new.answer ~ '[^[:space:]]' then
  -- A thread insert has already supplied its head. Old editors change only answer.
  if new.answer_head_id is distinct from old.answer_head_id and exists(select 1 from public.edu_question_answers where id=new.answer_head_id and question_id=new.id and content=new.answer) then return new; end if;
  insert into public.edu_question_answers(question_id,author_name,source,content) values(new.id,'운영자','legacy',new.answer);
 end if;
 return new;
end; $$;
create trigger edu_question_answer_mirror after insert on public.edu_question_answers for each row execute function edu_private.record_question_answer();
create trigger edu_question_legacy_answer after update of answer on public.edu_questions for each row execute function edu_private.capture_legacy_question_answer();

create function public.edu_read_question_thread(p_actor uuid,p_question uuid,p_before bigint default null)
returns jsonb language plpgsql stable security invoker set search_path='' as $$
declare q public.edu_questions%rowtype; operator boolean; answer_rows jsonb; next_cursor text;
begin
 perform public.edu_assert_message_actor(p_actor);
 operator:=public.edu_message_operator(p_actor);
 select * into q from public.edu_questions where id=p_question;
 if not found or (not operator and (q.user_id<>p_actor or q.is_archived)) then raise exception 'QUESTION_NOT_FOUND'; end if;
 if p_before<1 then raise exception 'QUESTION_INVALID'; end if;
 with page as (
  select * from public.edu_question_answers where question_id=q.id and (p_before is null or sequence<p_before) order by sequence desc limit 21
 ), visible as (select * from page order by sequence desc limit 20)
 select coalesce((select jsonb_agg(jsonb_build_object('id',id,'authorName',author_name,'content',content,'createdAt',created_at) order by sequence) from visible),'[]'::jsonb),
  case when (select count(*) from page)>20 then (select min(sequence)::text from visible) else null end into answer_rows,next_cursor;
 return jsonb_build_object('question',jsonb_build_object('id',q.id,'title',q.title,'content',q.content,'learningContext',q.learning_context,'status',q.status,'resolved',q.is_resolved,'archived',q.is_archived,'headId',q.answer_head_id),
  'answers',answer_rows,'nextCursor',next_cursor,'canAnswer',operator and not q.is_archived);
end; $$;

create function public.edu_add_question_answer(p_actor uuid,p_question uuid,p_expected_head uuid,p_request uuid,p_content text)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare q public.edu_questions%rowtype; a public.edu_question_answers%rowtype; author text;
begin
 if p_request is null or p_content is null or length(p_content)>10000 or p_content !~ '[^[:space:]]' then raise exception 'QUESTION_INVALID'; end if;
 perform public.edu_assert_block_reviewer(p_actor);
 select * into q from public.edu_questions where id=p_question for update;
 if not found or q.is_archived then raise exception 'QUESTION_NOT_FOUND'; end if;
 perform 1 from public.profiles where id=p_actor for share;
 perform public.edu_assert_block_reviewer(p_actor);
 select * into a from public.edu_question_answers where id=p_request;
 if found then
  if a.source<>'operator' or a.question_id<>q.id or a.actor_id is distinct from p_actor or a.content<>p_content or a.expected_head is distinct from p_expected_head then raise exception 'QUESTION_REQUEST_REUSED'; end if;
  return jsonb_build_object('id',a.id,'questionId',q.id);
 end if;
 if q.answer_head_id is distinct from p_expected_head then raise exception 'QUESTION_CHANGED'; end if;
 select coalesce(nullif(full_name,''),'운영자') into author from public.profiles where id=p_actor;
 insert into public.edu_question_answers(id,question_id,actor_id,author_name,source,expected_head,content) values(p_request,q.id,p_actor,author,'operator',p_expected_head,p_content);
 return jsonb_build_object('id',p_request,'questionId',q.id);
end; $$;
create function public.edu_resolve_question(p_actor uuid,p_question uuid)
returns jsonb language plpgsql security invoker set search_path='' as $$
begin
 perform public.edu_assert_block_reviewer(p_actor);
 perform 1 from public.edu_questions where id=p_question and not is_archived for update;
 if not found then raise exception 'QUESTION_NOT_FOUND'; end if;
 perform 1 from public.profiles where id=p_actor for share;
 perform public.edu_assert_block_reviewer(p_actor);
 update public.edu_questions set is_resolved=true,status='answered',updated_at=now() where id=p_question;
 return jsonb_build_object('id',p_question,'resolved',true);
end; $$;
revoke all on function edu_private.record_question_answer(),edu_private.capture_legacy_question_answer(),public.edu_read_question_thread(uuid,uuid,bigint),public.edu_add_question_answer(uuid,uuid,uuid,uuid,text),public.edu_resolve_question(uuid,uuid) from public,anon,authenticated;
grant execute on function edu_private.record_question_answer(),edu_private.capture_legacy_question_answer(),public.edu_read_question_thread(uuid,uuid,bigint),public.edu_add_question_answer(uuid,uuid,uuid,uuid,text),public.edu_resolve_question(uuid,uuid) to service_role;
commit;
