import assert from 'node:assert/strict';
import fs from 'node:fs';
import { randomUUID as id } from 'node:crypto';
import { fixture } from './lesson-block-review.mjs';
const read = name => fs.readFileSync(new URL('../../supabase/migrations/' + name, import.meta.url),'utf8');
const doc = (track='daily',day=1) => ({schemaVersion:1,blocks:[{id:'q',type:'text',content:'PRIVATE CONTENT'}],checklist:[],progression:{track,dayNumber:day},completion:{mode:track==='daily'?'mentor':'self',requireAnswers:false,requireQuizPass:track==='learning'}});
export async function setup(t) {
 const f = await fixture(doc()); t.after(()=>f.db.close());
 await f.db.exec(`reset role;
 alter table profiles add column email text; alter table profiles add column phone text;
 alter table courses add column category text default 'paid_class';
 alter table cohorts add column name text default '가상 기수'; alter table cohorts add column status text default 'active'; alter table cohorts add column operation_end_at timestamptz; alter table cohorts add column operation_start_at timestamptz;
 alter table curriculum_weeks add column week_number integer default 1;
 alter table curriculum_lessons add column day_number integer default 1;
 create table edu_ongoing_rules(lesson_id uuid primary key);
 create table edu_ongoing_completions(id uuid primary key,enrollment_id uuid,lesson_id uuid);
 create table edu_questions(id uuid primary key,user_id uuid,course_id uuid,status text,is_archived boolean default false);
 grant select on edu_ongoing_rules,edu_ongoing_completions,edu_questions to service_role;
 update profiles set full_name='합성 회원',email='qa@example.test' where role='member';`);
 await f.db.exec(read('20260928194336_edu_member_messages.sql'));
 await f.db.exec('alter table edu_member_messages add column is_notice boolean not null default false');
 await f.db.exec(read('20260929012022_member_visits.sql'));
 await f.db.exec(read('20261001024207_alumni_read_mode.sql').split('-- Project the same')[0]+'commit;');
 await f.db.exec(read('20261001180000_cohort_curriculum_visibility.sql').split('-- Direct PostgREST')[0]+'commit;');
 await f.db.exec(read('20261002102250_learner_feedback_completion_gate.sql'));
 await f.db.exec(read('20261008052124_learning_care_dashboard.sql'));
 const original=read('20261008052124_learning_care_dashboard.sql').split('create function public.edu_admin_learning_care')[0];
 await f.db.exec(original.replaceAll('edu_learning_care_cells','edu_learning_care_cells_reference')+'commit;');
 await f.db.exec(read('20261008073102_learning_care_batch_projection.sql'));
 await f.db.exec(read('20261008084305_learning_care_cohort_history.sql'));
 f.parity=async()=>{const result=await f.db.query('select edu_private.edu_learning_care_cells($1) as actual, edu_private.edu_learning_care_cells_reference($1) as expected',[f.enrollment]);assert.deepEqual(result.rows[0].actual,result.rows[0].expected);};
 await f.db.exec('set role service_role');
 f.snapshot = async(actor=f.admin,cohort=f.cohort)=>{await f.parity();return(await f.db.query('select edu_admin_learning_care($1,$2) as r',[actor,cohort])).rows[0].r;};
 f.personal = async(actor=f.student)=>(await f.db.query('select edu_member_learning_care($1) as r',[actor])).rows[0].r;
 f.send = async({actor=f.admin,request=id(),recipients=[f.student],lesson=f.lesson,cohort=f.cohort,content='함께 이어가요'}={})=>(await f.db.query('select edu_send_learning_care($1,$2,$3,$4,$5,$6) as r',[actor,request,cohort,lesson,recipients,content])).rows[0].r;
 f.add = async(track,day,published=true)=>{const lesson=id(),revision=id();await f.db.query('insert into curriculum_lessons(id,week_id,is_published,day_number) values($1,$2,true,$3)',[lesson,f.week,day]);await f.db.query('insert into edu_cohort_lesson_visibility(cohort_id,lesson_id,is_published) values($1,$2,$3)',[f.cohort,lesson,published]);await f.db.query('select edu_save_lesson_blocks($1,$2,null,$3,$4)',[f.admin,lesson,revision,doc(track,day)]);return{lesson,revision};};
 f.submitCell=async(lesson=f.lesson,revision=f.revision)=>{const values={blocks:{},checklist:[]},write=id();await f.db.query('select edu_save_block_draft($1,$2,$3,$4,null,$5,$6)',[f.student,lesson,f.enrollment,revision,write,values]);return(await f.db.query('select edu_submit_lesson_blocks($1,$2,$3,$4,$5,$6,$7) as r',[f.student,lesson,f.enrollment,revision,write,id(),values])).rows[0].r;};
 f.approve=async(s,decision='approved')=>(await f.db.query('select edu_decide_lesson_blocks($1,$2,$3,$4,$5,$6) as r',[f.admin,s.id,s.stateId,id(),decision,'합성 피드백'])).rows[0].r;
 return f;
}
